#!/bin/sh

# Setup environment
INIT_DIR=`pwd`

. $INIT_DIR/set_aliases

remtrace Getting netcore related source code
safe_md netcore
remtrace Getting EiffelSoftware.Runtime.dll netcore source code
exprt -r $ORIGO_SVN_REVISION $DEFAULT_ORIGO_SVN/Src/Eiffel/eiffel/com_il_generation/Core netcore/Eiffel/eiffel/com_il_generation/Core
remtrace Getting md consumer netcore source code
exprt -r $ORIGO_SVN_REVISION $DEFAULT_ORIGO_SVN/Src/dotnet/consumer_netcore netcore/dotnet/consumer_netcore
tgz netcore
move netcore.tar.bz2 $EXPORT_DIR/.
fullrd netcore
