#!/bin/sh

remtrace Retrieve unstable libraries
cd $1
md unstable
cd unstable

remtrace README.txt
exprt -r $ORIGO_SVN_REVISION $DEFAULT_ORIGO_SVN/Src/unstable/README.txt README.txt

remtrace library
exprt -r $ORIGO_SVN_REVISION $DEFAULT_ORIGO_SVN/Src/unstable/library library


remtrace Retrieve contrib libraries and examples
cd $1
md contrib
cd contrib

remtrace README.txt
exprt -r $ORIGO_SVN_REVISION $DEFAULT_ORIGO_SVN/Src/contrib/README.txt README.txt

remtrace library
exprt -r $ORIGO_SVN_REVISION $DEFAULT_ORIGO_SVN/Src/contrib/library library

remtrace examples
exprt -r $ORIGO_SVN_REVISION $DEFAULT_ORIGO_SVN/Src/contrib/examples examples
