#ifndef _YACC_ERROR_MESSAGE_H_
#define _YACC_ERROR_MESSAGE_H_

char* yacc_error_message_list[]=
{
/* 0 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 1 */ "Keyword \"class\" missing",
/* 2 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 3 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 4 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 5 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 6 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 7 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 8 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 9 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 10 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 11 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 12 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 13 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 14 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 15 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 16 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 17 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 18 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 19 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 20 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 21 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 22 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 23 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 24 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 25 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 26 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 27 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 28 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 29 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 30 */ "Feature_clause:\nwrong character after a \"feature\" keyword",
/* 31 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 32 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 33 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 34 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 35 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 36 */ "Client_list:\nMissing \"{\" or an Class Identifier",
/* 37 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 38 */ "Class_List:\nMissing : \"}\"",
/* 39 */ "Class_List:\nMissing : \"Class Identifier\"",
/* 40 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 41 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 42 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 43 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 44 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 45 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 46 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 47 */ "Feature_name_mark:\nMissing feature name, feature clause in bad place  or \"end\"",
/* 48 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 49 */ "Feature_name:\nMissing keyword \"as\" or class name",
/* 50 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 51 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 52 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 53 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 54 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 55 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 56 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 57 */ "Constant_or_routine:\nkeyword \"is\" missing in a class declaration",
/* 58 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 59 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 60 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 61 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 62 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 63 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 64 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 65 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 66 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 67 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 68 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 69 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 70 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 71 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 72 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 73 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 74 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 75 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 76 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 77 */ "Rename_list:\nWaiting for comma or feature name",
/* 78 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 79 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 80 */ "Missing feature name or export clause",
/* 81 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 82 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 83 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 84 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 85 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 86 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 87 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 88 */ "Missing feature name",
/* 89 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 90 */ "Feature_list:\nMissing comma or feature name",
/* 91 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 92 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 93 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 94 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 95 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 96 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 97 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 98 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 99 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 100 */ "Select :\n Missing separator or keyword or clauses in a bad order",
/* 101 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 102 */ "Select :\nMissing feature name",
/* 103 */ "Select :\ninheritance clauses in a wrong order",
/* 104 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 105 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 106 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 107 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 108 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 109 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 110 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 111 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 112 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 113 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 114 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 115 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 116 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 117 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 118 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 119 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 120 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 121 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 122 */ "External : Empty parameter"
/* 123 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 124 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 125 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 126 */ "Missing :=",
/* 127 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 128 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 129 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 130 */ "Local_declarations:\nMissing \"local\" or \"do\" or \"once\" ",
/* 131 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 132 */ "Local_declarations:\nMissing or wrong Entity declaration",
/* 133 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 134 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 135 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 136 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 137 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 138 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 139 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 140 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 141 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 142 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 143 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 144 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 145 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 146 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 147 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 148 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 149 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 150 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 151 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 152 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 153 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 154 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 155 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 156 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 157 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 158 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 159 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 160 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 161 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 162 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 163 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 164 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 165 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 166 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 167 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 168 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 169 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 170 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 171 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 172 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 173 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 174 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 175 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 176 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 177 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 178 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 179 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 180 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 181 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 182 */ "Missing \"]\""
/* 183 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 184 */ "Genericity : precise the constraint"
/* 185 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 186 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 187 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 188 */ "The number of generic parameters is limited to 8",
/* 189 */ "Missing declaration of creation feature",
/* 190 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 191 */ "Missing Boolean condition",
/* 192 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 193 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 194 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 195 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 196 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 197 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 198 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 199 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 200 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 201 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 202 */ "empty inspect clause : Missing \"when\" or \"end\" ",
/* 203 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 204 */ "inspect : missing end",
/* 205 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 206 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 207 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 208 */ "Inspect : Missing feature name",
/* 209 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 210 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 211 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 212 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 213 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 214 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 215 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 216 */ "Inspect : when clause empty",
/* 217 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 218 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 219 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 220 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 221 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 222 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 223 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 224 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 225 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 226 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 227 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 228 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 229 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 230 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 231 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 232 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 233 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 234 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 235 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 236 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 237 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 238 */ "Class_invariant:\nMissing Top Structure",
/* 239 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 240 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 241 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 242 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 243 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 244 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 245 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 246 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 247 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 248 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 249 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 250 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 251 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 252 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 253 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 254 */ "Class_invariant:\nBody declaration in a deferred class or instruction out of structure",
/* 255 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 256 */ "Invalid intructions in a rescue clause",
/* 257 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 258 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 259 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 260 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 261 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 262 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 263 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 264 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 265 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 266 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 267 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 268 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 269 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 270 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 271 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 272 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 273 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 274 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 275 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 276 */ "Missing ! before or after feature name",
/* 277 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 278 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 279 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 280 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 281 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 282 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 283 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 284 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 285 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 286 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 287 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 288 */ "Missing left parenthesis or \"until\" or  \"end\" keyword or else symbolous alone having nothing to do there",
/* 289 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 290 */ "Waiting for a class name, should not have parameters",
/* 291 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 292 */ "Missing left parenthesis or \"loop\" or \"then\" keyword",
/* 293 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 294 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 295 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 296 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 297 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 298 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 299 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 300 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 301 */ "And : too many features",
/* 302 */ "And then : too many features",
/* 303 */ "Or : too many features", 
/* 304 */ "Or else : too many features",
/* 305 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 306 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 307 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 308 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 309 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 310 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 311 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 312 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 313 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 314 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 315 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 316 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 317 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 318 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 319 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 320 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 321 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 322 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 323 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 324 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 325 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 326 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 327 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 328 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 329 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 330 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 331 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 332 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 333 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 334 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 335 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 336 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 337 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 338 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 339 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 340 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 341 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 342 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 343 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 344 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 345 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 346 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 347 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 348 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 349 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 350 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 351 */ "Missing double quote in manifest string",
/* 352 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 353 */ "Missing right parenthesis",
/* 354 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 355 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 356 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 357 */ "Identifier:\nMissing Identifier",
/* 358 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 359 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 360 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 361 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 362 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 363 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 364 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 365 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 366 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 367 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 368 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 369 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 370 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 371 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 372 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 373 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 374 */ "Missing indexing string",
/* 375 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 376 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 377 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 378 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 379 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 380 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 381 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 382 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 383 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 384 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 385 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 386 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 387 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 388 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 389 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 390 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 391 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 392 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 393 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 394 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 395 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 396 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 397 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 398 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 399 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message",
/* 400 */ "Please, contact ISE at http://support.eiffel.com\nto report the missing error message"
};

#endif
