#!/bin/sh
# shell script for running our standalone example

if test -e EIFGEN/F_code/standalone
then
    cd EIFGEN/F_code
else
    cd EIFGEN/W_code
fi

standalone -ORBNoIIOPProxy -ORBNoIIOPServer -ORBNoCodeSets