indexing

	description: "Parser token codes"
	generator: "geyacc version 1.5"

class EXTERNAL_TOKENS

feature -- Token codes

	TE_COLON: INTEGER is 258
	TE_LPARAN: INTEGER is 259
	TE_RPARAN: INTEGER is 260
	TE_COMMA: INTEGER is 261
	TE_ADDRESS: INTEGER is 262
	TE_STAR: INTEGER is 263
	TE_LT: INTEGER is 264
	TE_GT: INTEGER is 265
	TE_DQUOTE: INTEGER is 266
	TE_ACCESS: INTEGER is 267
	TE_C_LANGUAGE: INTEGER is 268
	TE_CPP_LANGUAGE: INTEGER is 269
	TE_INLINE: INTEGER is 270
	TE_DELETE: INTEGER is 271
	TE_DLL_LANGUAGE: INTEGER is 272
	TE_DLLWIN_LANGUAGE: INTEGER is 273
	TE_ENUM: INTEGER is 274
	TE_GET_PROPERTY: INTEGER is 275
	TE_IL_LANGUAGE: INTEGER is 276
	TE_MACRO: INTEGER is 277
	TE_FIELD: INTEGER is 278
	TE_JAVA_LANGUAGE: INTEGER is 279
	TE_DEFERRED: INTEGER is 280
	TE_OPERATOR: INTEGER is 281
	TE_SET_FIELD: INTEGER is 282
	TE_SET_PROPERTY: INTEGER is 283
	TE_SIGNATURE: INTEGER is 284
	TE_STATIC: INTEGER is 285
	TE_CREATOR: INTEGER is 286
	TE_STATIC_FIELD: INTEGER is 287
	TE_SET_STATIC_FIELD: INTEGER is 288
	TE_STRUCT: INTEGER is 289
	TE_TYPE: INTEGER is 290
	TE_USE: INTEGER is 291
	TE_ID: INTEGER is 292

end -- class EXTERNAL_TOKENS
