CC = cl
CFLAGS = -MT -DEIF_THREADS -I. -I$(ISE_EIFFEL)\bench\spec\windows\include 
OBJECTS = main.obj fext.obj
EIFLIB = libbank_account.lib
LD = link
MAKE=nmake

all: $(OBJECTS) $(EIFLIB) tst

main.obj: 
	$(CC) $(CFLAGS) -c main.c -Fo$@

fext.obj: 
	$(CC) $(CFLAGS) -c fext.c -Fo$@ 

$(EIFLIB):
	cd EIFGEN\F_code
	$(MAKE) cecil
	cd ..\..
tst: $(OBJECTS)  $(EIFLIB)
	$(LD) @cecil.lnk




