note
	description: "[
					Generated by EiffelRibbon tool
																							]"
	date: "$Date$"
	revision: "$Revision$"

class
	DROP_DOWN_BUTTON_IN_APP_MENU

inherit
	DROP_DOWN_BUTTON_IN_APP_MENU_IMP

create
	{EV_RIBBON_APPLICATION_MENU_GROUP} make_with_command_list

feature {NONE} -- Action handling


end

