note
	description: "[
					Generated by EiffelRibbon tool
					Don't edit this file, since it will be replaced by EiffelRibbon tool
					generated files everytime
																							]"
	date: "$Date$"
	revision: "$Revision$"

deferred class
	MENU_GROUP_IMP

inherit
	EV_RIBBON_APPLICATION_MENU_GROUP

feature {NONE} -- Initialization

	create_interface_objects
			-- Create objects
		do
			create button_in_app_menu.make_with_command_list (<<{COMMAND_NAME_CONSTANTS}.button_in_app_menu>>)
			create drop_down_button_in_app_menu.make_with_command_list (<<{COMMAND_NAME_CONSTANTS}.drop_down_button_in_app_menu>>)

			create buttons.make (1)
			buttons.extend (button_in_app_menu)
			buttons.extend (drop_down_button_in_app_menu)

		end

feature -- Query

	button_in_app_menu: BUTTON_IN_APP_MENU
	drop_down_button_in_app_menu: DROP_DOWN_BUTTON_IN_APP_MENU


end

