variables:
  EIFFEL_SRC: '$CI_PROJECT_DIR/Src'

build:
  stage: build
  script:
    - Write-Host "Just to define the 'build' stage name"
  except:
    refs:
      - tags
      - branches

linux_build_job:
  stage: build
  tags:
    - linux
  when: manual
  script:
    - cd $CI_PROJECT_DIR
    - export current_dir=$PWD ; echo current_dir=$current_dir ; cd ..
    - curl -sSL https://www.eiffel.org/setup/install.sh | bash -s nightly > eiffel.rc
    - source ./eiffel.rc
    - echo `ec -version`
    - cd $current_dir
    - export EIFFEL_SRC=$PWD/Src
    - export EWEASEL=$PWD/eweasel
    - export ISE_LIBRARY=$EIFFEL_SRC
    - export XEBRA_LIBRARY=$EIFFEL_SRC/framework/web/xebra/eiffel_projects/library
    - echo Check projects compilation status...
    - cd $EIFFEL_SRC/library
    - export COMPILEALL_DIR=library 
    - export COMPILEALL_IGNORE=scripts/CI/compile_all/stable_others.ini
    - sh $EIFFEL_SRC/scripts/CI/travis-ci-compile_all.sh $EIFFEL_SRC/$COMPILEALL_DIR $EIFFEL_SRC/$COMPILEALL_IGNORE
  only:
    refs:
      - master
      - merge_requests
      - schedules

stages:
  - build

