version: 1.0.{build}

image: Visual Studio 2015

init:
    - git config --global core.autocrlf input
    - mkdir -p c:\dev\eiffel
    - nuget install 7ZipCLI -ExcludeVersion -OutputDirectory c:\dev\eiffel\bin
    - set PATH=c:\dev\eiffel\bin\7ZipCLI\tools;%PATH%

clone_folder: c:\dev\%APPVEYOR_BUILD_ID%\trunk

shallow_clone: true

environment:
    ISE_C_COMPILER: msc_vc140
    ISE_PLATFORM: win64
    EIFFEL_SRC: c:\dev\%APPVEYOR_BUILD_ID%\trunk\Src
    ISE_LIBRARY: c:\dev\%APPVEYOR_BUILD_ID%\trunk\Src
    XEBRA_LIBRARY: c:\dev\%APPVEYOR_BUILD_ID%\trunk\Src\framework\web\xebra\eiffel_projects\library
    EWEASEL: c:\dev\%APPVEYOR_BUILD_ID%\trunk\eweasel

install:
    - appveyor DownloadFile https://www.eiffel.org/setup/install.bat -FileName %TEMP%\get-eiffelstudio.bat 
    - call %TEMP%\get-eiffelstudio.bat nightly > c:\dev\eiffel\eiffel_nightly.bat 
    - call c:\dev\eiffel\eiffel_nightly.bat 
    - echo EiffelStudio versions... 
    - cd c:\dev\eiffel && ec -version && compile_all -version

build_script:
    - set COMPILE_ALL_CMD=compile_all -ecb -clean -melt -list_failures -options dotnet=false -log_verbose
    - cd %EIFFEL_SRC%\Eiffel && %COMPILE_ALL_CMD% &&
    - cd %EIFFEL_SRC%\tools && %COMPILE_ALL_CMD% &&
    - cd %EIFFEL_SRC%\framework && %COMPILE_ALL_CMD% &&
    - cd %EIFFEL_SRC%\library && %COMPILE_ALL_CMD%

