FLAG = -c -I$(ISE_EIFFEL)\bench\spec\$(ISE_PLATFORM)\include -Ic:\msdev\include

LIBS = wsock32.lib $(ISE_EIFFEL)\library\net\spec\$(ISE_PLATFORM)\lib\wnetwork.lib $(ISE_EIFFEL)\bench\spec\$(ISE_PLATFORM)\lib\wkbench.lib

OBJS = dog.obj subs.obj 

CC = cl



win_dog: $(OBJS)

		$(CC) -o win_dog $(OBJS) $(LIBS)

                del  dog.obj

                del  subs.obj



dog.obj:   dog.c dog.h

		$(CC) $(FLAG) dog.c



subs.obj:   subs.c dog.h

		$(CC) $(FLAG) subs.c



