indexing
	description: "Objects that represent an EV_DIALOG.%
		%The original version of this class was generated by EiffelBuild."
	author: ""
	date: "$Date$"
	revision: "$Revision$"

deferred class
	GB_FIXED_POSITIONER_IMP

inherit
	EV_DIALOG
		redefine
			initialize, is_in_default_state
		end
			
	CONSTANTS
		undefine
			is_equal, default_create, copy
		end

-- This class is the implementation of an EV_DIALOG generated by EiffelBuild.
-- You should not modify this code by hand, as it will be re-generated every time
-- modifications are made to the project.

feature {NONE}-- Initialization

	initialize is
			-- Initialize `Current'.
		local 
			l_ev_vertical_box_1, l_ev_vertical_box_2, l_ev_vertical_box_3: EV_VERTICAL_BOX
			l_ev_horizontal_box_1, l_ev_horizontal_box_2: EV_HORIZONTAL_BOX
			l_ev_frame_1, l_ev_frame_2: EV_FRAME
			l_ev_cell_1: EV_CELL
		do
			Precursor {EV_DIALOG}
			initialize_constants
			
				-- Create all widgets.
			create l_ev_vertical_box_1
			create l_ev_horizontal_box_1
			create split_area
			create scrollable_area
			create drawing_area
			create l_ev_vertical_box_2
			create list
			create l_ev_frame_1
			create l_ev_vertical_box_3
			create snap_button
			create grid_visible_control
			create l_ev_cell_1
			create grid_size_control
			create l_ev_horizontal_box_2
			create l_ev_frame_2
			create prompt_label
			create ok_button
			
				-- Build_widget_structure.
			extend (l_ev_vertical_box_1)
			l_ev_vertical_box_1.extend (l_ev_horizontal_box_1)
			l_ev_horizontal_box_1.extend (split_area)
			split_area.extend (scrollable_area)
			scrollable_area.extend (drawing_area)
			split_area.extend (l_ev_vertical_box_2)
			l_ev_vertical_box_2.extend (list)
			l_ev_vertical_box_2.extend (l_ev_frame_1)
			l_ev_frame_1.extend (l_ev_vertical_box_3)
			l_ev_vertical_box_3.extend (snap_button)
			l_ev_vertical_box_3.extend (grid_visible_control)
			l_ev_vertical_box_3.extend (l_ev_cell_1)
			l_ev_cell_1.extend (grid_size_control)
			l_ev_vertical_box_1.extend (l_ev_horizontal_box_2)
			l_ev_horizontal_box_2.extend (l_ev_frame_2)
			l_ev_frame_2.extend (prompt_label)
			l_ev_horizontal_box_2.extend (ok_button)
			
			set_minimum_width (300)
			set_minimum_height (250)
			set_title ("EV_FIXED child positioner")
			l_ev_vertical_box_1.disable_item_expand (l_ev_horizontal_box_2)
			scrollable_area.set_minimum_width (100)
			scrollable_area.set_minimum_height (100)
			scrollable_area.set_item_width (0)
			scrollable_area.set_item_height (0)
			l_ev_vertical_box_2.disable_item_expand (l_ev_frame_1)
			l_ev_frame_1.set_text ("Grid properties")
			l_ev_vertical_box_3.disable_item_expand (snap_button)
			l_ev_vertical_box_3.disable_item_expand (grid_visible_control)
			l_ev_vertical_box_3.disable_item_expand (l_ev_cell_1)
			snap_button.set_text ("Snap to grid")
			grid_visible_control.set_text ("Visible")
			l_ev_horizontal_box_2.disable_item_expand (ok_button)
			l_ev_frame_2.set_style (1)
			ok_button.set_text ("Done")
			
				--Connect events.
			drawing_area.pointer_motion_actions.extend (agent track_movement (?, ?, ?, ?, ?, ?, ?))
			drawing_area.pointer_button_press_actions.extend (agent button_pressed (?, ?, ?, ?, ?, ?, ?, ?))
			drawing_area.pointer_button_release_actions.extend (agent button_released (?, ?, ?, ?, ?, ?, ?, ?))
			drawing_area.resize_actions.extend (agent update_pixmap_size (?, ?, ?, ?))
			prompt_label.pointer_button_press_actions.extend (agent clicked_for_enlarge (?, ?, ?, ?, ?, ?, ?, ?))
			ok_button.select_actions.extend (agent ok_pressed)
				-- Close the application when an interface close
				-- request is recieved on `Current'. i.e. the cross is clicked.

				-- Call `user_initialization'.
			user_initialization
		end

feature -- Access

	split_area: EV_HORIZONTAL_SPLIT_AREA
	scrollable_area: EV_SCROLLABLE_AREA
	drawing_area: EV_DRAWING_AREA
	list: EV_LIST
	snap_button, grid_visible_control: EV_CHECK_BUTTON
	grid_size_control: EV_SPIN_BUTTON
	prompt_label: EV_LABEL
	ok_button: EV_BUTTON

feature {NONE} -- Implementation

	is_in_default_state: BOOLEAN is
			-- Is `Current' in its default state?
		do
			-- Re-implement if you wish to enable checking
			-- for `Current'.
			Result := True
		end
	
	user_initialization is
			-- Feature for custom initialization, called at end of `initialize'.
		deferred
		end
	
	track_movement (a_x, a_y: INTEGER; a_x_tilt, a_y_tilt, a_pressure: DOUBLE; a_screen_x, a_screen_y: INTEGER) is
			-- Called by `pointer_motion_actions' of `drawing_area'.
		deferred
		end
	
	button_pressed (a_x, a_y, a_button: INTEGER; a_x_tilt, a_y_tilt, a_pressure: DOUBLE; a_screen_x, a_screen_y: INTEGER) is
			-- Called by `pointer_button_press_actions' of `drawing_area'.
		deferred
		end
	
	button_released (a_x, a_y, a_button: INTEGER; a_x_tilt, a_y_tilt, a_pressure: DOUBLE; a_screen_x, a_screen_y: INTEGER) is
			-- Called by `pointer_button_release_actions' of `drawing_area'.
		deferred
		end
	
	update_pixmap_size (a_x, a_y, a_width, a_height: INTEGER) is
			-- Called by `resize_actions' of `drawing_area'.
		deferred
		end
	
	clicked_for_enlarge (a_x, a_y, a_button: INTEGER; a_x_tilt, a_y_tilt, a_pressure: DOUBLE; a_screen_x, a_screen_y: INTEGER) is
			-- Called by `pointer_button_press_actions' of `prompt_label'.
		deferred
		end
	
	ok_pressed is
			-- Called by `select_actions' of `ok_button'.
		deferred
		end
	

end -- class GB_FIXED_POSITIONER_IMP
