USE [$(database_name)]
GO
INSERT [dbo].[Questions] ([QuestionID], [Text], [Type]) VALUES (11, N'I am on the ISE email dispatch list', 1)
INSERT [dbo].[Questions] ([QuestionID], [Text], [Type]) VALUES (12, N'I am on the Eiffel World email dispatch list', 1)
INSERT [dbo].[Questions] ([QuestionID], [Text], [Type]) VALUES (13, N'I am on the TOOLS Conferences email dispatch list', 1)
INSERT [dbo].[Questions] ([QuestionID], [Text], [Type]) VALUES (14, N'I am on the .NET Experts email dispatch list', 1)
INSERT [dbo].[Questions] ([QuestionID], [Text], [Type]) VALUES (15, N'I am on the Santa Barbara email dispatch list', 1)
INSERT [dbo].[Questions] ([QuestionID], [Text], [Type]) VALUES (16, N'I am on the Press email dispatch list', 1)
INSERT [dbo].[Questions] ([QuestionID], [Text], [Type]) VALUES (20, N'I am checked', NULL)
INSERT [dbo].[Questions] ([QuestionID], [Text], [Type]) VALUES (21, N'I am an active Eiffel user', 1)
INSERT [dbo].[Questions] ([QuestionID], [Text], [Type]) VALUES (22, N'I am an active Eiffel user under maintenance', 1)
INSERT [dbo].[Questions] ([QuestionID], [Text], [Type]) VALUES (23, N'I am on the University Partnership Program dispatch list', 1)
INSERT [dbo].[Questions] ([QuestionID], [Text], [Type]) VALUES (26, N'I am on the ENViSioN mailing list', 1)
INSERT [dbo].[Questions] ([QuestionID], [Text], [Type]) VALUES (27, N'I have been invited to join the ISE_users group', 1)
INSERT [dbo].[Questions] ([QuestionID], [Text], [Type]) VALUES (28, N'I am in the Programmer''s Registry', 1)
