USE [$(database_name)]
GO
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'1  ', N'')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'AFG', N'Afghanistan')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ALB', N'Albania')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ALG', N'Algeria')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'AME', N'American Samoa')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'AND', N'Andorra')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ANG', N'Angola')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ANI', N'Antigua and Barbuda')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ANT', N'Antarctica')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ANU', N'Anguilla')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ARG', N'Argentina')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ARM', N'Armenia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ARU', N'Aruba')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ASI', N'Asia/Pacific Region')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'AST', N'Austria')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'AUS', N'Australia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'AZE', N'Azerbaijan')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BAB', N'Barbados')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BAH', N'Bahamas')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BAN', N'Bangladesh')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BAR', N'Bahrain')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BEL', N'Belarus')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BEN', N'Benin')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BER', N'Bermuda')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BGM', N'Belgium')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BHU', N'Bhutan')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BLZ', N'Belize')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BOL', N'Bolivia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BOS', N'Bosnia and Herzegovina')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BOT', N'Botswana')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BOU', N'Bouvet Island')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BRA', N'Brazil')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BRI', N'British Indian Ocean Territory')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BRN', N'Brunei Darussalam')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BUL', N'Bulgaria')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BUR', N'Burkina Faso')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'BUU', N'Burundi')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'CAM', N'Cambodia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'CAN', N'Canada')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'CAP', N'Cape Verde')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'CAR', N'Cameroon')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'CAY', N'Cayman Islands')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'CEN', N'Central African Republic')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'CHA', N'Chad')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'CHI', N'Chile')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'CHN', N'China')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'CHR', N'Christmas Island')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'COC', N'Cocos (Keeling) Islands')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'COL', N'Colombia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'COM', N'Comoros')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'CON', N'Congo')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'COO', N'Cook Islands')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'COS', N'Costa Rica')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'COT', N'Cote D''Ivoire')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'CRO', N'Croatia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'CUB', N'Cuba')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'CYP', N'Cyprus')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'CZE', N'Czech Republic')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'DEN', N'Denmark')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'DJI', N'Djibouti')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'DOM', N'Dominica')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'DOR', N'Dominican Republic')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ECU', N'Ecuador')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'EGY', N'Egypt')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ELS', N'El Salvador')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'EQU', N'Equatorial Guinea')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ERI', N'Eritrea')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'EST', N'Estonia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ETH', N'Ethiopia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'EUR', N'Europe')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'FAL', N'Falkland Islands (Malvinas)')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'FAR', N'Faroe Islands')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'FIJ', N'Fiji')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'FIN', N'Finland')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'FRA', N'France')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'FRG', N'French Guiana')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'FRP', N'French Polynesia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'FRS', N'French Southern Territories')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'GAB', N'Gabon')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'GAM', N'Gambia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'GEO', N'Georgia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'GER', N'Germany')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'GHA', N'Ghana')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'GIB', N'Gibraltar')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'GRA', N'Grenada')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'GRE', N'Greece')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'GRN', N'Greenland')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'GUA', N'Guadeloupe')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'GUB', N'Guinea-Bissau')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'GUI', N'Guinea')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'GUM', N'Guam')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'GUT', N'Guatemala')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'GUY', N'Guyana')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'HAI', N'Haiti')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'HEA', N'Heard Island and McDonald Islands')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'HNG', N'Hong Kong')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'HOL', N'Holy See (Vatican City State)')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'HON', N'Honduras')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'HUN', N'Hungary')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ICE', N'Iceland')
GO
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'IND', N'India')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'INN', N'Indonesia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'IRA', N'Iran')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'IRE', N'Ireland')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'IRQ', N'Iraq')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ISR', N'Israel')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ITA', N'Italy')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'JAM', N'Jamaica')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'JAP', N'Japan')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'JOR', N'Jordan')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'KAZ', N'Kazakstan')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'KEN', N'Kenya')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'KIR', N'Kiribati')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'KOR', N'Korea')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'KUW', N'Kuwait')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'KYR', N'Kyrgyzstan')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'LAO', N'Lao People''s Democratic Republic')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'LAT', N'Latvia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'LEB', N'Lebanon')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'LES', N'Lesotho')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'LIA', N'Libyan Arab Jamahiriya')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'LIB', N'Liberia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'LIE', N'Liechtenstein')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'LIT', N'Lithuania')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'LUX', N'Luxembourg')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MAA', N'Mauritania')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MAC', N'Macau')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MAD', N'Madagascar')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MAI', N'Mali')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MAL', N'Malawi')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MAR', N'Marshall Islands')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MAS', N'Mauritius')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MAT', N'Malta')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MAY', N'Mayotte')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MCD', N'Macedonia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MEX', N'Mexico')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MIC', N'Micronesia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MLD', N'Maldives')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MLY', N'Malaysia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MNG', N'Mongolia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MNT', N'Montserrat')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MOL', N'Moldova')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MON', N'Monaco')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MOR', N'Morocco')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MOZ', N'Mozambique')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MRT', N'Martinique')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'MYA', N'Myanmar')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'NAM', N'Namibia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'NAU', N'Nauru')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'NEA', N'Netherlands Antilles')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'NEC', N'New Caledonia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'NEP', N'Nepal')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'NET', N'Netherlands')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'NEZ', N'New Zealand')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'NGR', N'Nigeria')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'NIC', N'Nicaragua')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'NIG', N'Niger')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'NIU', N'Niue')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'NOR', N'Norfolk Island')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'NRW', N'Norway')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'NTM', N'Northern Mariana Islands')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'OMA', N'Oman')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'PAK', N'Pakistan')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'PAL', N'Palau')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'PAN', N'Panama')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'PAP', N'Papua New Guinea')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'PAR', N'Paraguay')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'PER', N'Peru')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'PHI', N'Philippines')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'PIT', N'Pitcairn')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'PLS', N'Palestinian Territory')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'POL', N'Poland')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'POR', N'Portugal')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'PUE', N'Puerto Rico')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'QAT', N'Qatar')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'REU', N'Reunion')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ROM', N'Romania')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'RUS', N'Russian Federation')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'RWA', N'Rwanda')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SAH', N'Saint Helena')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SAK', N'Saint Kitts and Nevis')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SAL', N'Saint Lucia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SAM', N'Samoa')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SAN', N'San Marino')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SAO', N'Sao Tome and Principe')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SAP', N'Saint Pierre and Miquelon')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SAT', N'Satellite Provider')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SAU', N'Saudi Arabia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SAV', N'Saint Vincent and the Grenadines')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SEN', N'Senegal')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SEY', N'Seychelles')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SIE', N'Sierra Leone')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SIN', N'Singapore')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SLN', N'Slovenia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SLO', N'Slovakia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SOG', N'South Georgia and the South Sandwich Islands')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SOL', N'Solomon Islands')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SOM', N'Somalia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SOU', N'South Africa')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SPA', N'Spain')
GO
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SRI', N'Sri Lanka')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SUD', N'Sudan')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SUR', N'Suriname')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SVA', N'Svalbard and Jan Mayen')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SWA', N'Swaziland')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SWE', N'Sweden')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SWI', N'Switzerland')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'SYR', N'Syrian Arab Republic')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'TAI', N'Taiwan')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'TAJ', N'Tajikistan')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'TAN', N'Tanzania')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'TCI', N'Turks and Caicos Islands')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'THA', N'Thailand')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'TIM', N'East Timor')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'TOG', N'Togo')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'TOK', N'Tokelau')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'TON', N'Tonga')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'TRI', N'Trinidad and Tobago')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'TRK', N'Turkmenistan')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'TUN', N'Tunisia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'TUR', N'Turkey')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'TUV', N'Tuvalu')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'UAE', N'United Arab Emirates')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'UGA', N'Uganda')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'UKD', N'United Kingdom')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'UKR', N'Ukraine')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'UNK', N'Unknown')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'URU', N'Uruguay')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'USA', N'United States')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'USM', N'United States Minor Outlying Islands')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'UZB', N'Uzbekistan')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'VAN', N'Vanuatu')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'VEN', N'Venezuela')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'VIE', N'Vietnam')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'VIR', N'Virgin Islands')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'WAL', N'Wallis and Futuna')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'WES', N'Western Sahara')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'YEM', N'Yemen')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'YUG', N'Yugoslavia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ZAI', N'Zaire')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ZAM', N'Zambia')
INSERT [dbo].[Countries] ([CountryID], [Country]) VALUES (N'ZIM', N'Zimbabwe')
