indexing
	description: "Objects that represent an EV_DIALOG.%
		%The original version of this class was generated by EiffelBuild."
	author: ""
	date: "$Date$"
	revision: "$Revision$"

deferred class
	GB_NAMING_DIALOG_IMP

inherit
	EV_DIALOG
		redefine
			initialize, is_in_default_state
		end
			
	CONSTANTS
		undefine
			is_equal, default_create, copy
		end

-- This class is the implementation of an EV_DIALOG generated by EiffelBuild.
-- You should not modify this code by hand, as it will be re-generated every time
-- modifications are made to the project.

feature {NONE}-- Initialization

	initialize is
			-- Initialize `Current'.
		do
			Precursor {EV_DIALOG}
			initialize_constants
			
			create l_vertical_box_27
			create l_vertical_box_28
			create prompt_label
			create l_horizontal_box_29
			create name_field
			create l_cell_21
			create l_horizontal_box_30
			create l_cell_22
			create ok_button
			create l_cell_23
			create cancel_button
			
			extend (l_vertical_box_27)
			l_vertical_box_27.extend (l_vertical_box_28)
			l_vertical_box_28.extend (prompt_label)
			l_vertical_box_28.extend (l_horizontal_box_29)
			l_horizontal_box_29.extend (name_field)
			l_vertical_box_28.extend (l_cell_21)
			l_vertical_box_28.extend (l_horizontal_box_30)
			l_horizontal_box_30.extend (l_cell_22)
			l_horizontal_box_30.extend (ok_button)
			l_horizontal_box_30.extend (l_cell_23)
			l_horizontal_box_30.extend (cancel_button)
			
			set_minimum_width (250)
			set_minimum_height (120)
			set_title ("Display window")
			l_vertical_box_27.set_padding_width (large_spacing_width)
			l_vertical_box_27.set_border_width (small_padding)
			l_vertical_box_28.disable_item_expand (prompt_label)
			l_vertical_box_28.disable_item_expand (l_horizontal_box_29)
			l_vertical_box_28.disable_item_expand (l_horizontal_box_30)
			prompt_label.align_text_left
			l_cell_21.set_minimum_height (small_padding)
			l_horizontal_box_30.disable_item_expand (ok_button)
			l_horizontal_box_30.disable_item_expand (l_cell_23)
			l_horizontal_box_30.disable_item_expand (cancel_button)
			ok_button.set_text (ok_button_text)
			ok_button.set_minimum_width (default_button_width)
			l_cell_23.set_minimum_width (small_padding)
			cancel_button.set_text (cancel_button_text)
			cancel_button.set_minimum_width (default_button_width)
			
				-- Close the application when an interface close
				-- request is recieved on `Current'. i.e. the cross is clicked.

				-- Call `user_initialization'.
			user_initialization
		end
feature {NONE} -- Implementation

	is_in_default_state: BOOLEAN is
			-- Is `Current' in its default state?
		do
			-- Re-implement if you wish to enable checking
			-- for `Current'.
			Result := True
		end
	
	user_initialization is
			-- Feature for custom initialization, called at end of `initialize'.
		deferred
		end
	
	l_vertical_box_27, l_vertical_box_28: EV_VERTICAL_BOX
	prompt_label: EV_LABEL
	l_horizontal_box_29, l_horizontal_box_30: EV_HORIZONTAL_BOX
	name_field: EV_TEXT_FIELD
	l_cell_21, l_cell_22, l_cell_23: EV_CELL
	ok_button, cancel_button: EV_BUTTON
	end -- class GB_NAMING_DIALOG_IMP
