<?php
// $Id: ise_ctr.module,v 1.3.2.16.2.6 2010/05/14 19:20:44 heyrocker Exp $

/**
 * @file
 *  Link general user functionalities to services module.
 */

/**
 * Implementation of hook_perm().
 */
function ise_ctr_perm() {
  return array(
    'access content', 'edit content'
  );
}

/**
 * Implementation of hook_service().
 */
function ise_ctr_service() {
  return array(
    // ise.ctr.get_logs_range
    array(
      '#method'           => 'ise.ctr.get_logs_range',
      '#callback'         => 'ise_ctr_get_logs_range',
      '#access callback'  => 'ise_ctr_log_access',
      '#file'             => array('file' => 'inc', 'module' => 'ise_ctr'),
      '#args'             => array(
        array(
          '#name'           => 'repository',
          '#type'           => 'string',
          '#description'    => t('Associated repository.'),
        ),
	  ),
      '#return'           => 'struct',
      '#help'             => t('Get Known Range of logs.')
    ),
    // ise.ctr.get_missing_logs
    array(
      '#method'           => 'ise.ctr.get_missing_logs',
      '#callback'         => 'ise_ctr_get_missing_logs',
      '#access callback'  => 'ise_ctr_log_access',
      '#file'             => array('file' => 'inc', 'module' => 'ise_ctr'),
      '#args'             => array(
        array(
          '#name'           => 'repository',
          '#type'           => 'string',
          '#description'    => t('Associated repository.'),
        ),
        array(
          '#name'           => 'lower',
          '#type'           => 'string',
          '#description'    => t('Lower revision.'),
        ),
        array(
          '#name'           => 'upper',
          '#type'           => 'string',
          '#description'    => t('Upper revision.'),
        ),
      ),
      '#return'           => 'struct',
      '#help'             => t('Get Missing logs from range of logs.')
    ),
    // ise.ctr.get_log
    array(
      '#method'           => 'ise.ctr.get_log',
      '#callback'         => 'ise_ctr_get_log',
      '#access callback'  => 'ise_ctr_log_access',
      '#file'             => array('file' => 'inc', 'module' => 'ise_ctr'),
      '#args'             => array(
        array(
          '#name'           => 'repository',
          '#type'           => 'string',
          '#description'    => t('Associated repository.'),
        ),
        array(
          '#name'           => 'rev',
          '#type'           => 'string',
          '#description'    => t('Log revision.'),
        ),
      ),
      '#return'           => 'struct',
      '#help'             => t('Get Information on Log.')
    ),
    // ise.ctr.get_review
    array(
      '#method'           => 'ise.ctr.get_review',
      '#callback'         => 'ise_ctr_get_review',
      '#access callback'  => 'ise_ctr_get_review_access',
      '#file'             => array('file' => 'inc', 'module' => 'ise_ctr'),
      '#args'             => array(
        array(
          '#name'           => 'repository',
          '#type'           => 'string',
          '#description'    => t('Associated repository.'),
        ),
        array(
          '#name'           => 'rev',
          '#type'           => 'string',
          '#description'    => t('Log revision.'),
        ),
        array(
          '#name'           => 'user',
          '#type'           => 'string',
          '#description'    => t('Review author.'),
        ),
      ),
      '#return'           => 'struct',
      '#help'             => t('Post Review for Log.')
    ),
    // ise.ctr.post_logs
    array(
      '#method'           => 'ise.ctr.post_logs',
      '#callback'         => 'ise_ctr_post_logs',
      '#access callback'  => 'ise_ctr_log_access',
      '#file'             => array('file' => 'inc', 'module' => 'ise_ctr'),
      '#args'             => array(
        array(
          '#name'           => 'repository',
          '#type'           => 'string',
          '#description'    => t('Associated repository.'),
        ),
        array(
          '#name'           => 'value',
          '#type'           => 'struct',
          '#optional'       => TRUE,
          '#source'         => 'data',
          '#description'    => t('Logs to upload.'),
         ),
      ),
      '#return'           => 'struct',
      '#help'             => t('Upload logs.')
    ),
    // ise.ctr.post_review
    array(
      '#method'           => 'ise.ctr.post_review',
      '#callback'         => 'ise_ctr_post_review',
      '#access callback'  => 'ise_ctr_post_review_access',
      '#file'             => array('file' => 'inc', 'module' => 'ise_ctr'),
      '#args'             => array(
        array(
          '#name'           => 'repository',
          '#type'           => 'string',
          '#description'    => t('Associated repository.'),
        ),
        array(
          '#name'           => 'rev',
          '#type'           => 'string',
          '#description'    => t('Log revision.'),
        ),
        array(
          '#name'           => 'user',
          '#type'           => 'string',
          '#description'    => t('Posting user.'),
        ),
        array(
          '#name'           => 'value',
          '#type'           => 'struct',
          '#optional'       => TRUE,
          '#source'         => 'data',
          '#description'    => t('Value of post (approve, refuse, comment) if needed.'),
        ),
      ),
      '#return'           => 'struct',
      '#help'             => t('Post Review for Log.')
    ),
  );
}
