// Generated .IDL file (by the OLE/COM Object Viewer)
// 
// typelib filename: EiffelSoftware.MetadataConsumer.tlb

[
  uuid(7D31F607-90E3-3281-9917-B6A798492F76),
  version(6.4)
]
library EiffelSoftware_MetadataConsumer
{
    // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
    importlib("STDOLE2.TLB");

    // Forward declare all types defined in this typelib
    interface EiffelSoftware_MetadataConsumer_Interop_I_COM_CACHE_MANAGER;

    [
      odl,
      uuid(E1FFE1AC-8466-4E95-9C3F-3FEB392F8F32),
      version(1.0),
      dual,
      oleautomation
    ]
    interface EiffelSoftware_MetadataConsumer_Interop_I_COM_CACHE_MANAGER : IDispatch {
        [id(0x60020000)]
        HRESULT consume_assembly(
                        [in] BSTR a_name, 
                        [in] BSTR a_version, 
                        [in] BSTR a_culture, 
                        [in] BSTR a_key, 
                        [in] VARIANT_BOOL a_info_only);
        [id(0x60020001)]
        HRESULT consume_assembly_from_path(
                        [in] BSTR a_path, 
                        [in] VARIANT_BOOL a_info_only, 
                        [in] BSTR a_references);
        [restricted] void Missing9();
        [id(0x60020003)]
        HRESULT initialize();
        [id(0x60020004)]
        HRESULT initialize_with_path([in] BSTR a_path);
        [id(0x60020005)]
        HRESULT is_initialized([out, retval] VARIANT_BOOL* pRetVal);
        [id(0x60020006)]
        HRESULT is_successful([out, retval] VARIANT_BOOL* pRetVal);
        [id(0x60020007)]
        HRESULT last_error_message([out, retval] BSTR* pRetVal);
        [id(0x60020008)]
        HRESULT unload();
    };

    [
      uuid(E1FFE1AC-C88F-4CD5-BBCB-1B1B82308654),
      version(1.0)
    ]
    coclass EiffelSoftware_MetadataConsumer_Interop_COM_CACHE_MANAGER {
        [default] interface EiffelSoftware_MetadataConsumer_Interop_I_COM_CACHE_MANAGER;
    };
};

