class 
	APPLICATION_IDS

feature -- Access

	Create_project_check_constant: INTEGER is 1050
	Browse_button_constant: INTEGER is 1009
	Definition_file_browse_button_constant: INTEGER is 1051
	Code_type_info_static_constant: INTEGER is 1053
	Proxy_stub_static_constant: INTEGER is 1028
	Wizard_ps_dialog_constant: INTEGER is 105
	In_process_check_constant: INTEGER is 1013
	Component_type_static_constant: INTEGER is 1054
	Virtual_table_standard_radio_constant: INTEGER is 1058
	New_string_constant: INTEGER is 1
	Exit_string_constant: INTEGER is 4
	Wizard_generated_code_type_dialog_constant: INTEGER is 106
	Eiffel_code_compilation_check_constant: INTEGER is 1048
	C_code_compilation_check_constant: INTEGER is 1049
	Wizard3_bitmap_constant: INTEGER is 116
	Wizard1_bitmap_constant: INTEGER is 114
	Help_button_constant: INTEGER is 1018
	Destination_folder_edit_constant: INTEGER is 1010
	Output_static_constant: INTEGER is 1032
	Definition_file_edit_constant: INTEGER is 1007
	Code_type_static_constant: INTEGER is 1052
	Proxy_stub_input_edit_constant: INTEGER is 1030
	Open_string_constant: INTEGER is 2
	Server_check_constant: INTEGER is 1020
	Progress_static_constant: INTEGER is 1046
	Save_string_constant: INTEGER is 3
	Destination_folder_browse_button_constant: INTEGER is 1012
	Progress_dialog_constant: INTEGER is 121
	Wizard_final_dialog_constant: INTEGER is 104
	Wizard4_bitmap_constant: INTEGER is 117
	Launch_string_constant: INTEGER is 5
	Generate_string_constant: INTEGER is 6
	Introduction4_static_constant: INTEGER is 1044
	Title_static_constant: INTEGER is 1048
	Warnings_check_constant: INTEGER is 1060
	Id_back_constant: INTEGER is 1040
	Virtual_table_universal_radio_constant: INTEGER is 1057
	Marshallin_description_static_constant: INTEGER is 1059
	Output_info_static_constant: INTEGER is 1038
	Wizard2_bitmap_constant: INTEGER is 115
	Out_of_process_check_constant: INTEGER is 1056
	Information_check_constant: INTEGER is 1061
	Automation_radio_constant: INTEGER is 1029
	Wizard_definition_file_dialog_constant: INTEGER is 101
	Destination_folder_static_constant: INTEGER is 1044
	Wizard_idl_dialog_constant: INTEGER is 102
	Client_check_constant: INTEGER is 1019
	Output_question_static_constant: INTEGER is 1033
	Marshalling_static_constant: INTEGER is 1044
	Destination_folder_input_static_constant: INTEGER is 1016
	Marshalling_question_static_constant: INTEGER is 1056
	Definition_file_static_constant: INTEGER is 1043
	Open_project_check_constant: INTEGER is 1049
	Definition_file_input_static_constant: INTEGER is 1008
	Eiffel_code_compilation_static_constant: INTEGER is 1047
	Toolbar_bitmap_constant: INTEGER is 113
	Progress_bar_constant: INTEGER is 1045
	Wizard_first_choice_dialog_constant: INTEGER is 123
	Title_question_static_constant: INTEGER is 1044

end -- class APPLICATION_IDS

--|-------------------------------------------------------------------
--| This class was automatically generated by Resource Bench
--| Copyright (C) 1996-1997, Interactive Software Engineering, Inc.
--|
--| 270 Storke Road, Suite 7, Goleta, CA 93117 USA
--| Telephone 805-685-1006
--| Fax 805-685-6869
--| Information e-mail <info@eiffel.com>
--| Customer support e-mail <support@eiffel.com>
--|-------------------------------------------------------------------
