.TH CECIL 1  "November 10, 1999" "ISE" "CECIL Programmer's Manual"
.SH NAME
eif_access	\- access an Eiffel object
.SH SYNOPSYS
.nf
\fB#include "eif_hector.h"\fB
.sp
.BI "EIF_REFERENCE eif_access (EIF_OBJECT " obj ");"
.fi
.SH DESCRIPTION
The \fBeif_access()\fP macro accesses the Eiffel object \fIobj\fP. 
.SH RETURN VALUE
It returns
the Eiffel reference protected by \fIobj\fP and which can be 
passed to Eiffel routines. 
.SH CONFORMANCE
ISE Eiffel 4.1 and later.
.SH SEE ALSO
.BR eif_wean "(1) , "eif_adopt "(1), "eif_protect "(1)." 


