.TH CECIL 1  "November 10, 1999" "ISE" "CECIL Programmer's Manual"
.SH NAME
eif_type_id	\- return the type identifier. 
.SH SYNOPSYS
.nf
\fB#include "eif_gen_conf.h"\fP
.sp
.BI "EIF_TYPE_ID eif_type_id (char * " type ");"
.fi
.SH DESCRIPTION
The \fBeif_type_id()\fP function returns the type 
identifier corresponding to \fItype\fP, which is the name of the type.
.SH RETURN VALUE
The \fBeif_type_id()\fP function returns the type
.RS
.TP
.B EIF_NO_TYPE
\fBtype\fP does not match any type in the system. Check the name of the type, or include the class for this type in your system. 
.SH NOTES
An error cannot be caught by a visible exception. 
.br 
The type is not necessary visible.
.SH CONFORMANCE
ISE Eiffel 4.3 and later.
.SH COMPATIBILITY
\fBeif_type_id()\fP is equivalent to \fBeif_type_by_name()\fP.
With Eiffel 4.2 and earlier, use \fBeif_generic_type()\fP for generic types.
.SH SEE ALSO
.BR eif_reference_function "(1) , "eif_procedure "(1) , "eif_type "(1), "eif_name "(1)." 


