.TH CECIL 1  "November 10, 1999" "ISE" "CECIL Programmer's Manual"
.SH NAME
eif_protect	\- protect an Eiffel reference
.SH SYNOPSYS
.nf
\fB#include "eif_hector.h"\fB
.sp
.BI "EIF_OBJECT eif_protect (EIF_REFERENCE " ref ");"
.fi
.SH DESCRIPTION
The \fBeif_protect()\fP function protects the Eiffel reference \fIref\fP
from the GC. It keeps a reference on it so that the Garbage Collector does
not collect it if it is not referenced from Eiffel any longer. 
.SH RETURN VALUE
The \fBeif_protect()\fP function returns an EIF_OBJECT. 
This EIF_OBJECT can be used 
later on to access \fIref\fP with \fBeif_access ()\fP.
.SH CONFORMANCE
ISE Eiffel 4.4 and later.
.SH COMPATIBILTY
It is equivalent to \fBhenter()\fP, which is deprecated.
.SH SEE ALSO
.BR eif_access "(1), " eif_protect "(1) , " eif_wean "(1)."


