#!/bin/sh

INITIAL_DIR=`pwd`

remtrace Compile the C libraries C code
remtrace expat
cd C_library/expat
make
remtrace libpng
cd $INITIAL_DIR/C_library/libpng
if echo "$ISE_PLATFORM" | grep "linux" >/dev/null 2>&1; then
	cp scripts/makefile.linux .
	make -f makefile.linux
elif [ "$ISE_PLATFORM" = "solaris-2.5+" ]; then
	cp scripts/makefile.solaris .
	make -f makefile.solaris
else
	rep = $ISE_PLATFORM
	if [ ! -f "scripts/makefile.$rep" ]; then
		echo Here are the available makefiles:
		ls scripts
		echo "What is the extension of the makefile that should be used?"
		while [ ! -f "scripts/makefile.$rep" ]; do
			echo "scripts/makefile.$rep doesn't exist... Try another one"
			read rep
		done
	fi
	cp scripts/makefile.$rep .
	make -f makefile.$rep
fi

remtrace zlib
cd $INITIAL_DIR/C_library/zlib
make                                                                        


remtrace Compile the Eiffel libraries C code
remtrace event
cd $INITIAL_DIR/library/event/Clib
default_make
remtrace exml
cd $INITIAL_DIR/library/exml/compiler_specific/ise/clib
default_make
remtrace net
cd $INITIAL_DIR/library/net/Clib
default_make
remtrace time
cd $INITIAL_DIR/library/time/Clib
default_make
remtrace vision2
cd $INITIAL_DIR/library/vision2/Clib
default_make
cd $INITIAL_DIR/library/vision2/implementation/gtk/Clib
default_make
remtrace gel
cd $INITIAL_DIR/library/gel/glib
configure
cd $INITIAL_DIR


