#!/bin/sh

if [ "$1" == "local" ]; then
	echo $1
	export REMOTE=mosis
	cp -f make_solaris ~/
	# Launch platform specific scripts
	rsh $REMOTE "cd local/TEST_DELIV ; mv -f ~/make_solaris ."
	rsh $REMOTE "cd local/TEST_DELIV ; bash ./make_solaris"

ftp -n << EOF 
verbose 
open mosis.ise 
user manus manus 
binary
get local/TEST_DELIV/PorterPackage/Eiffel52_enterprise.tgz Eiffel52_solaris.tgz
get local/TEST_DELIV/PorterPackage/Eiffel52_enterprise.iso Eiffel52_enterprise_solaris.iso
close 
EOF

	echo Solaris compilation done
else
	rm -rf PorterPackage
	tar xvf ~/PorterPackage_enterprise.tar
	cd PorterPackage
	export ISE_PLATFORM=solaris-2.5+
	bash compile_exes
	bash make_images
fi
