#!/bin/sh

remtrace Should be called by make_delivery

#remtrace Recompile syntax_updater
#cd $EIFFEL_SRC/tools/syntax_updater
#clean_project
#finalize syntax_updater.ecf syntax_updater
#tgz_ccode syntax_updater syntax_updater.tar.bz2
#if [ ! -f syntax_updater.tar.bz2 ]; then
#	echo Could not finalize a new syntax_updater
#	CANCEL
#fi
#clean_project
#move syntax_updater.tar.bz2 $EXPORT_DIR/bin

remtrace Recompile compile_all
cd $EIFFEL_SRC/tools/compile_all
clean_project
finalize compile_all.ecf compile_all
tgz_ccode compile_all compile_all.tar.bz2
if [ ! -f compile_all.tar.bz2 ]; then
	echo Could not finalize a new compile_all
	CANCEL
fi
clean_project
move compile_all.tar.bz2 $EXPORT_DIR/bin

remtrace Recompile eiffel_image_embedder
cd $EIFFEL_SRC/tools/eiffel_image_embedder
clean_project
finalize eimgemb.ecf eiffel_image_embedder
tgz_ccode eiffel_image_embedder eimgemb.tar.bz2
if [ ! -f eimgemb.tar.bz2 ]; then
	echo Could not finalize a new Eiffel image embedder
	CANCEL
fi
clean_project
move eimgemb.tar.bz2 $EXPORT_DIR/bin
