#!/bin/sh

if [ $# -eq 0 ]; then 
	echo Usage: make_images platform
	exit 1
fi

export ISE_PLATFORM=$1

# Set up the environment
. set_aliases
OLD_PATH=$PATH
INIT_DIR=`pwd`
EIFFEL_SRC=$EXPORT_DIR; export EIFFEL_SRC
ISE_EIFFEL=$FINAL_INSTALL_DIR; export ISE_EIFFEL
INSTALL_DIR=$FINAL_INSTALL_DIR

echo > $COMPILE_LOG

if [ -z "$ISE_PLATFORM" ]; then
	remtrace Couldnt find environment variable ISE_PLATFORM
	CANCEL
fi

# Check everything's fine
if [ ! -d $EXPORT_DIR ]; then
	remtrace Couldnt find the directory with the tgzs.
	CANCEL
fi

if [ -f ec_ent.tar.gz ]; then
	MULTIPLE_EDITIONS="True"
else
	MULTIPLE_EDITIONS=""
fi

cd $EXPORT_DIR

if [ ! -d cdrom ]; then
	mkdir cdrom
fi

if [ ! -f Eiffel57_deliv.tgz ]; then
	remtrace Saving empty delivery in Eiffel57_deliv.tgz
	tar -cf Eiffel57_deliv.tar Eiffel57 
	gzip Eiffel57_deliv.tar
fi

if [ ! -d Eiffel57 ]; then
	remtrace Extracting current delivery
	gunzip -c Eiffel57_deliv.tgz | tar -xf -
fi


# Copy runtime files
cp -r runtimes/* $INSTALL_DIR/studio/spec/$ISE_PLATFORM/lib

if [ "$MULTIPLE_EDITIONS" ]; then
	remtrace Preparing Enterprise version
	gunzip -c $EXPORT_DIR/ecs/ec_ent.gz > $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec
	chmod a+rx $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec
	chmod go-w $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec 

	remtrace copying CD key validator
	move setup $INSTALL_DIR/register
	chmod a+rx $INSTALL_DIR/register
	mkdir $INSTALL_DIR/setup
	cp $INSTALL_DIR/studio/bitmaps/png/logo.png $INSTALL_DIR/setup/install_logo.png
	cp $INSTALL_DIR/studio/bitmaps/png/activation.png $INSTALL_DIR/setup/install_left.png

	remtrace Building Enterprise CD image
	mv Eiffel57 cdrom
	make_cd_image Eiffel57_enterprise Eiffel57_enterprise.iso cdrom
	gzip Eiffel57_enterprise.iso
	mv Eiffel57_enterprise.iso.gz Eiffel57_enterprise_$SVN_VERSION-$ISE_PLATFORM.iso.gz
	mv cdrom/Eiffel57 Eiffel57
	tar -cf Eiffel57_enterprise_$SVN_VERSION-$ISE_PLATFORM.tar Eiffel57 
	gzip Eiffel57_enterprise_$SVN_VERSION-$ISE_PLATFORM.tar
fi

remtrace Preparing GPL version
gunzip -c $EXPORT_DIR/ecs/ec_gpl.gz > $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec
chmod a+rx $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec
chmod go-w $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec 

remtrace Building GPL CD image
mv Eiffel57 cdrom
make_cd_image Eiffel57_gpl Eiffel57_gpl.iso cdrom
gzip Eiffel57_gpl.iso
mv Eiffel57_gpl.iso.gz Eiffel57_gpl_$SVN_VERSION-$ISE_PLATFORM.iso.gz
mv cdrom/Eiffel57 Eiffel57
tar -cf Eiffel57_gpl_$SVN_VERSION-$ISE_PLATFORM.tar Eiffel57
gzip Eiffel57_gpl_$SVN_VERSION-$ISE_PLATFORM.tar
