#!/bin/sh

# our script requires sh aliased to bash.

if [ $# -ge 4 ]; then
	remote_host=$1
	user=$2
	platform=$3
	port=$4
	echo $local
	scp -P $port PorterPackage_all.tar $user@$remote_host:
		# Launch platform specific scripts
	ssh -p $port -l $user $remote_host "mkdir TEST_DELIV"
	ssh -p $port -l $user $remote_host "cd TEST_DELIV ; \rm -rf PorterPackage"
	ssh -p $port -l $user $remote_host "cd TEST_DELIV ; tar xvf ~/PorterPackage_all.tar"
		#Note: we use `export' because we expect the remote shell to be bash.
	ssh -p $port -l $user $remote_host "cd TEST_DELIV/PorterPackage; export ISE_PLATFORM=$platform ; bash ./compile_exes"
	ssh -p $port -l $user $remote_host "cd TEST_DELIV/PorterPackage; export ISE_PLATFORM=$platform ; bash ./make_images"

	scp -P $port $user@$remote_host:TEST_DELIV/PorterPackage/Eiffel57_enterprise.tgz Eiffel57_$platform.tgz
	scp -P $port $user@$remote_host:TEST_DELIV/PorterPackage/Eiffel57_gpl.tgz Eiffel57_gpl_$platform.tgz
	scp -P $port $user@$remote_host:TEST_DELIV/PorterPackage/Eiffel57_enterprise.iso.gz Eiffel57_enterprise_$platform.iso.gz
	scp -P $port $user@$remote_host:TEST_DELIV/PorterPackage/Eiffel57_gpl.iso.gz Eiffel57_gpl_$platform.iso.gz

	echo Compilation for $platform is now done
else
	echo Usage: [local] host username platform
fi
