#!/bin/sh
 
# Set up the environment
. set_aliases
LASTTIME=`date +%s`
LASTTIME_TOT=`date +%s`
OLD_PATH=$PATH
INIT_DIR=`pwd`
EIFFEL_SRC=$EXPORT_DIR; export EIFFEL_SRC
ISE_EIFFEL=$FINAL_INSTALL_DIR; export ISE_EIFFEL
INSTALL_DIR=$FINAL_INSTALL_DIR

echo > $COMPILE_LOG

if [ -z "$ISE_PLATFORM" ]; then
	remtrace Couldnt find environment variable ISE_PLATFORM
	CANCEL
fi

# Check everything's fine
if [ ! -d $EXPORT_DIR ]; then
	remtrace Couldnt find the directory with the tgzs.
	CANCEL
fi

if [ -e free_rt ]; then
	MULTIPLE_EDITIONS="True"
else
	MULTIPLE_EDITIONS=""
fi

cd $EXPORT_DIR

if [ ! -e cdrom ]; then
	mkdir cdrom
fi

if [ ! -f Eiffel53_deliv.tgz ]; then
	remtrace Saving empty delivery in Eiffel53_deliv.tgz
	tar -c Eiffel53 | gzip -c > Eiffel53_deliv.tgz
fi

if [ ! -e Eiffel53 ]; then
	remtrace Extracting current delivery
	gunzip -c Eiffel53_deliv.tgz | tar -xf -
fi


if [ "$MULTIPLE_EDITIONS" ]; then
	remtrace Preparing Free version
	cp -r free_rt/* $INSTALL_DIR/studio/spec/$ISE_PLATFORM/lib
	gunzip -c $EXPORT_DIR/ecs/ec_free.gz > $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec
	chmod a+rx $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec
	chmod go-w $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec 

	remtrace Building Home CD image
	mv Eiffel53 cdrom
	cp cdrom/Eiffel53/INSTALL cdrom	
	make_cd_image Eiffel53_free Eiffel53_free.iso cdrom
	mv cdrom/Eiffel53 Eiffel53
	tar -c Eiffel53 | gzip -c > Eiffel53_free.tgz
fi

remtrace Preparing Enterprise version
cp -r commercial_rt/* $INSTALL_DIR/studio/spec/$ISE_PLATFORM/lib
gunzip -c $EXPORT_DIR/ecs/ec_enterprise.gz > $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec
chmod a+rx $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec
chmod go-w $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec 

remtrace copying Build
gunzip -c $EXPORT_DIR/build/build.gz > $INSTALL_DIR/build/spec/$ISE_PLATFORM/bin/build
chmod a+rx $INSTALL_DIR/build/spec/$ISE_PLATFORM/bin/build
chmod go-w $INSTALL_DIR/build/spec/$ISE_PLATFORM/bin/build 

remtrace copying CD key validator
move setup $INSTALL_DIR/register
chmod a+rx $INSTALL_DIR/register
mkdir $INSTALL_DIR/setup
cp $INSTALL_DIR/studio/bitmaps/png/logo.png $INSTALL_DIR/setup/install_logo.png
cp $INSTALL_DIR/studio/bitmaps/png/activation.png $INSTALL_DIR/setup/install_left.png

remtrace Building Enterprise CD image
mv Eiffel53 cdrom
cp cdrom/Eiffel53/INSTALL cdrom	
make_cd_image Eiffel53_enterprise Eiffel53_enterprise.iso cdrom
mv cdrom/Eiffel53 Eiffel53
tar -c Eiffel53 | gzip -c > Eiffel53_enterprise.tgz
