#!/bin/sh

# Create a delivery from scratch for all ISE supported platforms we have at ISE,
# ie solaris, ppx, linux and linux RH9.

# Let's initialize our environments variables
. ./set_aliases

# Let's create an enterprise package for Unix
rm -rf PorterPackage

# Let's create all packages
echo "\n" | /bin/sh make_delivery $1

# Let's keep an archive of this package
if [ ! -f PorterPackage_all.tar ]; then
	tar cvf PorterPackage_all.tar PorterPackage
fi

./compile_for_all_platforms &
