#!/bin/sh

if [ "$1" == "local" ]; then
	echo $1
	export REMOTE=mojo.ise
	cp -f make_linux_fedora ~/
	# Launch platform specific scripts
	rsh $REMOTE "cd local/TEST_DELIV ; mv -f ~/make_linux_fedora ."
	rsh $REMOTE "cd local/TEST_DELIV ; ./make_linux_fedora"

ftp -n << EOF 
verbose 
open mojo.ise 
user manus manus 
binary
get local/TEST_DELIV/PorterPackage/Eiffel55_enterprise.tgz Eiffel55_fedora.tgz
get local/TEST_DELIV/PorterPackage/Eiffel55_free.tgz Eiffel55_free_fedora.tgz
get local/TEST_DELIV/PorterPackage/Eiffel55_enterprise.iso.gz Eiffel55_enterprise_fedora.iso.gz
get local/TEST_DELIV/PorterPackage/Eiffel55_university.iso.gz Eiffel55_university_fedora.iso.gz
get local/TEST_DELIV/PorterPackage/Eiffel55_free.iso.gz Eiffel55_free_fedora.iso.gz
close 
EOF

	echo Linux for Fedora Core 2 compilation done
else
	rm -rf PorterPackage
	tar xvf ~/PorterPackage_all.tar
	cd PorterPackage
	export ISE_PLATFORM=linux-glibc2.1
	compile_exes
	make_images
fi
