#!/bin/sh
set -e

echo "ISE_EIFFEL: $ISE_EIFFEL"
. ./packaging/config.sh


# Create unix layout in debian directoy
./make_unix_layout $DEBIAN_DIR/$PRODUCT


# Prepare debian packaging files
. $DEBIAN_DIR/control.sh
. $DEBIAN_DIR/changelog.sh
cp $PACKAGING_DIR/license $DEBIAN_DIR/copyright
. $DEBIAN_DIR/postinst.sh
. $DEBIAN_DIR/prerm.sh


cd $DEBIAN_DIR


# First we check if there are any docs (architecture independent)
if test -d "$PRODUCT$DOCS_DIR"; then
	mkdir -p $PRODUCT-doc$DOCS_DIR
	mv $PRODUCT$DOCS_DIR/* $PRODUCT-doc$DOCS_DIR/
	rm -rf $PRODUCT$DOCS_DIR

	debuild --check-dirname-level 0 binary-indep >>$LOG 2>>$LOG
	echo Finished building package $PRODUCT-doc

	# Clean up doc related build files
	rm -rf $DEBIAN_DIR/$PRODUCT-doc
else
	echo "$0: No $DOCS_DIR present, $PRODUCT-doc package will not be created"
fi


# Then we build the main package (architecture dependent)
debuild --check-dirname-level 0 binary-arch >>$LOG 2>>$LOG
echo Finished building package $PRODUCT


# Clean up all build files
cd ../
rm -r $DEBIAN_DIR/$PRODUCT
debuild clean
rm $DEBIAN_DIR/$PRODUCT.postinst
rm $DEBIAN_DIR/$PRODUCT.prerm
rm $DEBIAN_DIR/copyright
rm $DEBIAN_DIR/control
rm $DEBIAN_DIR/changelog

