#!/bin/sh

if [ $# -eq 0 ]; then 
	echo Usage: make_images platform
	exit 1
fi

ISE_PLATFORM=$1; export ISE_PLATFORM

# Set up the environment
. ./set_aliases
OLD_PATH=$PATH
INIT_DIR=`pwd`
EIFFEL_SRC=$EXPORT_DIR; export EIFFEL_SRC
ISE_EIFFEL=$FINAL_INSTALL_DIR; export ISE_EIFFEL
INSTALL_DIR=$FINAL_INSTALL_DIR

echo > $COMPILE_LOG

if [ -z "$ISE_PLATFORM" ]; then
	remtrace Couldnt find environment variable ISE_PLATFORM
	CANCEL
fi

# Check everything's fine
if [ ! -d $EXPORT_DIR ]; then
	remtrace Couldnt find the directory with the compressed files.
	CANCEL
fi

if [ -f ec_ent.tar.bz2 ]; then
	MULTIPLE_EDITIONS="True"
else
	MULTIPLE_EDITIONS=""
fi

cd $EXPORT_DIR

if [ ! -d cdrom ]; then
	mkdir cdrom
fi

# Copy runtime files
cp -r runtimes/* $INSTALL_DIR/studio/spec/$ISE_PLATFORM/lib

remtrace Preparing GPL version
bunzip2 -c $EXPORT_DIR/ecs/ec_gpl.bz2 > $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec
chmod a+rx $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec
chmod go-w $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec 

remtrace Building GPL CD image
mv Eiffel61 cdrom
make_cd_image Eiffel61_gpl Eiffel61_gpl.iso cdrom
bzip2 Eiffel61_gpl.iso
mv Eiffel61_gpl.iso.bz2 Eiffel61_gpl_$FILE_SVN_REVISION-$ISE_PLATFORM.iso.bz2
mv cdrom/Eiffel61 Eiffel61
tar -cf Eiffel61_gpl_$FILE_SVN_REVISION-$ISE_PLATFORM.tar Eiffel61
bzip2 Eiffel61_gpl_$FILE_SVN_REVISION-$ISE_PLATFORM.tar

if [ "$MULTIPLE_EDITIONS" ]; then
	remtrace Preparing Enterprise version
	bunzip2 -c $EXPORT_DIR/ecs/ec_ent.bz2 > $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec
	chmod a+rx $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec
	chmod go-w $INSTALL_DIR/studio/spec/$ISE_PLATFORM/bin/ec 

	remtrace copying CD key validator
	move setup $INSTALL_DIR/register
	chmod a+rx $INSTALL_DIR/register
	mkdir $INSTALL_DIR/setup
	cp $INSTALL_DIR/studio/bitmaps/png/logo.png $INSTALL_DIR/setup/install_logo.png
	cp $INSTALL_DIR/studio/bitmaps/png/activation.png $INSTALL_DIR/setup/install_left.png

	remtrace Building Enterprise CD image
	mv Eiffel61 cdrom
	make_cd_image Eiffel61_enterprise Eiffel61_enterprise.iso cdrom
	bzip2 Eiffel61_enterprise.iso
	mv Eiffel61_enterprise.iso.bz2 Eiffel61_enterprise_$FILE_SVN_REVISION-$ISE_PLATFORM.iso.bz2
	mv cdrom/Eiffel61 Eiffel61
	tar -cf Eiffel61_enterprise_$FILE_SVN_REVISION-$ISE_PLATFORM.tar Eiffel61 
	bzip2 Eiffel61_enterprise_$FILE_SVN_REVISION-$ISE_PLATFORM.tar
fi


