#!/bin/sh
set -e

ARCH=`dpkg-architecture -qDEB_BUILD_ARCH`
if [ $# -ge 1 ]; then
	ARCH=$1
	if ! `dpkg-architecture -L | grep $ARCH >/dev/null`; then
		echo "$ARCH is not a valid architecture!"
		echo "Common architectures are: alpha amd64 i386 i686 ia64 powerpc ppc64 sparc (type \`dpkg-architecture -L\` for a complete list)"
	fi
fi


LOG=`pwd`/debian.log
>$LOG
. ./packaging/config.sh


# Create unix layout in debian directoy
DST_DIR=$DEBIAN_DIR/$PRODUCT
. ./make_unix_layout


# Prepare debian packaging files
. $DEBIAN_DIR/control.sh
. $DEBIAN_DIR/changelog.sh
cp $PACKAGING_DIR/license $DEBIAN_DIR/copyright
. $DEBIAN_DIR/postinst.sh
. $DEBIAN_DIR/prerm.sh


cd $DEBIAN_DIR


# First we check if there are any docs (architecture independent)
if test -d "$PRODUCT$DOCS_DIR"; then
	mkdir -p $PRODUCT-doc$DOCS_DIR
	mv $PRODUCT$DOCS_DIR/* $PRODUCT-doc$DOCS_DIR/
	rm -rf $PRODUCT$DOCS_DIR

	echo "Building $PRODUCT-doc package"
	debuild -eARCH=all --check-dirname-level 0 binary-indep >>$LOG 2>>$LOG

	# Clean up doc related build files
	rm -rf $DEBIAN_DIR/$PRODUCT-doc
else
	echo "$0: No $DOCS_DIR present, $PRODUCT-doc package will not be created"
fi


# Then we build the main package (architecture dependent)
echo "Building $PRODUCT ($ARCH) package"
debuild -eARCH=$ARCH --check-dirname-level 0 binary-arch >>$LOG 2>>$LOG


# Clean up all build files
cd ../
rm -r $DEBIAN_DIR/$PRODUCT
debuild clean >>$LOG 2>>$LOG
rm $DEBIAN_DIR/$PRODUCT.postinst
rm $DEBIAN_DIR/$PRODUCT.prerm
rm $DEBIAN_DIR/copyright
rm $DEBIAN_DIR/control
rm $DEBIAN_DIR/changelog

