#!/bin/sh

# our script requires sh aliased to bash.

if [ $# -ge 3 ]; then
	remote_host=$1
	user=$2
	platform=$3
	if [ $# -ge 4 ]; then
		port=$4
	else
		port=22
	fi
		# Launch platform specific scripts
	ssh -p $port -l $user $remote_host "mkdir -p local/TEST_DELIV"
	ssh -p $port -l $user $remote_host "cd local/TEST_DELIV ; \rm -rf PorterPackage"
	ssh -p $port -l $user $remote_host "cd local/TEST_DELIV ; \rm -rf PorterPackage_all.tar"
	scp -P $port PorterPackage_all.tar $user@$remote_host:local/TEST_DELIV/PorterPackage_all.tar
	ssh -p $port -l $user $remote_host "cd local/TEST_DELIV ; tar xvf PorterPackage_all.tar"
		# Do the compilation
	ssh -p $port -l $user $remote_host "cd local/TEST_DELIV/PorterPackage; sh ./compile_exes $platform"
		# Build the delivery
	ssh -p $port -l $user $remote_host "cd local/TEST_DELIV/PorterPackage; sh ./make_images $platform"

		#Upload locally
	scp -P $port "$user@$remote_host:local/TEST_DELIV/PorterPackage/Eiffel63_ent*bz2" .
	scp -P $port "$user@$remote_host:local/TEST_DELIV/PorterPackage/Eiffel63_gpl*bz2" .

		#Upload to our ftp site
	scp Eiffel63_gpl*$platform.tar.bz2 manus@eiffel.com:builds/

	echo Compilation for $platform is now done
else
	echo Usage: make_form_platform host username platform [port]
fi
