#!/bin/sh
set -e

if [ $# != 3 ]; then 
	echo Usage: make_unix_layout platform source destination
	exit 1
fi

export ISE_PLATFORM=$1

# Set up the environment
. ./set_aliases

SRC_DIR=$2
DST_DIR=$3

# some helper variables
UNIX_PLATFORM=unix
BASE_PATH=$DST_DIR$UNIX_BASE_PATH

BIN_DIR=$BASE_PATH/bin
INCLUDE_DIR=$BASE_PATH/include/$PRODUCT
LIB_DIR=$BASE_PATH/$UNIX_LIB_NAME/$PRODUCT
LIB_BIN_DIR=$LIB_DIR/studio
SHARE_DIR=$BASE_PATH/share/$PRODUCT
DOC_DIR=$BASE_PATH/share/doc/$PRODUCT
SRC_BIN_DIR=$SRC_DIR/studio/spec/$ISE_PLATFORM/bin

# Create basic directory layout

if test -d $DST_DIR; then
    echo $0: $DST_DIR exists already, please remove or choose a different directory for unix layout
    exit 1
fi

safe_md $BIN_DIR
safe_md $INCLUDE_DIR
safe_md $LIB_DIR
safe_md $LIB_BIN_DIR
safe_md $SHARE_DIR
safe_md $DOC_DIR

# Copy runtime
copy $SRC_DIR/studio/spec/$ISE_PLATFORM/include/* $INCLUDE_DIR
copy $SRC_DIR/studio/spec/$ISE_PLATFORM/lib/* $LIB_DIR

# Copy library
copy $SRC_DIR/library $LIB_DIR
copy $SRC_DIR/precomp $LIB_DIR

# Copy documentation
copy $SRC_DIR/VERSION $DOC_DIR
copy $SRC_DIR/INSTALL.readme $DOC_DIR
copy $SRC_DIR/examples $DOC_DIR

if test -d "$SRC_DIR/docs"; then
    copy $SRC_DIR/docs $DOC_DIR
else
    echo $0: New unix layout will not contain eiffel documentation
fi

# Copy esbuilder
copy $SRC_DIR/esbuilder/spec/$ISE_PLATFORM/bin/esbuilder $BIN_DIR/esbuilder$PRODUCT_VERSION
copy $SRC_DIR/esbuilder $SHARE_DIR
fullrd $SHARE_DIR/esbuilder/spec

# Copy vision2_demo
copy $SRC_DIR/vision2_demo/spec/$ISE_PLATFORM/bin/vision2_demo $BIN_DIR/vision2_demo$PRODUCT_VERSION
copy $SRC_DIR/vision2_demo $SHARE_DIR
copy $SRC_DIR/vision2_demo/readme.html $DOC_DIR/readme-vision2_demo.html
fullrd $SHARE_DIR/vision2_demo/spec
fullrf $SHARE_DIR/vision2_demo/readme.htlm

# Copy internal binaries
copy $SRC_BIN_DIR/ecdbgd $LIB_BIN_DIR/ecdbgd
copy $SRC_BIN_DIR/prelink $LIB_BIN_DIR/prelink
copy $SRC_BIN_DIR/quick_finalize $LIB_BIN_DIR/quick_finalize
copy $SRC_BIN_DIR/x2c $LIB_BIN_DIR/x2c

# Copy main binaries
copy $SRC_BIN_DIR/ec $BIN_DIR/ec$PRODUCT_VERSION
copy $SRC_BIN_DIR/estudio $BIN_DIR/estudio$PRODUCT_VERSION
copy $SRC_BIN_DIR/finish_freezing $BIN_DIR/finish_freezing$PRODUCT_VERSION

# Copy wizards
copy $SRC_DIR/studio/wizards $LIB_BIN_DIR

# Copy studio
copy $SRC_DIR/studio $SHARE_DIR/studio
fullrd $SHARE_DIR/studio/spec
fullrd $SHARE_DIR/studio/wizards

OLD_PWD=`pwd`
# Create symlinks
cd $DST_DIR/usr/bin
ln -s ec$PRODUCT_VERSION ec
ln -s estudio$PRODUCT_VERSION estudio
ln -s finish_freezing$PRODUCT_VERSION finish_freezing
ln -s esbuilder$PRODUCT_VERSION esbuilder
ln -s vision2_demo$PRODUCT_VERSION vision2_demo
cd $OLD_PWD

if [ $ISE_PLATFORM != "unix" ]; then
    move $LIB_DIR/precomp/spec/$ISE_PLATFORM $LIB_DIR/precomp/spec/unix
    move $LIB_BIN_DIR/wizards/new_projects/vision2/spec/$ISE_PLATFORM $LIB_BIN_DIR/wizards/new_projects/vision2/spec/unix
    move $LIB_BIN_DIR/wizards/others/precompile/spec/$ISE_PLATFORM $LIB_BIN_DIR/wizards/others/precompile/spec/unix
    move $LIB_DIR/library/gobo/spec/$ISE_PLATFORM $LIB_DIR/library/gobo/spec/unix
    move $LIB_DIR/library/vision2/spec/$ISE_PLATFORM $LIB_DIR/library/vision2/spec/unix
    move $LIB_DIR/library/net/spec/$ISE_PLATFORM $LIB_DIR/library/net/spec/unix
    move $SHARE_DIR/studio/config/$ISE_PLATFORM $SHARE_DIR/studio/config/unix
fi