#!/bin/sh

# Create a delivery from scratch for all ISE supported platforms we have at ISE,
# ie solaris, ppx, linux and linux RH9.

# Let's initialize our environments variables
. set_aliases

# Let's create an enterprise package for Unix
rm -rf PorterPackage

# Let's create all packages
echo "\n" | /bin/sh make_delivery all $1

# Now edit `set_aliases' in PorterPackage as we are now going for compilation mode.
cd PorterPackage
rm -f tmp
sed -e "s/\/PorterPackage//g" set_aliases > tmp
rm -f set_aliases
mv -f tmp set_aliases
cd ..

# Let's keep an archive of this package
if [ ! -f PorterPackage_all.tar ]; then
	tar cvf PorterPackage_all.tar PorterPackage
fi

cp -f PorterPackage_all.tar ~/

./compile_for_all_platforms &

#Compile and build CDs for current platform
cd PorterPackage
/bin/sh compile_exes
/bin/sh make_images
cd ..
