#!/bin/sh

remtrace free_add_ons
cd $EIFFEL_SRC
co $DEFAULT_ORIGO_SVN/free_add_ons free_add_ons

remtrace gobo
cd $EIFFEL_SRC/library
gunzip -c $EIFFEL_SRC/free_add_ons/gobo/gobo_34_unix.tgz | tar -xf -

remtrace keygen
cd $EIFFEL_SRC/library
co $DEFAULT_ISE_SVN/Src/library/keygen keygen

remtrace Compiling additional libraries
cd vision2/Clib
$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/bin/finish_freezing -library >> $INSTALL_LOG
cd ../implementation/gtk/Clib
$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/bin/finish_freezing -library >> $INSTALL_LOG

cd $EIFFEL_SRC
