#!/bin/sh

remtrace Update the Eiffel libraries source
if [ -e $EIFFEL_SRC ]; then
fullrd $EIFFEL_SRC
fi
md $EIFFEL_SRC
cd $EIFFEL_SRC
md library
cd library
remtrace base
exprt -r $DEFAULT_CVS_TAG -d base "Src/library/base"
remtrace encryption
exprt -r $DEFAULT_CVS_TAG -d encryption "Src/library/encryption"
remtrace editor
exprt -r $DEFAULT_CVS_TAG -d editor "Src/library/editor"
remtrace event
exprt -r $DEFAULT_CVS_TAG -d event "Src/library/event"
remtrace gobo
exprt -r $DEFAULT_CVS_TAG -d free_add_ons free_add_ons/gobo
gunzip -c free_add_ons/gobo_33_ise.tgz | tar -xf -
fullrd free_add_ons
remtrace graph
exprt -r $DEFAULT_CVS_TAG -d graph "Src/library/graph"
remtrace graph
exprt -r $DEFAULT_CVS_TAG -d helpers "Src/library/helpers"
remtrace keygen
exprt -r $DEFAULT_CVS_TAG -d keygen "Src/library/keygen"
remtrace lex
exprt -r $DEFAULT_CVS_TAG -d lex "Src/library/lex"
remtrace net
exprt -r $DEFAULT_CVS_TAG -d net "Src/library/net"
remtrace parse
exprt -r $DEFAULT_CVS_TAG -d parse "Src/library/parse"
remtrace patterns
exprt -r $DEFAULT_CVS_TAG -d patterns "Src/library/patterns"
remtrace preferences
exprt -r $DEFAULT_CVS_TAG -d preferences "Src/library/preferences"
remtrace time
exprt -r $DEFAULT_CVS_TAG -d time "Src/library/time"
remtrace vision2
exprt -r $DEFAULT_CVS_TAG -d vision2 "Src/library/vision2"
if [ "$1" == "gtk2" ]; then
	cp -rf vision2/implementation/gtk2/* vision2/implementation/gtk
fi
fullrd vision2/implementation/gtk2
remtrace wizard
exprt -r $DEFAULT_CVS_TAG -d wizard "Src/library/wizard"

remtrace Additional libraries for producing documentation
exprt -r $DEFAULT_CVS_TAG -d com "Src/library/com"
exprt -r $DEFAULT_CVS_TAG -d Eiffel2Java "Src/library/Eiffel2Java"
exprt -r $DEFAULT_CVS_TAG -d store "Src/library/store"
exprt -r $DEFAULT_CVS_TAG -d thread "Src/library/thread"
exprt -r $DEFAULT_CVS_TAG -d web "Src/library/web"
exprt -r $DEFAULT_CVS_TAG -d wel "Src/library/wel"

remtrace Compiling additional libraries
cd vision2/Clib
$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/bin/finish_freezing -library >> $INSTALL_LOG
cd ../implementation/gtk/Clib
$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/bin/finish_freezing -library >> $INSTALL_LOG

cd $EIFFEL_SRC
