indexing
	description: "Implemented `IFolderBrowser' Interface."
	Note: "Automatically generated by the EiffelCOM Wizard."

class
	IFOLDER_BROWSER_IMPL_PROXY

inherit
	IFOLDER_BROWSER_INTERFACE

	ECOM_QUERIABLE

creation
	make_from_other,
	make_from_pointer

feature {NONE}  -- Initialization

	make_from_pointer (cpp_obj: POINTER) is
			-- Make from pointer
		do
			initializer := ccom_create_ifolder_browser_impl_proxy_from_pointer(cpp_obj)
			item := ccom_item (initializer)
		end

feature -- Basic Operations

	folder_name (result1: CELL [STRING]) is
			-- Folder chosen by the user.
			-- `result1' [out].  
		do
			ccom_folder_name (initializer, result1)
		end

	set_starting_folder (result1: CELL [STRING]) is
			-- Set initial folder name.
			-- `result1' [in].  
		do
			ccom_set_starting_folder (initializer, result1)
		end

feature {NONE}  -- Implementation

	delete_wrapper is
			-- Delete wrapper
		do
			ccom_delete_ifolder_browser_impl_proxy(initializer)
		end

feature {NONE}  -- Externals

	ccom_folder_name (cpp_obj: POINTER; result1: CELL [STRING]) is
			-- Folder chosen by the user.
		external
			"C++ [ecom_FolderBrowser::IFolderBrowser_impl_proxy %"ecom_FolderBrowser_IFolderBrowser_impl_proxy_s.h%"](EIF_OBJECT)"
		end

	ccom_set_starting_folder (cpp_obj: POINTER; result1: CELL [STRING]) is
			-- Set initial folder name.
		external
			"C++ [ecom_FolderBrowser::IFolderBrowser_impl_proxy %"ecom_FolderBrowser_IFolderBrowser_impl_proxy_s.h%"](EIF_OBJECT)"
		end

	ccom_delete_ifolder_browser_impl_proxy (a_pointer: POINTER) is
			-- Release resource
		external
			"C++ [delete ecom_FolderBrowser::IFolderBrowser_impl_proxy %"ecom_FolderBrowser_IFolderBrowser_impl_proxy_s.h%"]()"
		end

	ccom_create_ifolder_browser_impl_proxy_from_pointer (a_pointer: POINTER): POINTER is
			-- Create from pointer
		external
			"C++ [new ecom_FolderBrowser::IFolderBrowser_impl_proxy %"ecom_FolderBrowser_IFolderBrowser_impl_proxy_s.h%"](IUnknown *)"
		end

	ccom_item (cpp_obj: POINTER): POINTER is
			-- Item
		external
			"C++ [ecom_FolderBrowser::IFolderBrowser_impl_proxy %"ecom_FolderBrowser_IFolderBrowser_impl_proxy_s.h%"]():EIF_POINTER"
		end

end -- IFOLDER_BROWSER_IMPL_PROXY

