note
	description: "[
		Objects that represent an EV_TITLED_WINDOW.
		The original version of this class was generated by EiffelBuild.
		This class is the implementation of an EV_TITLED_WINDOW generated by EiffelBuild.
		You should not modify this code by hand, as it will be re-generated every time
		 modifications are made to the project.
		 	]"
	date: "$Date$"
	revision: "$Revision$"

deferred class
	EB_METRIC_HISTORY_PANEL_IMP

inherit
	EV_VERTICAL_BOX
		redefine
			initialize, is_in_default_state
		end

feature {NONE}-- Initialization

	initialize
			-- Initialize `Current'.
		do
			Precursor {EV_VERTICAL_BOX}
			
				-- Create all widgets.
			create toolbar_area
			create first_tool_bar
			create run_btn
			create stop_btn
			create keep_detailed_result_tool_bar
			create warning_tool_bar
			create middle_tool_bar
			create remove_detailed_result_btn
			create l_ev_tool_bar_separator_1
			create remove_btn
			create group_tool_bar
			create last_tool_bar
			create l_ev_tool_bar_separator_2
			create l_ev_cell_1
			create hide_old_btn
			create old_item_area
			create hide_old_item_lbl
			create age_text
			create day_lbl
			create selector_toolbar
			create l_ev_tool_bar_separator_3
			create select_all_btn
			create deselect_all_btn
			create select_recalculatable_btn
			create deselect_recalculatable_btn
			create toolbar_cell
			create flat_grid_area
			create tree_grid_area
			
				-- Build widget structure.
			extend (toolbar_area)
			toolbar_area.extend (first_tool_bar)
			first_tool_bar.extend (run_btn)
			first_tool_bar.extend (stop_btn)
			toolbar_area.extend (keep_detailed_result_tool_bar)
			toolbar_area.extend (warning_tool_bar)
			toolbar_area.extend (middle_tool_bar)
			middle_tool_bar.extend (remove_detailed_result_btn)
			middle_tool_bar.extend (l_ev_tool_bar_separator_1)
			middle_tool_bar.extend (remove_btn)
			toolbar_area.extend (group_tool_bar)
			toolbar_area.extend (last_tool_bar)
			last_tool_bar.extend (l_ev_tool_bar_separator_2)
			toolbar_area.extend (l_ev_cell_1)
			toolbar_area.extend (hide_old_btn)
			toolbar_area.extend (old_item_area)
			old_item_area.extend (hide_old_item_lbl)
			old_item_area.extend (age_text)
			old_item_area.extend (day_lbl)
			toolbar_area.extend (selector_toolbar)
			selector_toolbar.extend (l_ev_tool_bar_separator_3)
			selector_toolbar.extend (select_all_btn)
			selector_toolbar.extend (deselect_all_btn)
			selector_toolbar.extend (select_recalculatable_btn)
			selector_toolbar.extend (deselect_recalculatable_btn)
			toolbar_area.extend (toolbar_cell)
			extend (flat_grid_area)
			extend (tree_grid_area)
			
			create string_constant_set_procedures.make (10)
			create string_constant_retrieval_functions.make (10)
			create integer_constant_set_procedures.make (10)
			create integer_constant_retrieval_functions.make (10)
			create pixmap_constant_set_procedures.make (10)
			create pixmap_constant_retrieval_functions.make (10)
			create integer_interval_constant_retrieval_functions.make (10)
			create integer_interval_constant_set_procedures.make (10)
			create font_constant_set_procedures.make (10)
			create font_constant_retrieval_functions.make (10)
			create pixmap_constant_retrieval_functions.make (10)
			create color_constant_set_procedures.make (10)
			create color_constant_retrieval_functions.make (10)
			toolbar_area.disable_item_expand (first_tool_bar)
			toolbar_area.disable_item_expand (keep_detailed_result_tool_bar)
			toolbar_area.disable_item_expand (warning_tool_bar)
			toolbar_area.disable_item_expand (middle_tool_bar)
			toolbar_area.disable_item_expand (group_tool_bar)
			toolbar_area.disable_item_expand (last_tool_bar)
			toolbar_area.disable_item_expand (l_ev_cell_1)
			toolbar_area.disable_item_expand (hide_old_btn)
			toolbar_area.disable_item_expand (old_item_area)
			toolbar_area.disable_item_expand (selector_toolbar)
			l_ev_cell_1.set_minimum_width (10)
			old_item_area.disable_item_expand (age_text)
			age_text.set_minimum_width (30)
			flat_grid_area.set_background_color (create {EV_COLOR}.make_with_8_bit_rgb (0, 0, 0))
			flat_grid_area.set_border_width (1)
			tree_grid_area.set_background_color (create {EV_COLOR}.make_with_8_bit_rgb (0, 0, 0))
			set_padding (5)
			disable_item_expand (toolbar_area)
			
			set_all_attributes_using_constants

				-- Call `user_initialization'.
			user_initialization
		end


feature -- Access

	toolbar_cell: EV_CELL
	first_tool_bar, keep_detailed_result_tool_bar, warning_tool_bar, middle_tool_bar,
	group_tool_bar, last_tool_bar, selector_toolbar: EV_TOOL_BAR
	run_btn, stop_btn, remove_detailed_result_btn,
	remove_btn, select_all_btn, deselect_all_btn, select_recalculatable_btn, deselect_recalculatable_btn: EV_TOOL_BAR_BUTTON
	toolbar_area,
	old_item_area, flat_grid_area, tree_grid_area: EV_HORIZONTAL_BOX
	hide_old_btn: EV_CHECK_BUTTON
	hide_old_item_lbl, day_lbl: EV_LABEL
	age_text: EV_TEXT_FIELD

feature {NONE} -- Implementation

	l_ev_tool_bar_separator_1, l_ev_tool_bar_separator_2, l_ev_tool_bar_separator_3: EV_TOOL_BAR_SEPARATOR
	l_ev_cell_1: EV_CELL

feature {NONE} -- Implementation

	is_in_default_state: BOOLEAN
			-- Is `Current' in its default state?
		do
			-- Re-implement if you wish to enable checking
			-- for `Current'.
			Result := True
		end
	
	user_initialization
			-- Feature for custom initialization, called at end of `initialize'.
		deferred
		end
	
feature {NONE} -- Constant setting

	set_attributes_using_string_constants
			-- Set all attributes relying on string constants to the current
			-- value of the associated constant.
		local
			s: STRING_GENERAL
		do
			from
				string_constant_set_procedures.start
			until
				string_constant_set_procedures.off
			loop
				string_constant_retrieval_functions.i_th (string_constant_set_procedures.index).call (Void)
				s := string_constant_retrieval_functions.i_th (string_constant_set_procedures.index).last_result
				string_constant_set_procedures.item.call ([s])
				string_constant_set_procedures.forth
			end
		end
		
	set_attributes_using_integer_constants
			-- Set all attributes relying on integer constants to the current
			-- value of the associated constant.
		local
			i: INTEGER
			arg1, arg2: INTEGER
			int: INTEGER_INTERVAL
		do
			from
				integer_constant_set_procedures.start
			until
				integer_constant_set_procedures.off
			loop
				integer_constant_retrieval_functions.i_th (integer_constant_set_procedures.index).call (Void)
				i := integer_constant_retrieval_functions.i_th (integer_constant_set_procedures.index).last_result
				integer_constant_set_procedures.item.call ([i])
				integer_constant_set_procedures.forth
			end
			from
				integer_interval_constant_retrieval_functions.start
				integer_interval_constant_set_procedures.start
			until
				integer_interval_constant_retrieval_functions.off
			loop
				integer_interval_constant_retrieval_functions.item.call (Void)
				arg1 := integer_interval_constant_retrieval_functions.item.last_result
				integer_interval_constant_retrieval_functions.forth
				integer_interval_constant_retrieval_functions.item.call (Void)
				arg2 := integer_interval_constant_retrieval_functions.item.last_result
				create int.make (arg1, arg2)
				integer_interval_constant_set_procedures.item.call ([int])
				integer_interval_constant_retrieval_functions.forth
				integer_interval_constant_set_procedures.forth
			end
		end
		
	set_attributes_using_pixmap_constants
			-- Set all attributes relying on pixmap constants to the current
			-- value of the associated constant.
		local
			p: EV_PIXMAP
		do
			from
				pixmap_constant_set_procedures.start
			until
				pixmap_constant_set_procedures.off
			loop
				pixmap_constant_retrieval_functions.i_th (pixmap_constant_set_procedures.index).call (Void)
				p := pixmap_constant_retrieval_functions.i_th (pixmap_constant_set_procedures.index).last_result
				pixmap_constant_set_procedures.item.call ([p])
				pixmap_constant_set_procedures.forth
			end
		end
		
	set_attributes_using_font_constants
			-- Set all attributes relying on font constants to the current
			-- value of the associated constant.
		local
			f: EV_FONT
		do
			from
				font_constant_set_procedures.start
			until
				font_constant_set_procedures.off
			loop
				font_constant_retrieval_functions.i_th (font_constant_set_procedures.index).call (Void)
				f := font_constant_retrieval_functions.i_th (font_constant_set_procedures.index).last_result
				font_constant_set_procedures.item.call ([f])
				font_constant_set_procedures.forth
			end	
		end
		
	set_attributes_using_color_constants
			-- Set all attributes relying on color constants to the current
			-- value of the associated constant.
		local
			c: EV_COLOR
		do
			from
				color_constant_set_procedures.start
			until
				color_constant_set_procedures.off
			loop
				color_constant_retrieval_functions.i_th (color_constant_set_procedures.index).call (Void)
				c := color_constant_retrieval_functions.i_th (color_constant_set_procedures.index).last_result
				color_constant_set_procedures.item.call ([c])
				color_constant_set_procedures.forth
			end
		end
		
	set_all_attributes_using_constants
			-- Set all attributes relying on constants to the current
			-- calue of the associated constant.
		do
			set_attributes_using_string_constants
			set_attributes_using_integer_constants
			set_attributes_using_pixmap_constants
			set_attributes_using_font_constants
			set_attributes_using_color_constants
		end
					
	string_constant_set_procedures: ARRAYED_LIST [PROCEDURE [ANY, TUPLE [STRING_GENERAL]]]
	string_constant_retrieval_functions: ARRAYED_LIST [FUNCTION [ANY, TUPLE [], STRING_GENERAL]]
	integer_constant_set_procedures: ARRAYED_LIST [PROCEDURE [ANY, TUPLE [INTEGER]]]
	integer_constant_retrieval_functions: ARRAYED_LIST [FUNCTION [ANY, TUPLE [], INTEGER]]
	pixmap_constant_set_procedures: ARRAYED_LIST [PROCEDURE [ANY, TUPLE [EV_PIXMAP]]]
	pixmap_constant_retrieval_functions: ARRAYED_LIST [FUNCTION [ANY, TUPLE [], EV_PIXMAP]]
	integer_interval_constant_retrieval_functions: ARRAYED_LIST [FUNCTION [ANY, TUPLE [], INTEGER]]
	integer_interval_constant_set_procedures: ARRAYED_LIST [PROCEDURE [ANY, TUPLE [INTEGER_INTERVAL]]]
	font_constant_set_procedures: ARRAYED_LIST [PROCEDURE [ANY, TUPLE [EV_FONT]]]
	font_constant_retrieval_functions: ARRAYED_LIST [FUNCTION [ANY, TUPLE [], EV_FONT]]
	color_constant_set_procedures: ARRAYED_LIST [PROCEDURE [ANY, TUPLE [EV_COLOR]]]
	color_constant_retrieval_functions: ARRAYED_LIST [FUNCTION [ANY, TUPLE [], EV_COLOR]]
	
	integer_from_integer (an_integer: INTEGER): INTEGER
			-- Return `an_integer', used for creation of
			-- an agent that returns a fixed integer value.
		do
			Result := an_integer
		end

end
