indexing
	description: "Objects that represent an EV_DIALOG.%
		%The original version of this class was generated by EiffelBuild."
	author: ""
	date: "$Date$"
	revision: "$Revision$"

deferred class
	DOCUMENT_WIDGET_IMP

inherit
	EV_VERTICAL_BOX
		rename
			border_width as border_width_box,
			padding_width as padding_width_box
		redefine
			initialize, is_in_default_state
		end
			
	CONSTANTS
		undefine
			is_equal, default_create, copy
		end

-- This class is the implementation of an EV_DIALOG generated by EiffelBuild.
-- You should not modify this code by hand, as it will be re-generated every time
-- modifications are made to the project.

feature {NONE}-- Initialization

	initialize is
			-- Initialize `Current'.
		local
			internal_pixmap: EV_PIXMAP
		do
			Precursor {EV_VERTICAL_BOX}
			initialize_constants
			
				-- Create all widgets.
			create l_ev_vertical_box_1
			create document_widget
			create main_box
			create view_box
			create button_box
			create edit_button
			create xml_button
			create html_button
			create l_ev_cell_1
			create internal_pixmap
			
				-- Build_widget_structure.
			extend (l_ev_vertical_box_1)
			l_ev_vertical_box_1.extend (document_widget)
			document_widget.extend (main_box)
			main_box.extend (view_box)
			main_box.extend (button_box)
			button_box.extend (edit_button)
			button_box.extend (xml_button)
			button_box.extend (html_button)
			button_box.extend (l_ev_cell_1)
			
			main_box.set_padding_width (5)
			main_box.set_border_width (2)
			main_box.disable_item_expand (button_box)
			view_box.set_padding_width (5)
			view_box.set_border_width (2)
			button_box.set_padding_width (5)
			button_box.set_border_width (2)
			button_box.disable_item_expand (edit_button)
			button_box.disable_item_expand (xml_button)
			button_box.disable_item_expand (html_button)
			edit_button.set_text ("Edit")
			edit_button.align_text_left
			internal_pixmap.set_with_named_file ("D:\My Documents\Documentation Project\systems\DocBuilder\resources\icons\icon_format_text_color.ico")
			edit_button.set_pixmap (internal_pixmap)
			xml_button.set_text ("XML")
			xml_button.align_text_left
			internal_pixmap.set_with_named_file ("D:\My Documents\Documentation Project\systems\DocBuilder\resources\icons\icon_cut_color.ico")
			xml_button.set_pixmap (internal_pixmap)
			html_button.set_text ("HTML")
			html_button.align_text_left
			internal_pixmap.set_with_named_file ("D:\My Documents\Documentation Project\systems\DocBuilder\resources\icons\icon_copy_color.ico")
			html_button.set_pixmap (internal_pixmap)
			
				--Connect events.
				-- Close the application when an interface close
				-- request is recieved on `Current'. i.e. the cross is clicked.

				-- Call `user_initialization'.
			user_initialization
		end

feature -- Access

	l_ev_vertical_box_1, main_box, view_box: EV_VERTICAL_BOX
	document_widget: EV_FRAME
	button_box: EV_HORIZONTAL_BOX
	edit_button, xml_button, html_button: EV_BUTTON
	l_ev_cell_1: EV_CELL

feature {NONE} -- Implementation

	is_in_default_state: BOOLEAN is
			-- Is `Current' in its default state?
		do
			-- Re-implement if you wish to enable checking
			-- for `Current'.
			Result := True
		end
	
	user_initialization is
			-- Feature for custom initialization, called at end of `initialize'.
		deferred
		end
	
end -- class DOCUMENT_WIDGET_IMP
