note
	description: "[
					Generated by EiffelRibbon tool
					Don't edit this file, since it will be replaced by EiffelRibbon tool
					generated files everytime
																							]"
	date: "$Date$"
	revision: "$Revision$"

deferred class
	$INDEX

inherit
	EV_RIBBON_TAB_GROUP

feature {NONE} -- Initialization

	create_interface_objects
			-- Create objects
		do
$TAB_CREATION
			create tabs.make (1)
$TAB_REGISTRY
		end

feature -- Query
$TAB_DECLARATION

end
