// Generated .IDL file (by the OLE/COM Object Viewer)
// 
// typelib filename: <could not determine filename>

[
  uuid(A15DF32A-0F73-3C93-89FD-A8783996C0DB),
  version(1.0)
]
library AssemblyManagerInterface
{
    // TLib :     // TLib : Common Language Runtime Library : {BED7F4EA-1A96-11D2-8F08-00A0C9A6186D}
    // importlib("mscorlib.tlb");
    // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
    importlib("stdole2.tlb");

    // Forward declare all types defined in this typelib
    interface IAssemblyManagerInterface;

    [
      odl,
      uuid(232A7E85-2357-386E-A37D-1D957E41AFFD),
      version(1.0),
      oleautomation  

    ]
    interface IAssemblyManagerInterface : IUnknown {
        HRESULT _stdcall ImportedAssemblies([out, retval] SAFEARRAY(BSTR)* pRetVal);
        HRESULT _stdcall LastImportationSuccessful([out, retval] VARIANT_BOOL* pRetVal);
        HRESULT _stdcall AssemblyLocation(
                        [in] BSTR Name, 
                        [in] BSTR Version, 
                        [in] BSTR Culture, 
                        [in] BSTR PublicKey, 
                        [out, retval] BSTR* pRetVal);
        HRESULT _stdcall AssemblyDependencies(
                        [in] BSTR Name, 
                        [in] BSTR Version, 
                        [in] BSTR Culture, 
                        [in] BSTR PublicKey, 
                        [out, retval] SAFEARRAY(BSTR)* pRetVal);
        HRESULT _stdcall CleanAssemblies();
    };

    [
      uuid(05624193-ECF7-3E13-9F0B-3AC39344E8CB),
      version(1.0)
    ]
    coclass AssemblyManagerInterface {
        [default] interface IAssemblyManagerInterface;
    };
};
