// Generated .IDL file (by the OLE/COM Object Viewer)
// 
// typelib filename: <could not determine filename>

[
  uuid(FD07FADA-05CB-305B-8CE8-CE081D6A98A5),
  version(5.0)
]
library AssemblyManagerInterface
{
    // TLib :     // TLib : Common Language Runtime Library : {BED7F4EA-1A96-11D2-8F08-00A0C9A6186D}
    // importlib("mscorlib.tlb");
    // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
    importlib("stdole2.tlb");

    // Forward declare all types defined in this typelib
    interface IAssemblyManagerInterface;

    [
      odl,
      uuid(2CAE334B-54E8-34BF-86AA-78C3E39B804F),
      version(1.0),
      oleautomation   

    ]
    interface IAssemblyManagerInterface : IUnknown {
        HRESULT _stdcall ImportedAssemblies([out, retval] SAFEARRAY(BSTR)* pRetVal);
        HRESULT _stdcall LastImportationSuccessful([out, retval] VARIANT_BOOL* pRetVal);
        HRESULT _stdcall AssemblyLocation(
                        [in] BSTR Name, 
                        [in] BSTR Version, 
                        [in] BSTR Culture, 
                        [in] BSTR PublicKey, 
                        [out, retval] BSTR* pRetVal);
        HRESULT _stdcall LocalAssemblyDependencies(
                        [in] BSTR Filename, 
                        [out, retval] SAFEARRAY(BSTR)* pRetVal);
        HRESULT _stdcall AssemblyDependencies(
                        [in] BSTR Name, 
                        [in] BSTR Version, 
                        [in] BSTR Culture, 
                        [in] BSTR PublicKey, 
                        [out, retval] SAFEARRAY(BSTR)* pRetVal);
        HRESULT _stdcall IsSigned(
                        [in] BSTR Filename, 
                        [out, retval] VARIANT_BOOL* pRetVal);
        HRESULT _stdcall CleanAssemblies();
    };

    [
      uuid(4116A1B8-4260-3D6F-BE70-19982B1BB9D7),
      version(1.0)
    ]
    coclass AssemblyManagerInterface {
        [default] interface IAssemblyManagerInterface;
    };
};
