// Generated .IDL file (by the OLE/COM Object Viewer)
// 
// typelib filename: <could not determine filename>

[
  uuid(FCD94257-1E25-39A6-89C3-E0C5D02870B1),
  version(0.1)
]
library AssemblyManagerInterface
{
    // TLib :     // TLib : Common Language Runtime Library : {BED7F4EA-1A96-11D2-8F08-00A0C9A6186D}
    // importlib("mscorlib.tlb");
    // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
    importlib("stdole2.tlb");

    // Forward declare all types defined in this typelib
    interface IAssemblyManagerInterface;

    [
      odl,
      uuid(4AA92D94-873F-381F-A476-3476DD816448),
      version(1.0),
      oleautomation 

    ]
    interface IAssemblyManagerInterface : IUnknown {
        HRESULT _stdcall ImportedAssemblies([out, retval] SAFEARRAY(BSTR)* pRetVal);
        HRESULT _stdcall AssemblyLocation(
                        [in] BSTR Name, 
                        [in] BSTR Version, 
                        [in] BSTR Culture, 
                        [in] BSTR PublicKey, 
                        [out, retval] BSTR* pRetVal);
        HRESULT _stdcall AssemblyDependencies(
                        [in] BSTR Name, 
                        [in] BSTR Version, 
                        [in] BSTR Culture, 
                        [in] BSTR PublicKey, 
                        [out, retval] SAFEARRAY(BSTR)* pRetVal);
    };

    [
      uuid(AFA79485-2EE0-3DF5-90C4-DEB77902F511),
      version(1.0)
    ]
    coclass AssemblyManagerInterface {
        [default] interface IAssemblyManagerInterface;
    };
};
