// Generated .IDL file (by the OLE/COM Object Viewer)
// 
// typelib filename: EiffelCompiler.tlb

[
  uuid(C947355E-AE58-3607-957C-7565E8CC09A1),
  version(5.1)
]
library EiffelCompiler
{
    // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
    importlib("stdole2.tlb");

    // Forward declare all types defined in this typelib
    interface COMPILER_PROXY_I;

    [
      odl,
      uuid(75DA17F3-0D39-354C-A339-564A657C805F),
      version(1.0),
      oleautomation
    ]
    interface COMPILER_PROXY_I : IUnknown {
        HRESULT _stdcall SetConsoleApplication();
        HRESULT _stdcall SetWindowApplication();
        HRESULT _stdcall SetDll();
        HRESULT _stdcall StartAssemblyGeneration(
                        [in] BSTR Name, 
                        [in] BSTR FName, 
                        [in] BSTR Location);
        HRESULT _stdcall AddAssemblyReference([in] BSTR Name);
        HRESULT _stdcall StartModuleGeneration(
                        [in] BSTR Name, 
                        [in] VARIANT_BOOL Debug);
        HRESULT _stdcall EndAssemblyGeneration();
        HRESULT _stdcall StartClassMappings([in] long ClassCount);
        HRESULT _stdcall generate_class_mappings(
                        [in] BSTR dotnet_name, 
                        [in] BSTR eiffel_name, 
                        [in] long TypeID, 
                        [in] long InterfaceID, 
                        [in] BSTR SourceFileName, 
                        [in] BSTR ElementTypeName);
        HRESULT _stdcall generate_type_class_mapping([in] long type_id);
        HRESULT _stdcall generate_class_type_class_mapping([in] long type_id);
        HRESULT _stdcall generate_generic_type_class_mapping([in] long type_id);
        HRESULT _stdcall generate_formal_type_class_mapping([in] long type_id);
        HRESULT _stdcall generate_anchored_type_class_mapping([in] long type_id);
        HRESULT _stdcall generate_basic_type_class_mapping([in] long type_id);
        HRESULT _stdcall GenerateClassHeader(
                        [in] VARIANT_BOOL IsInterface, 
                        [in] VARIANT_BOOL IsDeferred, 
                        [in] VARIANT_BOOL IsFrozen, 
                        [in] VARIANT_BOOL IsExpanded, 
                        [in] VARIANT_BOOL IsExternal, 
                        [in] long TypeID);
        HRESULT _stdcall EndClass();
        HRESULT _stdcall AddToParentsList([in] long TypeID);
        HRESULT _stdcall AddInterface([in] long TypeID);
        HRESULT _stdcall AddEiffelInterface([in] long TypeID);
        HRESULT _stdcall EndParentsList();
        HRESULT _stdcall StartFeaturesList([in] long TypeID);
        HRESULT _stdcall MarkInvariant([in] long FeatureID);
        HRESULT _stdcall MarkCreationRoutines([in] SAFEARRAY(long) FeatureID);
        HRESULT _stdcall StartFeatureDescription([in] long arg_count);
        HRESULT _stdcall GenerateInterfaceFeatureIdentification(
                        [in] BSTR Name, 
                        [in] long FeatureID, 
                        [in] VARIANT_BOOL IsAttribute);
        HRESULT _stdcall GenerateFeatureIdentification(
                        [in] BSTR Name, 
                        [in] long FeatureID, 
                        [in] VARIANT_BOOL IsRedefined, 
                        [in] VARIANT_BOOL IsDeferred, 
                        [in] VARIANT_BOOL IsFrozen, 
                        [in] VARIANT_BOOL IsAttribute, 
                        [in] VARIANT_BOOL Is_C_External, 
                        [in] VARIANT_BOOL IsStatic);
        HRESULT _stdcall GenerateExternalIdentification(
                        [in] BSTR Name, 
                        [in] BSTR ComName, 
                        [in] long ExternalKind, 
                        [in] long FeatureID, 
                        [in] long RoutineID, 
                        [in] VARIANT_BOOL InCurrentClass, 
                        [in] long WrittenTypeID, 
                        [in] SAFEARRAY(BSTR) Parameters, 
                        [in] BSTR ReturnType);
        HRESULT _stdcall GenerateFeatureReturnType([in] long TypeID);
        HRESULT _stdcall GenerateFeatureArgument(
                        [in] BSTR Name, 
                        [in] long TypeID);
        HRESULT _stdcall CreateFeatureDescription();
        HRESULT _stdcall DefineEntryPoint(
                        [in] long CreationTypeID, 
                        [in] long TypeID, 
                        [in] long FeatureID);
        HRESULT _stdcall LastError([out, retval] BSTR* pRetVal);
        HRESULT _stdcall AddCA(
                        [in] long TargetTypeID, 
                        [in] long AttributeTypeID, 
                        [in] long ArgCount);
        HRESULT _stdcall GenerateClassCA();
        HRESULT _stdcall GenerateFeatureCA([in] long FeatureID);
        HRESULT _stdcall AddCATypedArg(
                        [in] long Value, 
                        [in] long TypeID);
        HRESULT _stdcall AddCAIntegerArg([in] long Value);
        HRESULT _stdcall AddCAStringArg([in] BSTR Value);
        HRESULT _stdcall AddCARealArg([in] double Value);
        HRESULT _stdcall AddCADoubleArg([in] double Value);
        HRESULT _stdcall AddCACharacterArg([in] unsigned short Value);
        HRESULT _stdcall AddCABooleanArg([in] VARIANT_BOOL Value);
        HRESULT _stdcall AddCAArrayIntegerArg([in] SAFEARRAY(long) Value);
        HRESULT _stdcall AddCAArrayStringArg([in] SAFEARRAY(BSTR) Value);
        HRESULT _stdcall AddCAArrayRealArg([in] SAFEARRAY(double) Value);
        HRESULT _stdcall AddCAArrayDoubleArg([in] SAFEARRAY(double) Value);
        HRESULT _stdcall AddCAArrayCharacterArg([in] SAFEARRAY(unsigned short) Value);
        HRESULT _stdcall AddCAArrayBooleanArg([in] SAFEARRAY(VARIANT_BOOL) Value);
        HRESULT _stdcall StartIlGeneration([in] long TypeID);
        HRESULT _stdcall generate_formal_feature([in] long feature_id);
        HRESULT _stdcall GenerateFeatureIL(
                        [in] long FeatureID, 
                        [in] long TypeID, 
                        [in] long CodeFeatureID);
        HRESULT _stdcall GenerateFeatureInternalClone([in] long FeatureID);
        HRESULT _stdcall GenerateImplementationFeatureIL([in] long FeatureID);
        HRESULT _stdcall GenerateMethodImpl(
                        [in] long FeatureID, 
                        [in] long ParentTypeID, 
                        [in] long ParentFeatureID);
        HRESULT _stdcall GenerateCreationFeatureIL([in] long FeatureID);
        HRESULT _stdcall GenerateExternalCall(
                        [in] BSTR ExternalTypeName, 
                        [in] BSTR Name, 
                        [in] long ExternalKind, 
                        [in] SAFEARRAY(BSTR) ParameterTypes, 
                        [in] BSTR ReturnType, 
                        [in] VARIANT_BOOL IsVirtual);
        HRESULT _stdcall PutResultInfo([in] long TypeID);
        HRESULT _stdcall PutLocalInfo(
                        [in] long TypeID, 
                        [in] BSTR Name);
        HRESULT _stdcall CreateLikeCurrentObject();
        HRESULT _stdcall CreateObject([in] long TypeID);
        HRESULT _stdcall CreateAttributeObject(
                        [in] long TypeID, 
                        [in] long FeatureID);
        HRESULT _stdcall DuplicateTop();
        HRESULT _stdcall Pop();
        HRESULT _stdcall GenerateMetamorphose([in] long TypeID);
        HRESULT _stdcall GenerateUnmetamorphose([in] long TypeID);
        HRESULT _stdcall GenerateCheckCast(
                        [in] long SourceTypeID, 
                        [in] long TargetTypeID);
        HRESULT _stdcall ConvertToNativeInt();
        HRESULT _stdcall ConvertToBoolean();
        HRESULT _stdcall ConvertToCharacter();
        HRESULT _stdcall ConvertToInteger8();
        HRESULT _stdcall ConvertToInteger16();
        HRESULT _stdcall ConvertToInteger32();
        HRESULT _stdcall ConvertToInteger64();
        HRESULT _stdcall ConvertToDouble();
        HRESULT _stdcall ConvertToReal();
        HRESULT _stdcall GenerateCurrent();
        HRESULT _stdcall GenerateResult();
        HRESULT _stdcall GenerateAttribute(
                        [in] long TypeID, 
                        [in] long FeatureID);
        HRESULT _stdcall GenerateFeatureAccess(
                        [in] long TypeID, 
                        [in] long FeatureID, 
                        [in] VARIANT_BOOL IsVirtual);
        HRESULT _stdcall GeneratePrecursorFeatureAccess(
                        [in] long TypeID, 
                        [in] long FeatureID);
        HRESULT _stdcall PutMethodToken(
                        [in] long TypeID, 
                        [in] long FeatureID);
        HRESULT _stdcall put_type_token([in] long type_id);
        HRESULT _stdcall GenerateArgument([in] long n);
        HRESULT _stdcall GenerateLocal([in] long n);
        HRESULT _stdcall GenerateInAssertionTest([in] long EndOfAssertLabel);
        HRESULT _stdcall GenerateSetAssertionStatus();
        HRESULT _stdcall GenerateRestoreAssertionStatus();
        HRESULT _stdcall GenerateAssertionCheck(
                        [in] long AssertType, 
                        [in] BSTR Tag);
        HRESULT _stdcall GeneratePreconditionCheck(
                        [in] BSTR Tag, 
                        [in] long LabelID);
        HRESULT _stdcall GeneratePreconditionViolation();
        HRESULT _stdcall GenerateInvariantChecking([in] long TypeID);
        HRESULT _stdcall GenerateStartExceptionBlock();
        HRESULT _stdcall GenerateStartRescue();
        HRESULT _stdcall GenerateEndExceptionBlock();
        HRESULT _stdcall GenerateIsInstanceOf([in] long TypeID);
        HRESULT _stdcall GenerateAttributeAssignment(
                        [in] long TypeID, 
                        [in] long FeatureID);
        HRESULT _stdcall GenerateLocalAssignment([in] long n);
        HRESULT _stdcall GenerateResultAssignment();
        HRESULT _stdcall GenerateLocalAddress([in] long n);
        HRESULT _stdcall GenerateRoutineAddress(
                        [in] long TypeID, 
                        [in] long FeatureID);
        HRESULT _stdcall GenerateResultAddress();
        HRESULT _stdcall GenerateCurrentAddress();
        HRESULT _stdcall GenerateAttributeAddress(
                        [in] long TypeID, 
                        [in] long FeatureID);
        HRESULT _stdcall GenerateArgumentAddress([in] long n);
        HRESULT _stdcall GenerateLoadFromAddress([in] long type_id);
        HRESULT _stdcall GenerateArrayAccess([in] long Kind);
        HRESULT _stdcall GenerateArrayWrite([in] long Kind);
        HRESULT _stdcall GenerateArrayCreation([in] long TypeID);
        HRESULT _stdcall GenerateReturn();
        HRESULT _stdcall GenerateReturnValue();
        HRESULT _stdcall GenerateOnceDoneInfo([in] BSTR Name);
        HRESULT _stdcall GenerateOnceResultInfo(
                        [in] BSTR Name, 
                        [in] long TypeID);
        HRESULT _stdcall GenerateOnceTest();
        HRESULT _stdcall GenerateOnceResult();
        HRESULT _stdcall GenerateOnceStoreResult();
        HRESULT _stdcall GenerateArrayLower();
        HRESULT _stdcall GenerateArrayUpper();
        HRESULT _stdcall GenerateArrayCount();
        HRESULT _stdcall PutVoid();
        HRESULT _stdcall PutManifestString([in] BSTR s);
        HRESULT _stdcall PutInteger8Constant([in] long i);
        HRESULT _stdcall PutInteger16Constant([in] long i);
        HRESULT _stdcall PutInteger32Constant([in] long i);
        HRESULT _stdcall PutInteger64Constant([in] int64 i);
        HRESULT _stdcall PutDoubleConstant([in] double d);
        HRESULT _stdcall PutRealConstant([in] double d);
        HRESULT _stdcall PutCharacterConstant([in] unsigned short c);
        HRESULT _stdcall PutBooleanConstant([in] VARIANT_BOOL b);
        HRESULT _stdcall BranchOnTrue([in] long label);
        HRESULT _stdcall BranchOnFalse([in] long label);
        HRESULT _stdcall BranchTo([in] long label);
        HRESULT _stdcall MarkLabel([in] long label);
        HRESULT _stdcall GenerateLt();
        HRESULT _stdcall GenerateLe();
        HRESULT _stdcall GenerateGt();
        HRESULT _stdcall GenerateGe();
        HRESULT _stdcall GenerateStar();
        HRESULT _stdcall GeneratePower();
        HRESULT _stdcall GenerateMax([in] long TypeID);
        HRESULT _stdcall GenerateMin([in] long TypeID);
        HRESULT _stdcall GenerateAbs([in] long TypeID);
        HRESULT _stdcall GenerateToString();
        HRESULT _stdcall GeneratePlus();
        HRESULT _stdcall GenerateMod();
        HRESULT _stdcall GenerateMinus();
        HRESULT _stdcall GenerateDiv();
        HRESULT _stdcall GenerateXor();
        HRESULT _stdcall GenerateOr();
        HRESULT _stdcall GenerateAnd();
        HRESULT _stdcall GenerateImplies();
        HRESULT _stdcall GenerateEq();
        HRESULT _stdcall GenerateShl();
        HRESULT _stdcall GenerateShr();
        HRESULT _stdcall GenerateNe();
        HRESULT _stdcall GenerateUMinus();
        HRESULT _stdcall GenerateNot();
        HRESULT _stdcall GenerateBitwiseNot();
        HRESULT _stdcall PutLineInfo([in] long n);
        HRESULT _stdcall CreateLabel([out, retval] long* pRetVal);
        HRESULT _stdcall SetForInterfaces();
        HRESULT _stdcall SetForImplementations();
    };

    [
      uuid(284806C7-1637-361D-9C9E-2E4B4C00378A),
      version(1.0)
    ]
    coclass COMPILER_PROXY {
        [default] interface COMPILER_PROXY_I;
    };
};
