.TH CECIL 1  "November 10, 1999" "ISE" "CECIL Programmer's Manual"
.SH NAME
eif_string	\- build an Eiffel string from a C string. 
.SH SYNOPSYS
.nf
\fB#include "eif_plug.h"\fP
.sp
.BI "EIF_REFERENCE eif_string (char * " string ");"
.fi
.SH DESCRIPTION
The \fBeif_string()\fP macro returns the corresponding Eiffel string corresponding
to the C string \fIstring\fP.
.PP
The return value does not reference \fIstring\fP.  
.SH NOTES
This function return an Eiffel reference, which must be protected with \fBeif_protect()\fP.
.SH CONFORMANCE
ISE Eiffel 4.5 and later.
.SH COMPATIBILITY
\fBeif_string()\fP is equivalent to \fBRTMS()\fP, which is deprecated.
.SH SEE ALSO
.BR eif_protect "(1) , "eif_create "(1)." 


