.TH CECIL 1  "November 10, 1999" "ISE" "CECIL Programmer's Manual"
.SH NAME
eif_enable_visible_exception, eif_disable_visible_exception	\- enable and disable visible exception .
.SH SYNOPSYS
.nf
\fB#include "eif_cecil.h"\fB
.BI "void eif_enable_visible_exception ();"
.sp
.BI "void eif_disable_visible_exception ();"
.fi
.SH DESCRIPTION
The \fBeif_enable_visble_exception()\fP routine enables the visible exception, while 
\fBeif_disable_visible_exception()\fP disables it. These routines can be used for debugging
purpose. A visible exception is raised when the user tries to access to an Eiffel attribute
or a Eiffel routine address which is not visible. 
.PP
The visible exception is disabled by default.
.SH CONFORMANCE
ISE Eiffel 4.5 and later.
.SH COMPATIBILITY
On ISE Eiffel 4.3 and 4.4, the visible exception is enabled by default. 
.SH SEE ALSO
.BR eif_attribute "(1) , "eif_procedure "(1), "eif_reference_function "(1)." 


