FROM daald/ubuntu32:trusty

LABEL maintainer="Jocelyn Fiat <jfiat@eiffel.com>"

RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
        ca-certificates curl \
        bzip2 \
        gcc make dist \
        libxtst-dev \
        libgtk2.0-dev \
        libssl-dev \
		pax \
		dos2unix \
		subversion \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Define Eiffel environment variables
ENV ISE_PLATFORM=linux-x86
ENV SVN_EIFFELSTUDIO_REPO=https://svn.eiffel.com/eiffelstudio
ENV SVN_ISE_REPO=svn://svn.ise/ise_svn
ENV EIFFEL_SETUP_CHANNEL=nightly
#ENV SVN_EIFFELSTUDIO_REPO_REVISION=HEAD

RUN export uid=1000 gid=1000 && \
    mkdir -p /home/eiffel && \
    echo "eiffel:x:${uid}:${gid}:eiffel,,,:/home/eiffel:/bin/bash" >> /etc/passwd && \
    echo "eiffel:x:${uid}:" >> /etc/group && \
    chown ${uid}:${gid} -R /home/eiffel


USER eiffel
ENV HOME /home/eiffel
COPY --chown=eiffel:eiffel ./src/build_delivery.sh /home/eiffel/build_delivery.sh
RUN mkdir -p /home/eiffel/deliv/output \
	&& dos2unix /home/eiffel/build_delivery.sh

VOLUME /home/eiffel/deliv/output

WORKDIR $HOME
#ENTRYPOINT ["/bin/bash", "/home/eiffel/build_delivery.sh", "/home/eiffel/deliv"]
CMD /bin/bash /home/eiffel/build_delivery.sh /home/eiffel/deliv

