note
	description: "Summary description for {ER_TOOL_BAR_BUTTON_IMP}."
	date: "$Date$"
	revision: "$Revision$"

deferred class
	ER_TOOL_BAR_BUTTON_IMP_$INDEX

inherit
	ER_COMMAND_HANDLER_OBSERVER
	
	ER_TOOL_BAR_BUTTON

feature -- Query

	select_actions: EV_NOTIFY_ACTION_SEQUENCE
			--

	text: STRING = "Button 1"
			-- This is generated by EiffelRibbon tool

feature {NONE} -- Action handling


end
