note
	description: "[
					Generated by EiffelRibbon tool
																							]"
	date: "$Date$"
	revision: "$Revision$"

class
	$INDEX_1

inherit
	$INDEX_2

create
	{EV_RIBBON_TAB} make_with_command_list
	
end
