indexing
	description: "Generated by h2e from the file %
		%c:\eiffel4\examples\wel\stddlgs\app.rc."

class
	APPLICATION_IDS

feature -- Access

	Id_ico_application: INTEGER is 1
	Id_main_menu: INTEGER is 1
	Cmd_choose_file: INTEGER is 101
	Cmd_choose_font: INTEGER is 102
	Cmd_choose_color: INTEGER is 103
	Cmd_print_dialog: INTEGER is 104
	Cmd_exit: INTEGER is 1000

end -- class APPLICATION_IDS

--|----------------------------------------------------------------
--| Windows Eiffel Library: library of reusable components for ISE Eiffel.
--| Copyright (C) 1986-2001 Interactive Software Engineering Inc.
--| All rights reserved. Duplication and distribution prohibited.
--| May be used only with ISE Eiffel, under terms of user license. 
--| Contact ISE for any other use.
--|
--| Interactive Software Engineering Inc.
--| ISE Building
--| 360 Storke Road, Goleta, CA 93117 USA
--| Telephone 805-685-1006, Fax 805-685-6869
--| Electronic mail <info@eiffel.com>
--| Customer support: http://support.eiffel.com>
--| For latest info see award-winning pages: http://www.eiffel.com
--|----------------------------------------------------------------

