indexing

	description: "Parser token codes"
	generator: "geyacc version 1.5"

class LACE_TOKENS

feature -- Token codes

	LAC_ADAPT: INTEGER is 258
	LAC_ALL: INTEGER is 259
	LAC_AS: INTEGER is 260
	LAC_ASSERTION: INTEGER is 261
	LAC_CHECK: INTEGER is 262
	LAC_CLUSTER: INTEGER is 263
	LAC_COLON: INTEGER is 264
	LAC_COMMA: INTEGER is 265
	LAC_CREATION: INTEGER is 266
	LAC_DEBUG: INTEGER is 267
	LAC_DEFAULT: INTEGER is 268
	LAC_DISABLED_DEBUG: INTEGER is 269
	LAC_END: INTEGER is 270
	LAC_ENSURE: INTEGER is 271
	LAC_EXCLUDE: INTEGER is 272
	LAC_DEPEND: INTEGER is 273
	LAC_EXPORT: INTEGER is 274
	LAC_EXTERNAL: INTEGER is 275
	LAC_GENERATE: INTEGER is 276
	LAC_IDENTIFIER: INTEGER is 277
	LAC_IGNORE: INTEGER is 278
	LAC_INCLUDE: INTEGER is 279
	LAC_INVARIANT: INTEGER is 280
	LAC_LEFT_PARAM: INTEGER is 281
	LAC_LOOP: INTEGER is 282
	LAC_NO: INTEGER is 283
	LAC_OPTIMIZE: INTEGER is 284
	LAC_OPTION: INTEGER is 285
	LAC_PRECOMPILED: INTEGER is 286
	LAC_RENAME: INTEGER is 287
	LAC_REQUIRE: INTEGER is 288
	LAC_RIGHT_PARAM: INTEGER is 289
	LAC_ROOT: INTEGER is 290
	LAC_SEMICOLON: INTEGER is 291
	LAC_STRING: INTEGER is 292
	LAC_SYSTEM: INTEGER is 293
	LAC_TRACE: INTEGER is 294
	LAC_USE: INTEGER is 295
	LAC_VISIBLE: INTEGER is 296
	LAC_YES: INTEGER is 297
	LAC_LIBRARY: INTEGER is 298

end -- class LACE_TOKENS
