indexing
	description: "Objects that represent an EV_TITLED_WINDOW.%
		%The original version of this class was generated by EiffelBuild."
	legal: "See notice at end of class."
	status: "See notice at end of class."
	date: "$Date$"
	revision: "$Revision$"

deferred class
	TESTER_MAIN_WINDOW_IMP

inherit
	EV_TITLED_WINDOW
		redefine
			initialize, is_in_default_state
		end
			
	TESTER_CONSTANTS
		undefine
			is_equal, default_create, copy
		end

-- This class is the implementation of an EV_TITLED_WINDOW generated by EiffelBuild.
-- You should not modify this code by hand, as it will be re-generated every time
-- modifications are made to the project.

feature {NONE}-- Initialization

	initialize is
			-- Initialize `Current'.
		local 
			l_ev_horizontal_separator_1, l_ev_horizontal_separator_2, l_ev_horizontal_separator_3, 
			l_ev_horizontal_separator_4: EV_HORIZONTAL_SEPARATOR
			internal_font: EV_FONT
		do
			Precursor {EV_TITLED_WINDOW}
			initialize_constants
			
				-- Create all widgets.
			create main_split
			create left_box
			create codedom_provider_frame
			create code_provider_box
			create provider_label
			create provider_box
			create provider_combo_box
			create provider_browse_button
			create l_ev_horizontal_separator_1
			create file_extension_box
			create file_extension_title_label
			create file_extension_label
			create case_sensitive_box
			create case_sensitive_title_label
			create case_sensitive_check_button
			create codedom_trees_frame
			create codedom_trees_box
			create tree_bottom_split_area
			create codedom_tree
			create codedom_node_info_text
			create codedom_tree_buttons_box
			create left_buttons_padding_cell
			create add_button
			create remove_button
			create right_buttons_padding_cell
			create tests_notebook
			create code_generator_box
			create generation_tests_frame
			create generation_tests_box
			create blank_lines_box
			create blank_lines_label
			create blank_lines_check_button
			create else_on_closing_box
			create else_on_closing_label
			create else_at_closing_check_button
			create indent_string_box
			create indent_string_label
			create indent_string_text_field
			create generation_filename_box
			create generation_path_label
			create generation_path_box
			create generation_path_text_field
			create browse_button
			create generated_file_name
			create generated_filename_text_field
			create generate_box
			create generate_label
			create generate_button
			create identifier_tests_frame
			create identifier_tests_box
			create identifier_box
			create identifier_label
			create identifier_text_field
			create escaped_identifier_box
			create escaped_identifier_label
			create escaped_identifier_text_field
			create valid_identifier_box
			create valid_identifier_label
			create valid_identifier_text_field
			create is_valid_identifier_box
			create is_valid_identifier_label
			create is_valid_identifier_text_field
			create type_output_test_frame
			create type_output_test_box
			create type_box
			create type_label
			create type_text_field
			create output_type_box
			create output_type_label
			create output_type_text_field
			create properties_frame
			create properties_box
			create properties_title_box
			create supports_label
			create non_supports_label
			create supports_box
			create supports_list
			create non_supports_list
			create compiler_box
			create compiler_tests
			create compiler_tests_box
			create compile_from_dom_box
			create compile_from_dom_label
			create compile_from_dom_button
			create l_ev_horizontal_separator_2
			create compile_from_file_box
			create compile_from_file_title_box
			create compile_from_file_label
			create compile_from_file_button
			create compile_from_file_file_box
			create source_filename_text_field
			create browse_source_button
			create l_ev_horizontal_separator_3
			create compile_from_source_box
			create compile_from_source_title_box
			create compile_from_source_label
			create compile_from_source_button
			create source_text
			create compiler_parameters_frame
			create compiler_parameters_box
			create generate_executable_box
			create generate_executable_label
			create generate_executable_check_button
			create generate_in_memory_box
			create generate_in_memory_label
			create generate_in_memory_check_button
			create include_debug_box
			create include_debug_label
			create include_debug_check_button
			create compiler_options_box
			create compiler_options_label
			create compiler_options_text_field
			create main_class_box
			create main_class_label
			create main_class_text_field
			create output_assembly_box
			create output_assembly_label
			create output_assembly_text_field
			create resource_box
			create resource_label
			create resource_text_field
			create resource_browse_button
			create l_ev_horizontal_separator_4
			create referenced_assemblies_box
			create referenced_assemblies_label_box
			create referenced_assemblies_label
			create referenced_assemblies_list_box
			create referenced_assemblies_list
			create new_reference_box
			create new_reference_text_field
			create new_reference_browse_button
			create referenced_assemblies_list_buttons
			create referenced_assemblies_add_button
			create referenced_assemblies_remove_button
			create referenced_assemblies_right_padding_cell
			create code_parser_box
			create code_parser_frame
			create code_parser_settings_box
			create file_to_parse_label
			create parse_file_box
			create parse_file_text_field
			create parse_file_browse_button
			create serialized_folder_label
			create serialized_file_box
			create serialized_folder_text_field
			create serialized_folder_browse_button
			create serialized_filename_label
			create serialized_filename_text_field
			create parse_button_box
			create parse_button
			create parse_button_padding_cell
			create code_parser_padding_cell
			create output_text
			
				-- Build_widget_structure.
			extend (main_split)
			main_split.extend (left_box)
			left_box.extend (codedom_provider_frame)
			codedom_provider_frame.extend (code_provider_box)
			code_provider_box.extend (provider_label)
			code_provider_box.extend (provider_box)
			provider_box.extend (provider_combo_box)
			provider_box.extend (provider_browse_button)
			code_provider_box.extend (l_ev_horizontal_separator_1)
			code_provider_box.extend (file_extension_box)
			file_extension_box.extend (file_extension_title_label)
			file_extension_box.extend (file_extension_label)
			code_provider_box.extend (case_sensitive_box)
			case_sensitive_box.extend (case_sensitive_title_label)
			case_sensitive_box.extend (case_sensitive_check_button)
			left_box.extend (codedom_trees_frame)
			codedom_trees_frame.extend (codedom_trees_box)
			codedom_trees_box.extend (tree_bottom_split_area)
			tree_bottom_split_area.extend (codedom_tree)
			tree_bottom_split_area.extend (codedom_node_info_text)
			codedom_trees_box.extend (codedom_tree_buttons_box)
			codedom_tree_buttons_box.extend (left_buttons_padding_cell)
			codedom_tree_buttons_box.extend (add_button)
			codedom_tree_buttons_box.extend (remove_button)
			codedom_tree_buttons_box.extend (right_buttons_padding_cell)
			main_split.extend (tests_notebook)
			tests_notebook.extend (code_generator_box)
			code_generator_box.extend (generation_tests_frame)
			generation_tests_frame.extend (generation_tests_box)
			generation_tests_box.extend (blank_lines_box)
			blank_lines_box.extend (blank_lines_label)
			blank_lines_box.extend (blank_lines_check_button)
			generation_tests_box.extend (else_on_closing_box)
			else_on_closing_box.extend (else_on_closing_label)
			else_on_closing_box.extend (else_at_closing_check_button)
			generation_tests_box.extend (indent_string_box)
			indent_string_box.extend (indent_string_label)
			indent_string_box.extend (indent_string_text_field)
			generation_tests_box.extend (generation_filename_box)
			generation_filename_box.extend (generation_path_label)
			generation_filename_box.extend (generation_path_box)
			generation_path_box.extend (generation_path_text_field)
			generation_path_box.extend (browse_button)
			generation_filename_box.extend (generated_file_name)
			generation_filename_box.extend (generated_filename_text_field)
			generation_tests_box.extend (generate_box)
			generate_box.extend (generate_label)
			generate_box.extend (generate_button)
			code_generator_box.extend (identifier_tests_frame)
			identifier_tests_frame.extend (identifier_tests_box)
			identifier_tests_box.extend (identifier_box)
			identifier_box.extend (identifier_label)
			identifier_box.extend (identifier_text_field)
			identifier_tests_box.extend (escaped_identifier_box)
			escaped_identifier_box.extend (escaped_identifier_label)
			escaped_identifier_box.extend (escaped_identifier_text_field)
			identifier_tests_box.extend (valid_identifier_box)
			valid_identifier_box.extend (valid_identifier_label)
			valid_identifier_box.extend (valid_identifier_text_field)
			identifier_tests_box.extend (is_valid_identifier_box)
			is_valid_identifier_box.extend (is_valid_identifier_label)
			is_valid_identifier_box.extend (is_valid_identifier_text_field)
			code_generator_box.extend (type_output_test_frame)
			type_output_test_frame.extend (type_output_test_box)
			type_output_test_box.extend (type_box)
			type_box.extend (type_label)
			type_box.extend (type_text_field)
			type_output_test_box.extend (output_type_box)
			output_type_box.extend (output_type_label)
			output_type_box.extend (output_type_text_field)
			code_generator_box.extend (properties_frame)
			properties_frame.extend (properties_box)
			properties_box.extend (properties_title_box)
			properties_title_box.extend (supports_label)
			properties_title_box.extend (non_supports_label)
			properties_box.extend (supports_box)
			supports_box.extend (supports_list)
			supports_box.extend (non_supports_list)
			tests_notebook.extend (compiler_box)
			compiler_box.extend (compiler_tests)
			compiler_tests.extend (compiler_tests_box)
			compiler_tests_box.extend (compile_from_dom_box)
			compile_from_dom_box.extend (compile_from_dom_label)
			compile_from_dom_box.extend (compile_from_dom_button)
			compiler_tests_box.extend (l_ev_horizontal_separator_2)
			compiler_tests_box.extend (compile_from_file_box)
			compile_from_file_box.extend (compile_from_file_title_box)
			compile_from_file_title_box.extend (compile_from_file_label)
			compile_from_file_title_box.extend (compile_from_file_button)
			compile_from_file_box.extend (compile_from_file_file_box)
			compile_from_file_file_box.extend (source_filename_text_field)
			compile_from_file_file_box.extend (browse_source_button)
			compiler_tests_box.extend (l_ev_horizontal_separator_3)
			compiler_tests_box.extend (compile_from_source_box)
			compile_from_source_box.extend (compile_from_source_title_box)
			compile_from_source_title_box.extend (compile_from_source_label)
			compile_from_source_title_box.extend (compile_from_source_button)
			compile_from_source_box.extend (source_text)
			compiler_box.extend (compiler_parameters_frame)
			compiler_parameters_frame.extend (compiler_parameters_box)
			compiler_parameters_box.extend (generate_executable_box)
			generate_executable_box.extend (generate_executable_label)
			generate_executable_box.extend (generate_executable_check_button)
			compiler_parameters_box.extend (generate_in_memory_box)
			generate_in_memory_box.extend (generate_in_memory_label)
			generate_in_memory_box.extend (generate_in_memory_check_button)
			compiler_parameters_box.extend (include_debug_box)
			include_debug_box.extend (include_debug_label)
			include_debug_box.extend (include_debug_check_button)
			compiler_parameters_box.extend (compiler_options_box)
			compiler_options_box.extend (compiler_options_label)
			compiler_options_box.extend (compiler_options_text_field)
			compiler_parameters_box.extend (main_class_box)
			main_class_box.extend (main_class_label)
			main_class_box.extend (main_class_text_field)
			compiler_parameters_box.extend (output_assembly_box)
			output_assembly_box.extend (output_assembly_label)
			output_assembly_box.extend (output_assembly_text_field)
			compiler_parameters_box.extend (resource_box)
			resource_box.extend (resource_label)
			resource_box.extend (resource_text_field)
			resource_box.extend (resource_browse_button)
			compiler_parameters_box.extend (l_ev_horizontal_separator_4)
			compiler_parameters_box.extend (referenced_assemblies_box)
			referenced_assemblies_box.extend (referenced_assemblies_label_box)
			referenced_assemblies_label_box.extend (referenced_assemblies_label)
			referenced_assemblies_box.extend (referenced_assemblies_list_box)
			referenced_assemblies_list_box.extend (referenced_assemblies_list)
			referenced_assemblies_list_box.extend (new_reference_box)
			new_reference_box.extend (new_reference_text_field)
			new_reference_box.extend (new_reference_browse_button)
			referenced_assemblies_list_box.extend (referenced_assemblies_list_buttons)
			referenced_assemblies_list_buttons.extend (referenced_assemblies_add_button)
			referenced_assemblies_list_buttons.extend (referenced_assemblies_remove_button)
			referenced_assemblies_list_buttons.extend (referenced_assemblies_right_padding_cell)
			tests_notebook.extend (code_parser_box)
			code_parser_box.extend (code_parser_frame)
			code_parser_frame.extend (code_parser_settings_box)
			code_parser_settings_box.extend (file_to_parse_label)
			code_parser_settings_box.extend (parse_file_box)
			parse_file_box.extend (parse_file_text_field)
			parse_file_box.extend (parse_file_browse_button)
			code_parser_settings_box.extend (serialized_folder_label)
			code_parser_settings_box.extend (serialized_file_box)
			serialized_file_box.extend (serialized_folder_text_field)
			serialized_file_box.extend (serialized_folder_browse_button)
			code_parser_settings_box.extend (serialized_filename_label)
			code_parser_settings_box.extend (serialized_filename_text_field)
			code_parser_box.extend (parse_button_box)
			parse_button_box.extend (parse_button)
			parse_button_box.extend (parse_button_padding_cell)
			code_parser_box.extend (code_parser_padding_cell)
			tests_notebook.extend (output_text)
			
			set_title ("Eiffel CodeDom Provider Tester")
			left_box.set_padding_width (5)
			left_box.set_border_width (5)
			left_box.disable_item_expand (codedom_provider_frame)
			create internal_font
			internal_font.set_family (3)
			internal_font.set_weight (8)
			internal_font.set_shape (10)
			internal_font.set_height (11)
			internal_font.preferred_families.extend ("Microsoft Sans Serif")
			codedom_provider_frame.set_font (internal_font)
			codedom_provider_frame.set_text ("CodeDom Provider")
			code_provider_box.set_padding_width (10)
			code_provider_box.set_border_width (7)
			code_provider_box.disable_item_expand (provider_label)
			code_provider_box.disable_item_expand (provider_box)
			code_provider_box.disable_item_expand (l_ev_horizontal_separator_1)
			code_provider_box.disable_item_expand (file_extension_box)
			provider_label.set_text ("Selected CodeDom provider:")
			provider_label.align_text_left
			provider_box.set_padding_width (5)
			provider_box.disable_item_expand (provider_browse_button)
			provider_browse_button.set_text ("...")
			provider_browse_button.set_minimum_width (40)
			file_extension_box.disable_item_expand (file_extension_title_label)
			file_extension_box.disable_item_expand (file_extension_label)
			file_extension_title_label.set_text ("File Extension:")
			file_extension_title_label.set_minimum_width (90)
			file_extension_title_label.align_text_left
			file_extension_label.align_text_left
			case_sensitive_box.set_padding_width (5)
			case_sensitive_box.disable_item_expand (case_sensitive_title_label)
			case_sensitive_box.disable_item_expand (case_sensitive_check_button)
			case_sensitive_title_label.set_text ("Case sensitive:")
			case_sensitive_title_label.set_minimum_width (90)
			case_sensitive_title_label.align_text_left
			case_sensitive_check_button.disable_sensitive
			create internal_font
			internal_font.set_family (3)
			internal_font.set_weight (8)
			internal_font.set_shape (10)
			internal_font.set_height (11)
			internal_font.preferred_families.extend ("Microsoft Sans Serif")
			codedom_trees_frame.set_font (internal_font)
			codedom_trees_frame.set_text ("CodeDom Trees")
			codedom_trees_box.set_padding_width (5)
			codedom_trees_box.set_border_width (5)
			codedom_trees_box.disable_item_expand (codedom_tree_buttons_box)
			create internal_font
			internal_font.set_family (4)
			internal_font.set_weight (7)
			internal_font.set_shape (10)
			internal_font.set_height (11)
			internal_font.preferred_families.extend ("Courier New")
			codedom_node_info_text.set_font (internal_font)
			codedom_node_info_text.disable_edit
			codedom_tree_buttons_box.set_padding_width (5)
			codedom_tree_buttons_box.disable_item_expand (add_button)
			codedom_tree_buttons_box.disable_item_expand (remove_button)
			add_button.set_text ("Add")
			add_button.set_minimum_width (100)
			remove_button.disable_sensitive
			remove_button.set_text ("Remove")
			remove_button.set_minimum_width (100)
			tests_notebook.set_item_text (code_generator_box, "Generator")
			tests_notebook.set_item_text (compiler_box, "Compiler")
			tests_notebook.set_item_text (code_parser_box, "Parser")
			tests_notebook.set_item_text (output_text, "Output")
			code_generator_box.set_padding_width (5)
			code_generator_box.set_border_width (5)
			code_generator_box.disable_item_expand (generation_tests_frame)
			code_generator_box.disable_item_expand (identifier_tests_frame)
			code_generator_box.disable_item_expand (type_output_test_frame)
			create internal_font
			internal_font.set_family (3)
			internal_font.set_weight (8)
			internal_font.set_shape (10)
			internal_font.set_height (11)
			internal_font.preferred_families.extend ("Microsoft Sans Serif")
			generation_tests_frame.set_font (internal_font)
			generation_tests_frame.set_text ("Generation Tests")
			generation_tests_box.set_padding_width (5)
			generation_tests_box.set_border_width (5)
			generation_tests_box.disable_item_expand (blank_lines_box)
			generation_tests_box.disable_item_expand (indent_string_box)
			blank_lines_box.set_padding_width (5)
			blank_lines_box.disable_item_expand (blank_lines_label)
			blank_lines_box.disable_item_expand (blank_lines_check_button)
			blank_lines_label.set_text ("Insert blank lines between members:")
			blank_lines_label.set_minimum_width (180)
			blank_lines_label.align_text_left
			else_on_closing_box.set_padding_width (5)
			else_on_closing_box.disable_item_expand (else_on_closing_label)
			else_on_closing_box.disable_item_expand (else_at_closing_check_button)
			else_on_closing_label.set_text ("Append else at closing of if blocks:")
			else_on_closing_label.set_minimum_width (180)
			else_on_closing_label.align_text_left
			indent_string_box.set_padding_width (5)
			indent_string_box.disable_item_expand (indent_string_label)
			indent_string_label.set_text ("Indent string:")
			indent_string_label.set_minimum_width (180)
			indent_string_label.align_text_left
			generation_filename_box.set_padding_width (5)
			generation_filename_box.disable_item_expand (generation_path_label)
			generation_filename_box.disable_item_expand (generation_path_box)
			generation_path_label.set_text ("Generated file folder:")
			generation_path_label.set_minimum_width (90)
			generation_path_label.align_text_left
			generation_path_box.set_padding_width (5)
			generation_path_box.disable_item_expand (browse_button)
			browse_button.set_text ("...")
			browse_button.set_minimum_width (40)
			generated_file_name.set_text ("Generated filename (without extension):")
			generated_file_name.align_text_left
			generate_box.set_padding_width (5)
			generate_box.disable_item_expand (generate_button)
			generate_label.set_foreground_color (create {EV_COLOR}.make_with_8_bit_rgb (0, 0, 128))
			generate_label.set_minimum_width (90)
			generate_label.align_text_left
			generate_button.disable_sensitive
			generate_button.set_text ("Generate")
			generate_button.set_minimum_width (100)
			create internal_font
			internal_font.set_family (3)
			internal_font.set_weight (8)
			internal_font.set_shape (10)
			internal_font.set_height (11)
			internal_font.preferred_families.extend ("Microsoft Sans Serif")
			identifier_tests_frame.set_font (internal_font)
			identifier_tests_frame.set_text ("Identifier Tests")
			identifier_tests_box.set_padding_width (5)
			identifier_tests_box.set_border_width (5)
			identifier_tests_box.disable_item_expand (identifier_box)
			identifier_tests_box.disable_item_expand (escaped_identifier_box)
			identifier_tests_box.disable_item_expand (valid_identifier_box)
			identifier_tests_box.disable_item_expand (is_valid_identifier_box)
			identifier_box.set_padding_width (5)
			identifier_box.disable_item_expand (identifier_label)
			identifier_label.set_text ("Identifier:")
			identifier_label.set_minimum_width (90)
			identifier_label.align_text_left
			escaped_identifier_box.set_padding_width (5)
			escaped_identifier_box.disable_item_expand (escaped_identifier_label)
			escaped_identifier_label.set_text ("Escaped identifier:")
			escaped_identifier_label.set_minimum_width (90)
			escaped_identifier_label.align_text_left
			escaped_identifier_text_field.disable_edit
			valid_identifier_box.set_padding_width (5)
			valid_identifier_box.disable_item_expand (valid_identifier_label)
			valid_identifier_label.set_text ("Valid identifier:")
			valid_identifier_label.set_minimum_width (90)
			valid_identifier_label.align_text_left
			valid_identifier_text_field.disable_edit
			is_valid_identifier_box.set_padding_width (5)
			is_valid_identifier_box.disable_item_expand (is_valid_identifier_label)
			is_valid_identifier_label.set_text ("Is valid identifier:")
			is_valid_identifier_label.set_minimum_width (90)
			is_valid_identifier_label.align_text_left
			is_valid_identifier_text_field.disable_edit
			create internal_font
			internal_font.set_family (3)
			internal_font.set_weight (8)
			internal_font.set_shape (10)
			internal_font.set_height (11)
			internal_font.preferred_families.extend ("Microsoft Sans Serif")
			type_output_test_frame.set_font (internal_font)
			type_output_test_frame.set_text ("Type Output Test")
			type_output_test_box.set_padding_width (5)
			type_output_test_box.set_border_width (5)
			type_output_test_box.disable_item_expand (type_box)
			type_output_test_box.disable_item_expand (output_type_box)
			type_box.set_padding_width (5)
			type_box.disable_item_expand (type_label)
			type_label.set_text ("Type:")
			type_label.set_minimum_width (90)
			type_label.align_text_left
			output_type_box.set_padding_width (5)
			output_type_box.disable_item_expand (output_type_label)
			output_type_label.set_text ("Output type:")
			output_type_label.set_minimum_width (90)
			output_type_label.align_text_left
			output_type_text_field.disable_edit
			create internal_font
			internal_font.set_family (3)
			internal_font.set_weight (8)
			internal_font.set_shape (10)
			internal_font.set_height (11)
			internal_font.preferred_families.extend ("Microsoft Sans Serif")
			properties_frame.set_font (internal_font)
			properties_frame.set_text ("Properties")
			properties_box.set_border_width (3)
			properties_box.disable_item_expand (properties_title_box)
			properties_title_box.set_border_width (2)
			supports_label.set_text ("Supported:")
			non_supports_label.set_text ("Not supported:")
			supports_box.set_padding_width (5)
			supports_box.set_border_width (5)
			compiler_box.set_padding_width (5)
			compiler_box.set_border_width (5)
			compiler_box.disable_item_expand (compiler_parameters_frame)
			create internal_font
			internal_font.set_family (3)
			internal_font.set_weight (8)
			internal_font.set_shape (10)
			internal_font.set_height (11)
			internal_font.preferred_families.extend ("Microsoft Sans Serif")
			compiler_tests.set_font (internal_font)
			compiler_tests.set_text ("Compiler Tests")
			compiler_tests_box.set_padding_width (10)
			compiler_tests_box.set_border_width (5)
			compiler_tests_box.disable_item_expand (compile_from_dom_box)
			compiler_tests_box.disable_item_expand (l_ev_horizontal_separator_2)
			compiler_tests_box.disable_item_expand (compile_from_file_box)
			compiler_tests_box.disable_item_expand (l_ev_horizontal_separator_3)
			compile_from_dom_box.set_padding_width (5)
			compile_from_dom_box.disable_item_expand (compile_from_dom_button)
			compile_from_dom_label.set_text ("Select CodeDom compile unit")
			compile_from_dom_label.align_text_left
			compile_from_dom_button.disable_sensitive
			compile_from_dom_button.set_text ("Compile")
			compile_from_dom_button.set_minimum_width (100)
			compile_from_file_box.set_padding_width (5)
			compile_from_file_title_box.disable_item_expand (compile_from_file_button)
			compile_from_file_label.set_text ("Compile assembly from file")
			compile_from_file_label.align_text_left
			compile_from_file_button.disable_sensitive
			compile_from_file_button.set_text ("Compile")
			compile_from_file_button.set_minimum_width (100)
			compile_from_file_file_box.set_padding_width (5)
			compile_from_file_file_box.disable_item_expand (browse_source_button)
			browse_source_button.set_text ("...")
			browse_source_button.set_minimum_width (40)
			compile_from_source_box.set_padding_width (5)
			compile_from_source_box.disable_item_expand (compile_from_source_title_box)
			compile_from_source_title_box.disable_item_expand (compile_from_source_button)
			compile_from_source_label.set_text ("Compile assembly from source")
			compile_from_source_label.align_text_left
			compile_from_source_button.disable_sensitive
			compile_from_source_button.set_text ("Compile")
			compile_from_source_button.set_minimum_width (100)
			source_text.set_minimum_height (100)
			create internal_font
			internal_font.set_family (3)
			internal_font.set_weight (8)
			internal_font.set_shape (10)
			internal_font.set_height (11)
			internal_font.preferred_families.extend ("Microsoft Sans Serif")
			compiler_parameters_frame.set_font (internal_font)
			compiler_parameters_frame.set_text ("Compiler Parameters")
			compiler_parameters_box.set_padding_width (5)
			compiler_parameters_box.set_border_width (5)
			compiler_parameters_box.disable_item_expand (generate_executable_box)
			compiler_parameters_box.disable_item_expand (generate_in_memory_box)
			compiler_parameters_box.disable_item_expand (include_debug_box)
			compiler_parameters_box.disable_item_expand (compiler_options_box)
			compiler_parameters_box.disable_item_expand (main_class_box)
			compiler_parameters_box.disable_item_expand (output_assembly_box)
			compiler_parameters_box.disable_item_expand (resource_box)
			compiler_parameters_box.disable_item_expand (l_ev_horizontal_separator_4)
			generate_executable_box.set_padding_width (5)
			generate_executable_box.disable_item_expand (generate_executable_label)
			generate_executable_box.disable_item_expand (generate_executable_check_button)
			generate_executable_label.set_text ("Generate executable:")
			generate_executable_label.set_minimum_width (130)
			generate_executable_label.align_text_left
			generate_in_memory_box.set_padding_width (5)
			generate_in_memory_box.disable_item_expand (generate_in_memory_label)
			generate_in_memory_box.disable_item_expand (generate_in_memory_check_button)
			generate_in_memory_label.set_text ("Generate in memory:")
			generate_in_memory_label.set_minimum_width (130)
			generate_in_memory_label.align_text_left
			include_debug_box.set_padding_width (5)
			include_debug_box.disable_item_expand (include_debug_label)
			include_debug_box.disable_item_expand (include_debug_check_button)
			include_debug_label.set_text ("Include debug information:")
			include_debug_label.set_minimum_width (130)
			include_debug_label.align_text_left
			compiler_options_box.set_padding_width (5)
			compiler_options_box.disable_item_expand (compiler_options_label)
			compiler_options_label.set_text ("Compiler options:")
			compiler_options_label.set_minimum_width (90)
			compiler_options_label.align_text_left
			main_class_box.set_padding_width (5)
			main_class_box.disable_item_expand (main_class_label)
			main_class_label.set_text ("Main class:")
			main_class_label.set_minimum_width (90)
			main_class_label.align_text_left
			output_assembly_box.set_padding_width (5)
			output_assembly_box.disable_item_expand (output_assembly_label)
			output_assembly_label.set_text ("Output assembly:")
			output_assembly_label.set_minimum_width (90)
			output_assembly_label.align_text_left
			resource_box.set_padding_width (5)
			resource_box.disable_item_expand (resource_label)
			resource_box.disable_item_expand (resource_browse_button)
			resource_label.set_text ("Resource file:")
			resource_label.set_minimum_width (90)
			resource_label.align_text_left
			resource_browse_button.set_text ("...")
			resource_browse_button.set_minimum_width (40)
			referenced_assemblies_box.set_padding_width (5)
			referenced_assemblies_box.disable_item_expand (referenced_assemblies_label_box)
			referenced_assemblies_label_box.set_minimum_width (130)
			referenced_assemblies_label_box.disable_item_expand (referenced_assemblies_label)
			referenced_assemblies_label.set_text ("Referenced assemblies:")
			referenced_assemblies_label.set_minimum_width (120)
			referenced_assemblies_label.align_text_left
			referenced_assemblies_list_box.set_padding_width (5)
			referenced_assemblies_list_box.disable_item_expand (referenced_assemblies_list_buttons)
			referenced_assemblies_list.set_minimum_height (80)
			new_reference_box.set_padding_width (5)
			new_reference_box.disable_item_expand (new_reference_browse_button)
			new_reference_browse_button.set_text ("...")
			new_reference_browse_button.set_minimum_width (40)
			referenced_assemblies_list_buttons.set_padding_width (5)
			referenced_assemblies_list_buttons.disable_item_expand (referenced_assemblies_add_button)
			referenced_assemblies_list_buttons.disable_item_expand (referenced_assemblies_remove_button)
			referenced_assemblies_add_button.disable_sensitive
			referenced_assemblies_add_button.set_text ("Add")
			referenced_assemblies_add_button.set_minimum_width (100)
			referenced_assemblies_remove_button.disable_sensitive
			referenced_assemblies_remove_button.set_text ("Remove")
			referenced_assemblies_remove_button.set_minimum_width (100)
			code_parser_box.set_padding_width (10)
			code_parser_box.set_border_width (5)
			code_parser_box.disable_item_expand (code_parser_frame)
			code_parser_box.disable_item_expand (parse_button_box)
			code_parser_frame.set_text ("Settings")
			code_parser_settings_box.set_padding_width (10)
			code_parser_settings_box.set_border_width (5)
			code_parser_settings_box.disable_item_expand (file_to_parse_label)
			code_parser_settings_box.disable_item_expand (parse_file_box)
			code_parser_settings_box.disable_item_expand (serialized_folder_label)
			code_parser_settings_box.disable_item_expand (serialized_file_box)
			file_to_parse_label.set_text ("File to parse:")
			file_to_parse_label.align_text_left
			parse_file_box.set_padding_width (5)
			parse_file_box.disable_item_expand (parse_file_browse_button)
			parse_file_browse_button.set_text ("...")
			parse_file_browse_button.set_minimum_width (40)
			serialized_folder_label.set_text ("Folder where to serialize CodeDom:")
			serialized_folder_label.align_text_left
			serialized_file_box.set_padding_width (5)
			serialized_file_box.disable_item_expand (serialized_folder_browse_button)
			serialized_folder_browse_button.set_text ("...")
			serialized_folder_browse_button.set_minimum_width (40)
			serialized_filename_label.set_text ("Serialized CodeDom filename (without extension):")
			serialized_filename_label.align_text_left
			parse_button_box.disable_item_expand (parse_button)
			parse_button.disable_sensitive
			parse_button.set_text ("Parse")
			parse_button.set_minimum_width (100)
			output_text.set_minimum_height (100)
			output_text.disable_edit
			
				--Connect events.
			provider_combo_box.change_actions.extend (agent on_provider_update)
			provider_browse_button.select_actions.extend (agent on_provider_browse)
			add_button.select_actions.extend (agent on_add_codedom_tree)
			remove_button.select_actions.extend (agent on_remove_codedom_tree)
			generation_path_text_field.change_actions.extend (agent on_change_generation_path)
			browse_button.select_actions.extend (agent on_browse_generated_file_folder)
			generated_filename_text_field.change_actions.extend (agent on_change_generated_filename)
			generate_button.select_actions.extend (agent on_generate_source)
			identifier_text_field.change_actions.extend (agent on_identifier_change)
			type_text_field.change_actions.extend (agent on_output_type_update)
			compile_from_dom_button.select_actions.extend (agent on_compile_from_dom)
			compile_from_file_button.select_actions.extend (agent on_compile_from_file)
			source_filename_text_field.change_actions.extend (agent on_source_file_name_change)
			browse_source_button.select_actions.extend (agent on_browse_source)
			compile_from_source_button.select_actions.extend (agent on_compile_from_source)
			source_text.change_actions.extend (agent on_source_change)
			resource_browse_button.select_actions.extend (agent on_browse_for_resource)
			referenced_assemblies_list.select_actions.extend (agent on_referenced_assembly_select)
			referenced_assemblies_list.deselect_actions.extend (agent on_referenced_assembly_deselect)
			new_reference_text_field.change_actions.extend (agent on_new_reference_change)
			new_reference_browse_button.select_actions.extend (agent on_browse_new_reference)
			referenced_assemblies_add_button.select_actions.extend (agent on_add_referenced_assembly)
			referenced_assemblies_remove_button.select_actions.extend (agent on_remove_referenced_assembly)
			parse_file_text_field.change_actions.extend (agent on_parse_file_change)
			parse_file_browse_button.select_actions.extend (agent on_browse_parse_file)
			serialized_folder_text_field.change_actions.extend (agent on_serialized_folder_change)
			serialized_folder_browse_button.select_actions.extend (agent on_browse_serialized_folder)
			serialized_filename_text_field.change_actions.extend (agent on_serialized_filename_change)
			parse_button.select_actions.extend (agent on_parse)
				-- Close the application when an interface close
				-- request is recieved on `Current'. i.e. the cross is clicked.

				-- Call `user_initialization'.
			user_initialization
		end

feature -- Access

	main_split: EV_HORIZONTAL_SPLIT_AREA
	left_box, code_provider_box, codedom_trees_box, code_generator_box, generation_tests_box, 
	generation_filename_box, identifier_tests_box, type_output_test_box, properties_box, 
	compiler_box, compiler_tests_box, compile_from_file_box, compile_from_source_box, 
	compiler_parameters_box, referenced_assemblies_box, referenced_assemblies_label_box, 
	referenced_assemblies_list_box, code_parser_box, code_parser_settings_box: EV_VERTICAL_BOX
	codedom_provider_frame, codedom_trees_frame, generation_tests_frame, identifier_tests_frame, 
	type_output_test_frame, properties_frame, compiler_tests, compiler_parameters_frame, 
	code_parser_frame: EV_FRAME
	provider_label, file_extension_title_label, file_extension_label, case_sensitive_title_label, 
	blank_lines_label, else_on_closing_label, indent_string_label, generation_path_label, 
	generated_file_name, generate_label, identifier_label, escaped_identifier_label, 
	valid_identifier_label, is_valid_identifier_label, type_label, output_type_label, 
	supports_label, non_supports_label, compile_from_dom_label, compile_from_file_label, 
	compile_from_source_label, generate_executable_label, generate_in_memory_label, 
	include_debug_label, compiler_options_label, main_class_label, output_assembly_label, 
	resource_label, referenced_assemblies_label, file_to_parse_label, serialized_folder_label, 
	serialized_filename_label: EV_LABEL
	provider_box, file_extension_box, case_sensitive_box, codedom_tree_buttons_box, 
	blank_lines_box, else_on_closing_box, indent_string_box, generation_path_box, 
	generate_box, identifier_box, escaped_identifier_box, valid_identifier_box, is_valid_identifier_box, 
	type_box, output_type_box, properties_title_box, supports_box, compile_from_dom_box, 
	compile_from_file_title_box, compile_from_file_file_box, compile_from_source_title_box, 
	generate_executable_box, generate_in_memory_box, include_debug_box, compiler_options_box, 
	main_class_box, output_assembly_box, resource_box, new_reference_box, referenced_assemblies_list_buttons, 
	parse_file_box, serialized_file_box, parse_button_box: EV_HORIZONTAL_BOX
	provider_combo_box: EV_COMBO_BOX
	provider_browse_button, add_button, remove_button, browse_button, generate_button, 
	compile_from_dom_button, compile_from_file_button, browse_source_button, compile_from_source_button, 
	resource_browse_button, new_reference_browse_button, referenced_assemblies_add_button, 
	referenced_assemblies_remove_button, parse_file_browse_button, serialized_folder_browse_button, 
	parse_button: EV_BUTTON
	case_sensitive_check_button, blank_lines_check_button, else_at_closing_check_button, 
	generate_executable_check_button, generate_in_memory_check_button, include_debug_check_button: EV_CHECK_BUTTON
	tree_bottom_split_area: EV_VERTICAL_SPLIT_AREA
	codedom_tree: EV_TREE
	codedom_node_info_text, source_text, output_text: EV_TEXT
	left_buttons_padding_cell, right_buttons_padding_cell, referenced_assemblies_right_padding_cell, 
	parse_button_padding_cell, code_parser_padding_cell: EV_CELL
	tests_notebook: EV_NOTEBOOK
	indent_string_text_field, generation_path_text_field, generated_filename_text_field, 
	identifier_text_field, escaped_identifier_text_field, valid_identifier_text_field, 
	is_valid_identifier_text_field, type_text_field, output_type_text_field, source_filename_text_field, 
	compiler_options_text_field, main_class_text_field, output_assembly_text_field, 
	resource_text_field, new_reference_text_field, parse_file_text_field, serialized_folder_text_field, 
	serialized_filename_text_field: EV_TEXT_FIELD
	supports_list, non_supports_list, referenced_assemblies_list: EV_LIST

feature {NONE} -- Implementation

	is_in_default_state: BOOLEAN is
			-- Is `Current' in its default state?
		do
			-- Re-implement if you wish to enable checking
			-- for `Current'.
			Result := True
		end
	
	user_initialization is
			-- Feature for custom initialization, called at end of `initialize'.
		deferred
		end
	
	on_provider_update is
			-- Called by `change_actions' of `provider_combo_box'.
		deferred
		end
	
	on_provider_browse is
			-- Called by `select_actions' of `provider_browse_button'.
		deferred
		end
	
	on_add_codedom_tree is
			-- Called by `select_actions' of `add_button'.
		deferred
		end
	
	on_remove_codedom_tree is
			-- Called by `select_actions' of `remove_button'.
		deferred
		end
	
	on_change_generation_path is
			-- Called by `change_actions' of `generation_path_text_field'.
		deferred
		end
	
	on_browse_generated_file_folder is
			-- Called by `select_actions' of `browse_button'.
		deferred
		end
	
	on_change_generated_filename is
			-- Called by `change_actions' of `generated_filename_text_field'.
		deferred
		end
	
	on_generate_source is
			-- Called by `select_actions' of `generate_button'.
		deferred
		end
	
	on_identifier_change is
			-- Called by `change_actions' of `identifier_text_field'.
		deferred
		end
	
	on_output_type_update is
			-- Called by `change_actions' of `type_text_field'.
		deferred
		end
	
	on_compile_from_dom is
			-- Called by `select_actions' of `compile_from_dom_button'.
		deferred
		end
	
	on_compile_from_file is
			-- Called by `select_actions' of `compile_from_file_button'.
		deferred
		end
	
	on_source_file_name_change is
			-- Called by `change_actions' of `source_filename_text_field'.
		deferred
		end
	
	on_browse_source is
			-- Called by `select_actions' of `browse_source_button'.
		deferred
		end
	
	on_compile_from_source is
			-- Called by `select_actions' of `compile_from_source_button'.
		deferred
		end
	
	on_source_change is
			-- Called by `change_actions' of `source_text'.
		deferred
		end
	
	on_browse_for_resource is
			-- Called by `select_actions' of `resource_browse_button'.
		deferred
		end
	
	on_referenced_assembly_select is
			-- Called by `select_actions' of `referenced_assemblies_list'.
		deferred
		end
	
	on_referenced_assembly_deselect is
			-- Called by `deselect_actions' of `referenced_assemblies_list'.
		deferred
		end
	
	on_new_reference_change is
			-- Called by `change_actions' of `new_reference_text_field'.
		deferred
		end
	
	on_browse_new_reference is
			-- Called by `select_actions' of `new_reference_browse_button'.
		deferred
		end
	
	on_add_referenced_assembly is
			-- Called by `select_actions' of `referenced_assemblies_add_button'.
		deferred
		end
	
	on_remove_referenced_assembly is
			-- Called by `select_actions' of `referenced_assemblies_remove_button'.
		deferred
		end
	
	on_parse_file_change is
			-- Called by `change_actions' of `parse_file_text_field'.
		deferred
		end
	
	on_browse_parse_file is
			-- Called by `select_actions' of `parse_file_browse_button'.
		deferred
		end
	
	on_serialized_folder_change is
			-- Called by `change_actions' of `serialized_folder_text_field'.
		deferred
		end
	
	on_browse_serialized_folder is
			-- Called by `select_actions' of `serialized_folder_browse_button'.
		deferred
		end
	
	on_serialized_filename_change is
			-- Called by `change_actions' of `serialized_filename_text_field'.
		deferred
		end
	
	on_parse is
			-- Called by `select_actions' of `parse_button'.
		deferred
		end
	

indexing
	copyright:	"Copyright (c) 1984-2006, Eiffel Software"
	license:	"GPL version 2 (see http://www.eiffel.com/licensing/gpl.txt)"
	licensing_options:	"http://www.eiffel.com/licensing"
	copying: "[
			This file is part of Eiffel Software's Eiffel Development Environment.
			
			Eiffel Software's Eiffel Development Environment is free
			software; you can redistribute it and/or modify it under
			the terms of the GNU General Public License as published
			by the Free Software Foundation, version 2 of the License
			(available at the URL listed under "license" above).
			
			Eiffel Software's Eiffel Development Environment is
			distributed in the hope that it will be useful,	but
			WITHOUT ANY WARRANTY; without even the implied warranty
			of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
			See the	GNU General Public License for more details.
			
			You should have received a copy of the GNU General Public
			License along with Eiffel Software's Eiffel Development
			Environment; if not, write to the Free Software Foundation,
			Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA
		]"
	source: "[
			 Eiffel Software
			 356 Storke Road, Goleta, CA 93117 USA
			 Telephone 805-685-1006, Fax 805-685-6869
			 Website http://www.eiffel.com
			 Customer support http://support.eiffel.com
		]"
end -- class TESTER_MAIN_WINDOW_IMP
