# ecom.lib - Makefile for Microsoft C

MV = copy
CC = $(ISE_EIFFEL)\Bcc55\Bin\bcc32.exe
OUTPUT_CMD = -o
CFLAGS = -w- -I$(ISE_EIFFEL)\BCC55\include -L$(ISE_EIFFEL)\BCC55\lib -D_WIN32_DCOM -c -I..\..\client\include -I..\..\server\include -I..\..\common\include -I$(ISE_EIFFEL)\studio\spec\windows\include -I$(ISE_EIFFEL)\library\com\spec\windows\include 

OBJ = ecom_eiffel_compiler_ieiffelassemblyproperties_impl_stub.obj \
ecom_eiffel_compiler_ieiffelclassdescriptor_impl_stub.obj \
ecom_eiffel_compiler_ieiffelclusterdescriptor_impl_stub.obj \
ecom_eiffel_compiler_ieiffelclusterproperties_impl_stub.obj \
ecom_eiffel_compiler_ieiffelcompilerevents_impl_stub.obj \
ecom_eiffel_compiler_ieiffelcompiler_impl_stub.obj \
ecom_eiffel_compiler_ieiffelcompletionentry_impl_stub.obj \
ecom_eiffel_compiler_ieiffelcompletioninfo_impl_stub.obj \
ecom_eiffel_compiler_ieiffelfeaturedescriptor_impl_stub.obj \
ecom_eiffel_compiler_ieiffelhtmldocevents_impl_stub.obj \
ecom_eiffel_compiler_ieiffelhtmldocgenerator_impl_stub.obj \
ecom_eiffel_compiler_ieiffelprojectproperties_impl_stub.obj \
ecom_eiffel_compiler_ieiffelsystemassemblies_impl_stub.obj \
ecom_eiffel_compiler_ieiffelsystembrowser_impl_stub.obj \
ecom_eiffel_compiler_ieiffelsystemclusters_impl_stub.obj \
ecom_eiffel_compiler_ieiffelsystemexternals_impl_stub.obj \
ecom_eiffel_compiler_ienumassembly_impl_stub.obj \
ecom_eiffel_compiler_ienumclusterexcludes_impl_stub.obj \
ecom_eiffel_compiler_ienumclusterprop_impl_stub.obj \
ecom_eiffel_compiler_ienumcluster_impl_stub.obj \
ecom_eiffel_compiler_ienumcompletionentry_impl_stub.obj \
ecom_eiffel_compiler_ienumeiffelclass_impl_stub.obj \
ecom_eiffel_compiler_ienumfeature_impl_stub.obj \
ecom_eiffel_compiler_ienumincludepaths_impl_stub.obj \
ecom_eiffel_compiler_ienumobjectfiles_impl_stub.obj \


WOBJ = wecom_eiffel_compiler_ieiffelassemblyproperties_impl_stub.obj \
wecom_eiffel_compiler_ieiffelclassdescriptor_impl_stub.obj \
wecom_eiffel_compiler_ieiffelclusterdescriptor_impl_stub.obj \
wecom_eiffel_compiler_ieiffelclusterproperties_impl_stub.obj \
wecom_eiffel_compiler_ieiffelcompilerevents_impl_stub.obj \
wecom_eiffel_compiler_ieiffelcompiler_impl_stub.obj \
wecom_eiffel_compiler_ieiffelcompletionentry_impl_stub.obj \
wecom_eiffel_compiler_ieiffelcompletioninfo_impl_stub.obj \
wecom_eiffel_compiler_ieiffelfeaturedescriptor_impl_stub.obj \
wecom_eiffel_compiler_ieiffelhtmldocevents_impl_stub.obj \
wecom_eiffel_compiler_ieiffelhtmldocgenerator_impl_stub.obj \
wecom_eiffel_compiler_ieiffelprojectproperties_impl_stub.obj \
wecom_eiffel_compiler_ieiffelsystemassemblies_impl_stub.obj \
wecom_eiffel_compiler_ieiffelsystembrowser_impl_stub.obj \
wecom_eiffel_compiler_ieiffelsystemclusters_impl_stub.obj \
wecom_eiffel_compiler_ieiffelsystemexternals_impl_stub.obj \
wecom_eiffel_compiler_ienumassembly_impl_stub.obj \
wecom_eiffel_compiler_ienumclusterexcludes_impl_stub.obj \
wecom_eiffel_compiler_ienumclusterprop_impl_stub.obj \
wecom_eiffel_compiler_ienumcluster_impl_stub.obj \
wecom_eiffel_compiler_ienumcompletionentry_impl_stub.obj \
wecom_eiffel_compiler_ienumeiffelclass_impl_stub.obj \
wecom_eiffel_compiler_ienumfeature_impl_stub.obj \
wecom_eiffel_compiler_ienumincludepaths_impl_stub.obj \
wecom_eiffel_compiler_ienumobjectfiles_impl_stub.obj \


all:: ecom.lib ecom_final.lib

ecom.lib: $(WOBJ)
	if exist $@ del $@
	&$(ISE_EIFFEL)\Bcc55\Bin\tlib.exe /p256 $@ +-$**
	del *.obj
	if not exist bcb mkdir bcb
	$(MV) $@ bcb
	del $@

ecom_final.lib: $(OBJ)
	if exist $@ del $@
	&$(ISE_EIFFEL)\Bcc55\Bin\tlib.exe /p256 $@ +-$**
	del *.obj
	if not exist bcb mkdir bcb
	$(MV) $@ bcb
	del $@

.cpp.obj:
	$(CC) $(CFLAGS) $<

wecom_eiffel_compiler_ieiffelassemblyproperties_impl_stub.obj: ecom_eiffel_compiler_ieiffelassemblyproperties_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelclassdescriptor_impl_stub.obj: ecom_eiffel_compiler_ieiffelclassdescriptor_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelclusterdescriptor_impl_stub.obj: ecom_eiffel_compiler_ieiffelclusterdescriptor_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelclusterproperties_impl_stub.obj: ecom_eiffel_compiler_ieiffelclusterproperties_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelcompilerevents_impl_stub.obj: ecom_eiffel_compiler_ieiffelcompilerevents_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelcompiler_impl_stub.obj: ecom_eiffel_compiler_ieiffelcompiler_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelcompletionentry_impl_stub.obj: ecom_eiffel_compiler_ieiffelcompletionentry_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelcompletioninfo_impl_stub.obj: ecom_eiffel_compiler_ieiffelcompletioninfo_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelfeaturedescriptor_impl_stub.obj: ecom_eiffel_compiler_ieiffelfeaturedescriptor_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelhtmldocevents_impl_stub.obj: ecom_eiffel_compiler_ieiffelhtmldocevents_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelhtmldocgenerator_impl_stub.obj: ecom_eiffel_compiler_ieiffelhtmldocgenerator_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelprojectproperties_impl_stub.obj: ecom_eiffel_compiler_ieiffelprojectproperties_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelsystemassemblies_impl_stub.obj: ecom_eiffel_compiler_ieiffelsystemassemblies_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelsystembrowser_impl_stub.obj: ecom_eiffel_compiler_ieiffelsystembrowser_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelsystemclusters_impl_stub.obj: ecom_eiffel_compiler_ieiffelsystemclusters_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelsystemexternals_impl_stub.obj: ecom_eiffel_compiler_ieiffelsystemexternals_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ienumassembly_impl_stub.obj: ecom_eiffel_compiler_ienumassembly_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ienumclusterexcludes_impl_stub.obj: ecom_eiffel_compiler_ienumclusterexcludes_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ienumclusterprop_impl_stub.obj: ecom_eiffel_compiler_ienumclusterprop_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ienumcluster_impl_stub.obj: ecom_eiffel_compiler_ienumcluster_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ienumcompletionentry_impl_stub.obj: ecom_eiffel_compiler_ienumcompletionentry_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ienumeiffelclass_impl_stub.obj: ecom_eiffel_compiler_ienumeiffelclass_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ienumfeature_impl_stub.obj: ecom_eiffel_compiler_ienumfeature_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ienumincludepaths_impl_stub.obj: ecom_eiffel_compiler_ienumincludepaths_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ienumobjectfiles_impl_stub.obj: ecom_eiffel_compiler_ienumobjectfiles_impl_stub.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

