# ecom.lib - Makefile for Microsoft C

MV = copy
CC = $(ISE_EIFFEL)\Bcc55\Bin\bcc32.exe
OUTPUT_CMD = -o
CFLAGS = -w- -I$(ISE_EIFFEL)\BCC55\include -L$(ISE_EIFFEL)\BCC55\lib -D_WIN32_DCOM -c -I..\..\client\include -I..\..\server\include -I..\..\common\include -I$(ISE_EIFFEL)\studio\spec\windows\include -I$(ISE_EIFFEL)\library\com\spec\windows\include 

OBJ = ecom_eiffelcomcompiler_ceiffelcompiler.obj \
ecom_eiffelcomcompiler_ceiffelcompletioninfo.obj \
ecom_eiffelcomcompiler_ceiffelproject.obj \
ecom_eiffelcomcompiler_ieiffelassemblyproperties_impl_proxy.obj \
ecom_eiffelcomcompiler_ieiffelclassdescriptor_impl_proxy.obj \
ecom_eiffelcomcompiler_ieiffelclusterdescriptor_impl_proxy.obj \
ecom_eiffelcomcompiler_ieiffelclusterproperties_impl_proxy.obj \
ecom_eiffelcomcompiler_ieiffelcompiler_impl_proxy.obj \
ecom_eiffelcomcompiler_ieiffelcompletioninfo_impl_proxy.obj \
ecom_eiffelcomcompiler_ieiffelexception_impl_proxy.obj \
ecom_eiffelcomcompiler_ieiffelfeaturedescriptor_impl_proxy.obj \
ecom_eiffelcomcompiler_ieiffelhtmldocumentationevents_impl_proxy.obj \
ecom_eiffelcomcompiler_ieiffelhtmldocumentationgenerator_impl_proxy.obj \
ecom_eiffelcomcompiler_ieiffelparameterdescriptor_impl_proxy.obj \
ecom_eiffelcomcompiler_ieiffelprojectproperties_impl_proxy.obj \
ecom_eiffelcomcompiler_ieiffelsystemassemblies_impl_proxy.obj \
ecom_eiffelcomcompiler_ieiffelsystembrowser_impl_proxy.obj \
ecom_eiffelcomcompiler_ieiffelsystemclusters_impl_proxy.obj \
ecom_eiffelcomcompiler_ieiffelsystemexternals_impl_proxy.obj \
ecom_eiffelcomcompiler_ienumassembly_impl_proxy.obj \
ecom_eiffelcomcompiler_ienumclusterexcludes_impl_proxy.obj \
ecom_eiffelcomcompiler_ienumclusterprop_impl_proxy.obj \
ecom_eiffelcomcompiler_ienumcluster_impl_proxy.obj \
ecom_eiffelcomcompiler_ienumeiffelclass_impl_proxy.obj \
ecom_eiffelcomcompiler_ienumfeature_impl_proxy.obj \
ecom_eiffelcomcompiler_ienumincludepaths_impl_proxy.obj \
ecom_eiffelcomcompiler_ienumobjectfiles_impl_proxy.obj \
ecom_eiffelcomcompiler_ienumparameter_impl_proxy.obj \
ecom_gce_ise_c.obj \
ecom_gec_ise_c.obj \


WOBJ = wecom_eiffelcomcompiler_ceiffelcompiler.obj \
wecom_eiffelcomcompiler_ceiffelcompletioninfo.obj \
wecom_eiffelcomcompiler_ceiffelproject.obj \
wecom_eiffelcomcompiler_ieiffelassemblyproperties_impl_proxy.obj \
wecom_eiffelcomcompiler_ieiffelclassdescriptor_impl_proxy.obj \
wecom_eiffelcomcompiler_ieiffelclusterdescriptor_impl_proxy.obj \
wecom_eiffelcomcompiler_ieiffelclusterproperties_impl_proxy.obj \
wecom_eiffelcomcompiler_ieiffelcompiler_impl_proxy.obj \
wecom_eiffelcomcompiler_ieiffelcompletioninfo_impl_proxy.obj \
wecom_eiffelcomcompiler_ieiffelexception_impl_proxy.obj \
wecom_eiffelcomcompiler_ieiffelfeaturedescriptor_impl_proxy.obj \
wecom_eiffelcomcompiler_ieiffelhtmldocumentationevents_impl_proxy.obj \
wecom_eiffelcomcompiler_ieiffelhtmldocumentationgenerator_impl_proxy.obj \
wecom_eiffelcomcompiler_ieiffelparameterdescriptor_impl_proxy.obj \
wecom_eiffelcomcompiler_ieiffelprojectproperties_impl_proxy.obj \
wecom_eiffelcomcompiler_ieiffelsystemassemblies_impl_proxy.obj \
wecom_eiffelcomcompiler_ieiffelsystembrowser_impl_proxy.obj \
wecom_eiffelcomcompiler_ieiffelsystemclusters_impl_proxy.obj \
wecom_eiffelcomcompiler_ieiffelsystemexternals_impl_proxy.obj \
wecom_eiffelcomcompiler_ienumassembly_impl_proxy.obj \
wecom_eiffelcomcompiler_ienumclusterexcludes_impl_proxy.obj \
wecom_eiffelcomcompiler_ienumclusterprop_impl_proxy.obj \
wecom_eiffelcomcompiler_ienumcluster_impl_proxy.obj \
wecom_eiffelcomcompiler_ienumeiffelclass_impl_proxy.obj \
wecom_eiffelcomcompiler_ienumfeature_impl_proxy.obj \
wecom_eiffelcomcompiler_ienumincludepaths_impl_proxy.obj \
wecom_eiffelcomcompiler_ienumobjectfiles_impl_proxy.obj \
wecom_eiffelcomcompiler_ienumparameter_impl_proxy.obj \
wecom_gce_ise_c.obj \
wecom_gec_ise_c.obj \


all:: ecom.lib ecom_final.lib

ecom.lib: $(WOBJ)
	if exist $@ del $@
	&$(ISE_EIFFEL)\Bcc55\Bin\tlib.exe /p256 $@ +-$**
	del *.obj
	if not exist bcb mkdir bcb
	$(MV) $@ bcb
	del $@

ecom_final.lib: $(OBJ)
	if exist $@ del $@
	&$(ISE_EIFFEL)\Bcc55\Bin\tlib.exe /p256 $@ +-$**
	del *.obj
	if not exist bcb mkdir bcb
	$(MV) $@ bcb
	del $@

.cpp.obj:
	$(CC) $(CFLAGS) $<

wecom_eiffelcomcompiler_ceiffelcompiler.obj: ecom_eiffelcomcompiler_ceiffelcompiler.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ceiffelcompletioninfo.obj: ecom_eiffelcomcompiler_ceiffelcompletioninfo.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ceiffelproject.obj: ecom_eiffelcomcompiler_ceiffelproject.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelassemblyproperties_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelassemblyproperties_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelclassdescriptor_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelclassdescriptor_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelclusterdescriptor_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelclusterdescriptor_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelclusterproperties_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelclusterproperties_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelcompiler_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelcompiler_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelcompletioninfo_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelcompletioninfo_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelexception_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelexception_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelfeaturedescriptor_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelfeaturedescriptor_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelhtmldocumentationevents_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelhtmldocumentationevents_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelhtmldocumentationgenerator_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelhtmldocumentationgenerator_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelparameterdescriptor_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelparameterdescriptor_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelprojectproperties_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelprojectproperties_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelsystemassemblies_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelsystemassemblies_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelsystembrowser_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelsystembrowser_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelsystemclusters_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelsystemclusters_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ieiffelsystemexternals_impl_proxy.obj: ecom_eiffelcomcompiler_ieiffelsystemexternals_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ienumassembly_impl_proxy.obj: ecom_eiffelcomcompiler_ienumassembly_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ienumclusterexcludes_impl_proxy.obj: ecom_eiffelcomcompiler_ienumclusterexcludes_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ienumclusterprop_impl_proxy.obj: ecom_eiffelcomcompiler_ienumclusterprop_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ienumcluster_impl_proxy.obj: ecom_eiffelcomcompiler_ienumcluster_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ienumeiffelclass_impl_proxy.obj: ecom_eiffelcomcompiler_ienumeiffelclass_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ienumfeature_impl_proxy.obj: ecom_eiffelcomcompiler_ienumfeature_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ienumincludepaths_impl_proxy.obj: ecom_eiffelcomcompiler_ienumincludepaths_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ienumobjectfiles_impl_proxy.obj: ecom_eiffelcomcompiler_ienumobjectfiles_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffelcomcompiler_ienumparameter_impl_proxy.obj: ecom_eiffelcomcompiler_ienumparameter_impl_proxy.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_gce_ise_c.obj: ecom_gce_ise_c.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_gec_ise_c.obj: ecom_gec_ise_c.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

