<project>
	<project_name>docs</project_name>
	<root_directory>d:/_dev/trunk/Src/../Documentation/xmldoc</root_directory>
	<schema>D:/_dev/trunk/Src/tools/doc_builder/resources/xml/schema/document.xsd</schema>
	<html_css>d:/_dev/trunk/Src/../Documentation/xmldoc/default.css</html_css>
	<header_override>True</header_override>
	<use_header_from_file>False</use_header_from_file>
	<footer_override>True</footer_override>
	<use_footer_from_file>False</use_footer_from_file>
	<process_includes>True</process_includes>
	<process_header>True</process_header>
	<process_footer>True</process_footer>
	<process_html_stylesheet>True</process_html_stylesheet>
	<include_navigation_links>True</include_navigation_links>
	<generate_dhtml_filter>True</generate_dhtml_filter>
	<generate_feature_nodes>True</generate_feature_nodes>
	<filter>
		<filter_description>EiffelStudio for Mac OS X</filter_description>
		<filter_highlight_color_red>0.87451</filter_highlight_color_red>
		<filter_highlight_color_green>1</filter_highlight_color_green>
		<filter_highlight_color_blue>0.87451</filter_highlight_color_blue>
		<filter_highlight_on>True</filter_highlight_on>
		<filter_primary_flag>studio_mac</filter_primary_flag>
		<tag>all</tag>
		<tag>studio_mac</tag>
		<tag>studio</tag>
	</filter>
	<filter>
		<filter_description>EiffelStudio for Windows</filter_description>
		<filter_highlight_color_red>0.937255</filter_highlight_color_red>
		<filter_highlight_color_green>0.937255</filter_highlight_color_green>
		<filter_highlight_color_blue>0.937255</filter_highlight_color_blue>
		<filter_highlight_on>False</filter_highlight_on>
		<filter_primary_flag>studio_win</filter_primary_flag>
		<tag>all</tag>
		<tag>studio_win</tag>
		<tag>studio</tag>
	</filter>
	<filter>
		<filter_description>ENViSioN!</filter_description>
		<filter_highlight_color_red>1</filter_highlight_color_red>
		<filter_highlight_color_green>0.811765</filter_highlight_color_green>
		<filter_highlight_color_blue>0.623529</filter_highlight_color_blue>
		<filter_highlight_on>False</filter_highlight_on>
		<filter_primary_flag>envision</filter_primary_flag>
		<tag>all</tag>
		<tag>envision</tag>
	</filter>
	<filter>
		<filter_description>EiffelStudio for Unix/Linux</filter_description>
		<filter_highlight_color_red>1</filter_highlight_color_red>
		<filter_highlight_color_green>1</filter_highlight_color_green>
		<filter_highlight_color_blue>0.807843</filter_highlight_color_blue>
		<filter_highlight_on>False</filter_highlight_on>
		<filter_primary_flag>studio_lin</filter_primary_flag>
		<tag>all</tag>
		<tag>studio_lin</tag>
		<tag>studio</tag>
	</filter>
	<filter>
		<filter_description>EiffelStudio</filter_description>
		<filter_highlight_color_red>0.701961</filter_highlight_color_red>
		<filter_highlight_color_green>0.85098</filter_highlight_color_green>
		<filter_highlight_color_blue>1</filter_highlight_color_blue>
		<filter_highlight_on>True</filter_highlight_on>
		<filter_primary_flag>studio</filter_primary_flag>
		<tag>all</tag>
		<tag>studio</tag>
		<tag>studio_win</tag>
		<tag>studio_lin</tag>
		<tag>studio_mac</tag>
	</filter>
	<shortcut>
		<shortcut_key>1</shortcut_key>
		<shortcut_value>&lt;cluster_name&gt;[tag]&lt;/cluster_name&gt;</shortcut_value>
	</shortcut>
	<shortcut>
		<shortcut_key>2</shortcut_key>
		<shortcut_value>&lt;class_name&gt;[tag]&lt;/class_name&gt;</shortcut_value>
	</shortcut>
	<shortcut>
		<shortcut_key>3</shortcut_key>
		<shortcut_value>&lt;feature_name&gt;[tag]&lt;/feature_name&gt;</shortcut_value>
	</shortcut>
	<shortcut>
		<shortcut_key>4</shortcut_key>
		<shortcut_value>&lt;keyword&gt;[tag]&lt;/keyword&gt;</shortcut_value>
	</shortcut>
	<shortcut>
		<shortcut_key>69</shortcut_key>
		<shortcut_value>&lt;bold&gt;[tag]&lt;/bold&gt;</shortcut_value>
	</shortcut>
	<shortcut>
		<shortcut_key>72</shortcut_key>
		<shortcut_value>&lt;code&gt;&lt;class_name&gt;</shortcut_value>
	</shortcut>
	<shortcut>
		<shortcut_key>75</shortcut_key>
		<shortcut_value>&lt;heading&gt;&lt;size&gt;&lt;/size&gt;[tag]&lt;/heading&gt;</shortcut_value>
	</shortcut>
	<shortcut>
		<shortcut_key>76</shortcut_key>
		<shortcut_value>&lt;italic&gt;[tag]&lt;/italic&gt;</shortcut_value>
	</shortcut>
	<shortcut>
		<shortcut_key>78</shortcut_key>
		<shortcut_value>&lt;link&gt;&lt;url&gt;&lt;/url&gt;&lt;label&gt;[tag]&lt;/label&gt;&lt;/link&gt;</shortcut_value>
	</shortcut>
	<shortcut>
		<shortcut_key>82</shortcut_key>
		<shortcut_value>&lt;output output=""&gt;[tag]&lt;/output&gt;</shortcut_value>
	</shortcut>
	<shortcut>
		<shortcut_key>83</shortcut_key>
		<shortcut_value>&lt;paragraph&gt;[tag]&lt;/paragraph&gt;</shortcut_value>
	</shortcut>
	<shortcut>
		<shortcut_key>87</shortcut_key>
		<shortcut_value>&lt;table&gt;&lt;row&gt;&lt;cell&gt;[tag]&lt;/cell&gt;&lt;/row&gt;&lt;/table&gt;</shortcut_value>
	</shortcut>
	<shortcut>
		<shortcut_key>88</shortcut_key>
		<shortcut_value>&lt;url&gt;[tag]&lt;/url&gt;</shortcut_value>
	</shortcut></project>