<project>
	<project_name>compliance_checker</project_name>
	<root_directory>E:/delivery/xmldoc/tools/compliance_checker</root_directory>
	<schema>D:/Development/EiffelDoc/resources/xml/schema/document.xsd</schema>
	<html_css>E:/delivery/xmldoc/tools/compliance_checker/default.css</html_css>
	<header_override>True</header_override>
	<use_header_from_file>False</use_header_from_file>
	<footer_override>True</footer_override>
	<use_footer_from_file>False</use_footer_from_file>
	<process_includes>True</process_includes>
	<process_header>True</process_header>
	<process_footer>True</process_footer>
	<process_html_stylesheet>True</process_html_stylesheet>
	<include_navigation_links>True</include_navigation_links>
	<generate_dhtml_filter>True</generate_dhtml_filter>
	<generate_feature_nodes>True</generate_feature_nodes>
	<filter>
		<filter_description>Eiffel for .NET Compliance Checker</filter_description>
		<filter_highlight_color_red>1</filter_highlight_color_red>
		<filter_highlight_color_green>1</filter_highlight_color_green>
		<filter_highlight_color_blue>1</filter_highlight_color_blue>
		<filter_highlight_on>False</filter_highlight_on>
		<tag>eiffel_compliance_checker</tag>
	</filter>
	<filter>
		<filter_description>eiffel_compliance_checker</filter_description>
		<filter_highlight_color_red>1</filter_highlight_color_red>
		<filter_highlight_color_green>1</filter_highlight_color_green>
		<filter_highlight_color_blue>1</filter_highlight_color_blue>
		<filter_highlight_on>False</filter_highlight_on>
		<tag>eiffel_compliance_checker</tag>
	</filter>
	<shortcut>
		<shortcut_key>75</shortcut_key>
		<shortcut_value>&lt;link&gt;&lt;url&gt;url&lt;/url&gt;&lt;label&gt;[tag]&lt;/label&gt;&lt;/link&gt;</shortcut_value>
	</shortcut>
	<shortcut>
		<shortcut_key>76</shortcut_key>
		<shortcut_value>&lt;italic&gt;[tag]&lt;/italic&gt;</shortcut_value>
	</shortcut>
	<shortcut>
		<shortcut_key>69</shortcut_key>
		<shortcut_value>&lt;bold&gt;[tag]&lt;/bold&gt;</shortcut_value>
	</shortcut>
	<toc_folders>
		<folder>E:/delivery/xmldoc/tools/compliance_checker\10_getting_started</folder>
		<folder>E:/delivery/xmldoc/tools/compliance_checker\20_projects</folder>
		<folder>E:/delivery/xmldoc/tools/compliance_checker\30_user_interface</folder>
	</toc_folders></project>