
extern EIF_INTEGER int_and (EIF_INTEGER, EIF_INTEGER);
extern EIF_INTEGER int_or  (EIF_INTEGER, EIF_INTEGER);
extern EIF_INTEGER int_xor (EIF_INTEGER, EIF_INTEGER);
extern EIF_INTEGER int_not (EIF_INTEGER, EIF_INTEGER);
