<project>
	<project_name>docs</project_name>
	<root_directory>E:/delivery/xmldoc</root_directory>
	<schema>D:/Development/EiffelDoc/resources/xml/schema/document.xsd</schema>
	<html_css>E:/delivery/xmldoc/default.css</html_css>
	<header_override>True</header_override>
	<use_header_from_file>False</use_header_from_file>
	<footer_override>True</footer_override>
	<use_footer_from_file>False</use_footer_from_file>
	<process_includes>True</process_includes>
	<process_header>True</process_header>
	<process_footer>True</process_footer>
	<process_html_stylesheet>True</process_html_stylesheet>
	<include_navigation_links>True</include_navigation_links>
	<generate_dhtml_filter>True</generate_dhtml_filter>
	<generate_feature_nodes>True</generate_feature_nodes>
	<filter>
		<filter_description>ENViSioN!</filter_description>
		<filter_highlight_color_red>1</filter_highlight_color_red>
		<filter_highlight_color_green>1</filter_highlight_color_green>
		<filter_highlight_color_blue>1</filter_highlight_color_blue>
		<filter_highlight_on>False</filter_highlight_on>
		<tag>all</tag>
		<tag>envision</tag>
	</filter>
	<filter>
		<filter_description>EiffelStudio for Mac OS X</filter_description>
		<filter_highlight_color_red>0.8745098</filter_highlight_color_red>
		<filter_highlight_color_green>0</filter_highlight_color_green>
		<filter_highlight_color_blue>0</filter_highlight_color_blue>
		<filter_highlight_on>False</filter_highlight_on>
	</filter></project>