# ecom.lib - Makefile for Microsoft C

MV = copy
CC = cl
OUTPUT_CMD = -Fo
CFLAGS = -W0 -Zi -D_WIN32_DCOM -c -I$(ISE_EIFFEL)\studio\spec\windows\include -I$(EIFFEL_SRC)\library\com\spec\windows\include 

OBJ = ceiffelcompiler_factory.obj \
ceiffelproject_factory.obj \
ecom_eiffel_compiler_ceiffelcompiler_s.obj \
ecom_eiffel_compiler_ceiffelproject_s.obj \
ecom_eiffel_compiler_ieiffelclassdescriptor_impl_stub_s.obj \
ecom_eiffel_compiler_ieiffelclusterdescriptor_impl_stub_s.obj \
ecom_eiffel_compiler_ieiffelclusterproperties_impl_stub_s.obj \
ecom_eiffel_compiler_ieiffelcompiler_impl_stub_s.obj \
ecom_eiffel_compiler_ieiffelfeaturedescriptor_impl_stub_s.obj \
ecom_eiffel_compiler_ieiffelprojectproperties_impl_stub_s.obj \
ecom_eiffel_compiler_ieiffelproject_impl_stub_s.obj \
ecom_eiffel_compiler_ieiffelsystembrowser_impl_stub_s.obj \
ecom_gce_eif_compiler.obj \
ecom_gec_eif_compiler.obj \
ecom_xcp_ieiffelcompilerevents_ceiffelcompiler.obj \
server_registration.obj \
ecom_eiffel_compiler_ieiffelclassdescriptor_impl_proxy_s.obj \
ecom_eiffel_compiler_ieiffelclusterdescriptor_impl_proxy_s.obj \
ecom_eiffel_compiler_ieiffelclusterproperties_impl_proxy_s.obj \
ecom_eiffel_compiler_ieiffelcompilerevents_impl_proxy_s.obj \
ecom_eiffel_compiler_ieiffelcompiler_impl_proxy_s.obj \
ecom_eiffel_compiler_ieiffelfeaturedescriptor_impl_proxy_s.obj \
ecom_eiffel_compiler_ieiffelprojectproperties_impl_proxy_s.obj \
ecom_eiffel_compiler_ieiffelproject_impl_proxy_s.obj \
ecom_eiffel_compiler_ieiffelsystembrowser_impl_proxy_s.obj \
ecom_eiffel_compiler_ienumclass_impl_stub_s.obj \
ecom_eiffel_compiler_ienumcluster_impl_stub_s.obj \
ecom_eiffel_compiler_ienumfeature_impl_stub_s.obj \

WOBJ = wceiffelcompiler_factory.obj \
wceiffelproject_factory.obj \
wecom_eiffel_compiler_ceiffelcompiler_s.obj \
wecom_eiffel_compiler_ceiffelproject_s.obj \
wecom_eiffel_compiler_ieiffelclassdescriptor_impl_stub_s.obj \
wecom_eiffel_compiler_ieiffelclusterdescriptor_impl_stub_s.obj \
wecom_eiffel_compiler_ieiffelclusterproperties_impl_stub_s.obj \
wecom_eiffel_compiler_ieiffelcompiler_impl_stub_s.obj \
wecom_eiffel_compiler_ieiffelfeaturedescriptor_impl_stub_s.obj \
wecom_eiffel_compiler_ieiffelprojectproperties_impl_stub_s.obj \
wecom_eiffel_compiler_ieiffelproject_impl_stub_s.obj \
wecom_eiffel_compiler_ieiffelsystembrowser_impl_stub_s.obj \
wecom_gce_eif_compiler.obj \
wecom_gec_eif_compiler.obj \
wecom_xcp_ieiffelcompilerevents_ceiffelcompiler.obj \
wserver_registration.obj \
wecom_eiffel_compiler_ieiffelclassdescriptor_impl_proxy_s.obj \
wecom_eiffel_compiler_ieiffelclusterdescriptor_impl_proxy_s.obj \
wecom_eiffel_compiler_ieiffelclusterproperties_impl_proxy_s.obj \
wecom_eiffel_compiler_ieiffelcompilerevents_impl_proxy_s.obj \
wecom_eiffel_compiler_ieiffelcompiler_impl_proxy_s.obj \
wecom_eiffel_compiler_ieiffelfeaturedescriptor_impl_proxy_s.obj \
wecom_eiffel_compiler_ieiffelprojectproperties_impl_proxy_s.obj \
wecom_eiffel_compiler_ieiffelproject_impl_proxy_s.obj \
wecom_eiffel_compiler_ieiffelsystembrowser_impl_proxy_s.obj \
wecom_eiffel_compiler_ienumclass_impl_stub_s.obj \
wecom_eiffel_compiler_ienumcluster_impl_stub_s.obj \
wecom_eiffel_compiler_ienumfeature_impl_stub_s.obj \

all:: ecom.lib ecom_final.lib

ecom.lib: $(WOBJ)
	if exist $@ del $@
	lib -OUT:$@ $(WOBJ)
	del *.obj
	if not exist msc mkdir msc
	$(MV) $@ msc
	del $@

ecom_final.lib: $(OBJ)
	if exist $@ del $@
	lib -OUT:$@ $(OBJ)
	del *.obj
	if not exist msc mkdir msc
	$(MV) $@ msc
	del $@

.cpp.obj:
	$(CC) $(CFLAGS) $<

wceiffelcompiler_factory.obj: ceiffelcompiler_factory.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wceiffelproject_factory.obj: ceiffelproject_factory.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ceiffelcompiler_s.obj: ecom_eiffel_compiler_ceiffelcompiler_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ceiffelproject_s.obj: ecom_eiffel_compiler_ceiffelproject_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelclassdescriptor_impl_stub_s.obj: ecom_eiffel_compiler_ieiffelclassdescriptor_impl_stub_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelclusterdescriptor_impl_stub_s.obj: ecom_eiffel_compiler_ieiffelclusterdescriptor_impl_stub_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelclusterproperties_impl_stub_s.obj: ecom_eiffel_compiler_ieiffelclusterproperties_impl_stub_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelcompiler_impl_stub_s.obj: ecom_eiffel_compiler_ieiffelcompiler_impl_stub_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelfeaturedescriptor_impl_stub_s.obj: ecom_eiffel_compiler_ieiffelfeaturedescriptor_impl_stub_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelprojectproperties_impl_stub_s.obj: ecom_eiffel_compiler_ieiffelprojectproperties_impl_stub_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelproject_impl_stub_s.obj: ecom_eiffel_compiler_ieiffelproject_impl_stub_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelsystembrowser_impl_stub_s.obj: ecom_eiffel_compiler_ieiffelsystembrowser_impl_stub_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_gce_eif_compiler.obj: ecom_gce_eif_compiler.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_gec_eif_compiler.obj: ecom_gec_eif_compiler.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_xcp_ieiffelcompilerevents_ceiffelcompiler.obj: ecom_xcp_ieiffelcompilerevents_ceiffelcompiler.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wserver_registration.obj: server_registration.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelclassdescriptor_impl_proxy_s.obj: ecom_eiffel_compiler_ieiffelclassdescriptor_impl_proxy_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelclusterdescriptor_impl_proxy_s.obj: ecom_eiffel_compiler_ieiffelclusterdescriptor_impl_proxy_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelclusterproperties_impl_proxy_s.obj: ecom_eiffel_compiler_ieiffelclusterproperties_impl_proxy_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelcompilerevents_impl_proxy_s.obj: ecom_eiffel_compiler_ieiffelcompilerevents_impl_proxy_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelcompiler_impl_proxy_s.obj: ecom_eiffel_compiler_ieiffelcompiler_impl_proxy_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelfeaturedescriptor_impl_proxy_s.obj: ecom_eiffel_compiler_ieiffelfeaturedescriptor_impl_proxy_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelprojectproperties_impl_proxy_s.obj: ecom_eiffel_compiler_ieiffelprojectproperties_impl_proxy_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelproject_impl_proxy_s.obj: ecom_eiffel_compiler_ieiffelproject_impl_proxy_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ieiffelsystembrowser_impl_proxy_s.obj: ecom_eiffel_compiler_ieiffelsystembrowser_impl_proxy_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ienumclass_impl_stub_s.obj: ecom_eiffel_compiler_ienumclass_impl_stub_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ienumcluster_impl_stub_s.obj: ecom_eiffel_compiler_ienumcluster_impl_stub_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?

wecom_eiffel_compiler_ienumfeature_impl_stub_s.obj: ecom_eiffel_compiler_ienumfeature_impl_stub_s.cpp
	$(CC) $(CFLAGS) -DWORKBENCH	$(OUTPUT_CMD)$@ $?
