#!/bin/sh

NEWFILES=no

allfiles () {
    cut -f 1 -d"	" < MANIFEST 
    find . -type f | grep -v /CVS/
}

# Remove obsolete files from MANIFEST.
allfiles | sort | uniq -d > MANIFEST.new
mv MANIFEST.new MANIFEST

for i in `allfiles | sort | uniq -u`; do
    NEWFILES=yes
    echo "$i	***** new file *****" >> MANIFEST
done

if test $NEWFILES = "yes"; then
    sort -o MANIFEST MANIFEST
    echo "new files found, check MANIFEST for '**** new file ****'"
fi
