#!/bin/sh

# Script to generate the wizard executables for Linux.
# It generates the Vision2 and Precompilation wizards and puts them in the delivery.

remtrace Building the Vision2 wizard
cd $EXPORT_DIR/vision2_wizard
untgz_ccode wizard
mkdir -p $INSTALL_DIR/studio/wizards/new_projects/vision2/spec/$ISE_PLATFORM
move wizard $INSTALL_DIR/studio/wizards/new_projects/vision2/spec/$ISE_PLATFORM
remtrace Vision2 wizard Built!

remtrace Building the Precompilation wizard
cd $EXPORT_DIR/precomp_wizard
untgz_ccode wizard
mkdir -p $INSTALL_DIR/studio/wizards/precompile/spec/$ISE_PLATFORM
move wizard $INSTALL_DIR/studio/wizards/precompile/spec/$ISE_PLATFORM
remtrace Precompilation wizard Built!
