#!/bin/bash

# Script to generate the wizard executables for Linux.
# It generates the Vision2 and Precompilation wizards and puts them in the delivery.

remtrace Building the Vision2 wizard
cd $EXPORT_DIR/vision2_wizard
untgz_ccode wizard
mkdir -p $INSTALL_DIR/studio/wizards/new_projects/vision2/spec/$ISE_PLATFORM
move wizard $INSTALL_DIR/studio/wizards/new_projects/vision2/spec/$ISE_PLATFORM
remtrace Vision2 wizard Built!

remtrace Building the Precompilation wizard
cd $EXPORT_DIR/precomp_wizard
untgz_ccode wizard
mkdir -p $INSTALL_DIR/studio/wizards/others/precompile/spec/$ISE_PLATFORM
move wizard $INSTALL_DIR/studio/wizards/others/precompile/spec/$ISE_PLATFORM

remtrace Building the EWF wizard
cd $EXPORT_DIR/ewf_wizard
untgz_ccode wizard
mkdir -p $INSTALL_DIR/studio/wizards/new_projects/ewf/spec/$ISE_PLATFORM
move wizard $INSTALL_DIR/studio/wizards/new_projects/ewf/spec/$ISE_PLATFORM
remtrace EWF wizard Built!

remtrace Building the Library wizard
cd $EXPORT_DIR/library_wizard
untgz_ccode wizard
mkdir -p $INSTALL_DIR/studio/wizards/new_projects/library/spec/$ISE_PLATFORM
move wizard $INSTALL_DIR/studio/wizards/new_projects/library/spec/$ISE_PLATFORM
remtrace Library wizard Built!

remtrace Building the WrapC wizard
cd $EXPORT_DIR/wrapc_wizard
untgz_ccode wizard
mkdir -p $INSTALL_DIR/studio/wizards/new_projects/wrapc/spec/$ISE_PLATFORM
move wizard $INSTALL_DIR/studio/wizards/new_projects/wrapc/spec/$ISE_PLATFORM
remtrace WrapC wizard Built!
