#!/bin/sh

# Script to generate the wizard executables for Linux.
# It generates the Vision2, Wizard and Precompilation wizards and puts them in the delivery.

echo Make the Vision2 wizard [y]? 
read rep
if [ $rep = y ]; then
	echo Building the Vision2 wizard
	# Launch the finalization.
	ecb -finalize -c_compile -config vision2_wizard.ecf
	# Copy the file.
	mkdir -p $ISE_EIFFEL/studio/wizards/new_projects/vision2/spec/$ISE_PLATFORM/
	cp EIFGENs/wizard/F_code/wizard $ISE_EIFFEL/studio/wizards/new_projects/vision2/spec/$ISE_PLATFORM/
	echo Vision2 wizard Built!
fi
echo Make the Wizard wizard [y]? 
read rep
if [ $rep = y ]; then
	echo Building the Wizard wizard
	# Launch the finalization.
	ecb -finalize -c_compile -config wizard_wizard.ecf
	# Copy the file.
	mkdir -p $ISE_EIFFEL/studio/wizards/new_projects/wizard/spec/$ISE_PLATFORM/
	cp EIFGENs/wizard/F_code/wizard $ISE_EIFFEL/studio/wizards/new_projects/wizard/spec/$ISE_PLATFORM/
	echo Wizard wizard Built!
fi
echo Make the Precompilation wizard [y]? 
read rep
if [ $rep = y ]; then
	echo Building the Precompilation wizard
	# Launch the finalization.
	ecb -finalize -c_compile -config precompile_wizard.ecf
	# Copy the file.
	mkdir $ISE_EIFFEL/studio/wizards/precompile/spec/$ISE_PLATFORM/
	cp EIFGENs/wizard/F_code/wizard $ISE_EIFFEL/studio/wizards/precompile/spec/$ISE_PLATFORM/
	echo Precompilation wizard Built!
fi



