<?php
// $Id$

/**
 * Implementation of hook_help().
 */
function isedoc_eis_help($path, $arg) {
  switch ($path) {
    case 'admin/content/isedoc_eis':
      $output = '<p>'. t("Administrate the EIS mapping.") .'</p>';
      return $output;
    case 'admin/settings/isedoc_eis':
      return t("Configure the ISE Doc EIS mapping's settings.");
    default:
      return null;
  }
}

/**
 * Implementation of hook_perm().
 */
function isedoc_eis_perm() {
  return array('access content','access eis', 'edit eis');
}

/**
 * Implementation of hook_menu().
 */
function isedoc_eis_menu() {
  $items = array();
  
  $items['admin/content/isedoc_eis'] = array(
    'title' => '(ISE) EIS mapping ...',
    'page callback' => 'isedoc_eis_admin_content',
    'page arguments' => array(),
    'access arguments' => array('access eis'),
    'type' => MENU_CALLBACK,
    'file' => 'isedoc_eis.admin.inc',
    'description' => 'List of all EIS mappers.',
  );

  $items['admin/settings/isedoc/isedoc_eis'] = array(
    'title' => t('EIS mapping'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('isedoc_eis_admin_settings'),
    'file' => 'isedoc_eis.admin.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['node/%node/eismapping'] = array(
    'title' => t('EIS'),
    'page callback' => 'isedoc_eis_mapping',
    'page arguments' => array(1),
    'access arguments' => array('access eis'),
    'file' => 'isedoc_eis.query.inc',
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
  );

  $items['isedoc/eis/%'] = array(
    'title' => t('Redirect using EIS entry'),
    'page callback' => 'isedoc_eis_query',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'file' => 'isedoc_eis.query.inc',
    'type' => MENU_CALLBACK,
  );
  $items['isedoc/edit/eis/%'] = array(
    'title' => t('Edit EIS entry association'),
    'page callback' => 'isedoc_eis_query_edit',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('edit eis'),
    'file' => 'isedoc_eis.edit.inc',
  );

  $items['isedoc/edit/eis/%/%'] = array(
    'title' => t('Edit EIS entry association'),
    'page callback' => 'isedoc_eis_query_edit',
    'page arguments' => array(3,4),
    'type' => MENU_CALLBACK,
    'access arguments' => array('edit eis'),
    'file' => 'isedoc_eis.edit.inc',
  );

  return $items;
}

/**
 * Implementation of hook_theme() registry.
function isedoc_eis_theme() {
  return array(
    'isedoc_eis_form' => array(
      'arguments' => array('form' => NULL),
      'file' => 'isedoc_eis.admin.inc',
    ),
  );
}
 **/

?>
