<?php
// $Id$

function isedoc_help($path, $arg) {
	$output = '';
	switch ($path) {
		case "admin/help#isedoc":
		$output = '<p>'.t("Import/Export books").'</p>';
		break;
	}
	return $output;
} // function isedoc_help

function isedoc_block($op = 'list', $delta = 0) {
	if ($op == 'list') {
		$block[0]["info"] = t('ISE docs');
		return $block;
	} else if ($op == 'view') {
		$block_content = '';
		$links = array();
		if (user_access('import isedoc')) {
			if (module_exists('isedoc_import')) {
			  $links[] = l('Import into...','admin/content/isedoc_import');
			} else {
			  $links[] = l('Enabled Import ...','admin/build/modules');
			}
		}
		if (user_access('export isedoc')) {
			if (module_exists('isedoc_export')) {
			  $links[] = l('Export from ...','admin/content/isedoc_export');
			} else {
			  $links[] = l('Enabled Export ...','admin/build/modules');
			}
		}
		$n = menu_get_object();
		if ($n) {
		  $links[] = l('What links here','node/'.$n->nid.'/whatlinkshere');
		}

		$block_content .= theme('item_list', $links);
		if ($block_content == '') {
			return;
		}
		$block['subject'] = 'Doc Control';
		$block['content'] = $block_content;
		return $block;
	}
} // function isedoc_block

function isedoc_menu() {
  $items = array();
  $items['admin/settings/isedoc'] = array(
    'title' => 'IseDoc',
    'description' => 'ISE Documentation settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('isedoc_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'isedoc.admin.inc',
  );
  $items['admin/settings/isedoc/nodes'] = array(
    'title' => 'General',
    'description' => 'General Settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('isedoc_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'isedoc.admin.inc',
    'weight' => '-10',
  );  
  $items['node/%node/whatlinkshere'] = array(
    'title' => t('References'),
    'page callback' => 'isedoc_whatlinkshere',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'isedoc.whatlinkshere.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

?>
