indexing
	description: "Objects that represent an EV_DIALOG.%
		%The original version of this class was generated by EiffelBuild."
	date: "$Date$"
	revision: "$Revision$"

deferred class
	PROGRESS_DIALOG_IMP

inherit
	EV_DIALOG
		redefine
			initialize, is_in_default_state
		end
			
	CONSTANTS
		undefine
			is_equal, default_create, copy
		end

-- This class is the implementation of an EV_DIALOG generated by EiffelBuild.
-- You should not modify this code by hand, as it will be re-generated every time
-- modifications are made to the project.

feature {NONE}-- Initialization

	initialize is
			-- Initialize `Current'.
		do
			Precursor {EV_DIALOG}
			initialize_constants
			
				-- Create all widgets.
			create cancel_button
			create l_ev_vertical_box_1
			create progress_bar
			create l_ev_vertical_box_2
			create heading_label
			create l_ev_vertical_box_3
			create status_label
			
				-- Build_widget_structure.
			extend (cancel_button)
			cancel_button.extend (l_ev_vertical_box_1)
			l_ev_vertical_box_1.extend (progress_bar)
			cancel_button.extend (l_ev_vertical_box_2)
			l_ev_vertical_box_2.extend (heading_label)
			cancel_button.extend (l_ev_vertical_box_3)
			l_ev_vertical_box_3.extend (status_label)
			
			cancel_button.set_padding_width (5)
			cancel_button.set_border_width (2)
			cancel_button.disable_item_expand (l_ev_vertical_box_1)
			cancel_button.disable_item_expand (l_ev_vertical_box_2)
			cancel_button.disable_item_expand (l_ev_vertical_box_3)
			l_ev_vertical_box_1.set_padding_width (5)
			l_ev_vertical_box_1.set_border_width (inner_border_width)
			l_ev_vertical_box_1.disable_item_expand (progress_bar)
			progress_bar.set_minimum_width (15)
			progress_bar.set_minimum_height (25)
			progress_bar.set_leap (1)
			l_ev_vertical_box_2.set_padding_width (5)
			l_ev_vertical_box_2.set_border_width (inner_border_width)
			heading_label.align_text_left
			l_ev_vertical_box_3.set_padding_width (5)
			l_ev_vertical_box_3.set_border_width (inner_border_width)
			l_ev_vertical_box_3.disable_item_expand (status_label)
			status_label.align_text_left
			set_minimum_width (dialog_width)
			set_minimum_height (dialog_short_height)
			disable_user_resize
			set_maximum_width (dialog_width)
			set_maximum_height (dialog_tall_height)
			set_title ("Progress")
			
				--Connect events.
				-- Close the application when an interface close
				-- request is recieved on `Current'. i.e. the cross is clicked.

				-- Call `user_initialization'.
			user_initialization
		end

feature -- Access

	progress_bar: EV_HORIZONTAL_PROGRESS_BAR
	cancel_button: EV_VERTICAL_BOX
	l_ev_vertical_box_1: EV_VERTICAL_BOX
	l_ev_vertical_box_2: EV_VERTICAL_BOX
	l_ev_vertical_box_3: EV_VERTICAL_BOX
	heading_label: EV_LABEL
	status_label: EV_LABEL

feature {NONE} -- Implementation

	is_in_default_state: BOOLEAN is
			-- Is `Current' in its default state?
		do
			-- Re-implement if you wish to enable checking
			-- for `Current'.
			Result := True
		end
	
	user_initialization is
			-- Feature for custom initialization, called at end of `initialize'.
		deferred
		end
	
end -- class PROGRESS_DIALOG_IMP
