indexing
	description: "Objects that represent an EV_TITLED_WINDOW.%
		%The original version of this class was generated by EiffelBuild."
	date: "$Date$"
	revision: "$Revision$"

deferred class
	SEARCH_CONTROL_IMP

inherit
	EV_HORIZONTAL_BOX
		redefine
			initialize, is_in_default_state
		end
			
	CONSTANTS
		undefine
			is_equal, default_create, copy
		end

-- This class is the implementation of an EV_TITLED_WINDOW generated by EiffelBuild.
-- You should not modify this code by hand, as it will be re-generated every time
-- modifications are made to the project.

feature {NONE}-- Initialization

	initialize is
			-- Initialize `Current'.
		do
			Precursor {EV_HORIZONTAL_BOX}
			initialize_constants
			
				-- Create all widgets.
			create l_ev_label_1
			create search_text
			create search_button
			
				-- Build_widget_structure.
			extend (l_ev_label_1)
			extend (search_text)
			extend (search_button)
			
			l_ev_label_1.set_text ("Find: ")
			search_text.set_minimum_width (100)
			search_button.set_text ("Find")
			search_button.set_minimum_width (button_width)
			set_padding_width (box_padding_width)
			set_border_width (box_border_width)
			disable_item_expand (l_ev_label_1)
			disable_item_expand (search_text)
			disable_item_expand (search_button)
			
				--Connect events.
				-- Close the application when an interface close
				-- request is recieved on `Current'. i.e. the cross is clicked.

				-- Call `user_initialization'.
			user_initialization
		end

feature -- Access

	search_button: EV_BUTTON
	l_ev_label_1: EV_LABEL
	search_text: EV_TEXT_FIELD

feature {NONE} -- Implementation

	is_in_default_state: BOOLEAN is
			-- Is `Current' in its default state?
		do
			-- Re-implement if you wish to enable checking
			-- for `Current'.
			Result := True
		end
	
	user_initialization is
			-- Feature for custom initialization, called at end of `initialize'.
		deferred
		end
	
end -- class SEARCH_CONTROL_IMP
