class 
	APPLICATION_IDS

feature -- Access

	Proxy_stub_file_edit_constant: INTEGER is 1030
	About_button_constant: INTEGER is 1017
	Wizard_bitmap_constant: INTEGER is 1006
	Idl_static_constant: INTEGER is 1008
	Universal2_radio_constant: INTEGER is 1024
	Client_check_constant: INTEGER is 1019
	Definition_file_edit_constant: INTEGER is 1007
	Location_static_constant: INTEGER is -1
	Universal_radio_constant: INTEGER is 1026
	Remote_check_constant: INTEGER is 1015
	Standard_radio_constant: INTEGER is 1027
	Marshaling2_static_constant: INTEGER is 1022
	Type2_static_constant: INTEGER is 1023
	Local_check_constant: INTEGER is 1014
	Marshaling_static_constant: INTEGER is 1025
	Generate_static_constant: INTEGER is 1011
	Wizard_final_dialog_constant: INTEGER is 104
	Browse_button_constant: INTEGER is 1009
	Wizard_ps_dialog_constant: INTEGER is 103
	Wizard_initial_dialog_constant: INTEGER is 101
	Generate_edit_constant: INTEGER is 1010
	Virtual_table2_radio_constant: INTEGER is 1027
	Automation2_radio_constant: INTEGER is 1026
	In_process_check_constant: INTEGER is 1013
	Generate_code_static_constant: INTEGER is 1021
	Browse2_button_constant: INTEGER is 1012
	Server_check_constant: INTEGER is 1020
	Wizard_idl_dialog_constant: INTEGER is 102
	Standard2_radio_constant: INTEGER is 1025
	Wizard_ouput_dialog_constant: INTEGER is 105
	Proxy_stub_static_constant: INTEGER is 1028
	Help_button_constant: INTEGER is 1018
	Output_Progress_constant: INTEGER is 1031
	Output_Static_constant: INTEGER is 1032
	Toolbar_bitmap_constant: INTEGER is 113
	New_id: INTEGER is 1
	Open_id:INTEGER is 2
	Save_id:INTEGER is 3
	Clear_id: INTEGER is 4
	Launch_id: INTEGER is 5
	Exit_id: INTEGER is 6

end -- class APPLICATION_IDS

--|-------------------------------------------------------------------
--| This class was automatically generated by Resource Bench
--| Copyright (C) 1996-1997, Interactive Software Engineering, Inc.
--|
--| 270 Storke Road, Suite 7, Goleta, CA 93117 USA
--| Telephone 805-685-1006
--| Fax 805-685-6869
--| Information e-mail <info@eiffel.com>
--| Customer support e-mail <support@eiffel.com>
--|-------------------------------------------------------------------
