
--| Copyright (c) 1993-2018 University of Southern California and contributors.
--| All rights reserved.
--| Your use of this work is governed under the terms of the GNU General
--| Public License version 2.

class TEST

create
	make

feature
	
	make (args: ARRAY [STRING])
		local
			a: ARRAY [ANY]
			k, count: INTEGER
		do
			count := args [1].to_integer
			from
				k := 1
			until
				k > count
			loop
				a := << 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (),
					strip (),
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (),
					strip (),
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (),
					strip (),
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (),
					strip (),
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (), 
					strip (),
					strip ()
					>>
				k := k + 1
			end
		end

end
