FROM ubuntu:18.04

LABEL maintainer="Jocelyn Fiat <jfiat@eiffel.com>"

RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
        ca-certificates curl \
        bzip2 \
        gcc make dist \
        libxtst-dev \
        libgtk2.0-dev \
        libssl-dev \
		pax \
		dos2unix \
		subversion \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#Define delivery variables
ENV ISE_PLATFORM=linux-x86-64
ENV SVN_EIFFELSTUDIO_REPO=https://svn.eiffel.com/eiffelstudio
ENV SVN_ISE_REPO=svn://svn.ise/ise_svn
ENV EIFFEL_SETUP_CHANNEL=nightly
#ENV SVN_EIFFELSTUDIO_REPO_REVISION=HEAD

RUN mkdir -p /home/eiffel
COPY ./src/build_porterpackage.sh /home/eiffel/build_porterpackage.sh
RUN mkdir -p /home/eiffel/deliv/output \
	&& dos2unix /home/eiffel/build_porterpackage.sh

VOLUME /home/eiffel/deliv/output
VOLUME /home/eiffel/Eiffel-nightly

WORKDIR /home/eiffel
#ENTRYPOINT ["/bin/bash", "/home/eiffel/build_porterpackage.sh", "/home/eiffel/deliv"]
CMD /bin/bash /home/eiffel/build_porterpackage.sh /home/eiffel/deliv

