FROM ubuntu:18.04

LABEL maintainer="Jocelyn Fiat <jfiat@eiffel.com>"

RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
        ca-certificates curl \
        bzip2 \
        gcc make dist \
        libxtst-dev \
        libgtk2.0-dev \
        libgtk-3-dev \
        libgdk-pixbuf2.0-dev \
        libssl-dev \
		pax \
		dos2unix \
		subversion \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#Define delivery variables
ENV USER_ID=1001 USER_GID=1001

ENV ISE_PLATFORM=linux-x86-64
ENV SVN_EIFFELSTUDIO_REPO=https://svn.eiffel.com/eiffelstudio
ENV SVN_ISE_REPO=svn://svn.ise/ise_svn
ENV EIFFEL_SETUP_CHANNEL=nightly
#ENV SVN_EIFFELSTUDIO_REPO_REVISION=HEAD

RUN mkdir -p /home/eiffel/deliv/output && mkdir /home/eiffel/workspace
COPY ./src/build_porterpackage.sh /home/eiffel/build_porterpackage.sh
RUN dos2unix /home/eiffel/build_porterpackage.sh

VOLUME /home/eiffel/deliv/output
VOLUME /home/eiffel/Eiffel

# now creating user
RUN groupadd --gid "${USER_GID}" "eiffel" && \
    useradd \
      --uid ${USER_ID} \
      --gid ${USER_GID} \
      --shell /bin/bash \
      eiffel && \
      chown -R eiffel:${USER_GID} /home/eiffel && \
      chmod a+w -R /home/eiffel/workspace

USER eiffel
WORKDIR /home/eiffel
CMD /bin/bash /home/eiffel/build_porterpackage.sh /home/eiffel/deliv

