#!/bin/sh

echo Welcome to the ISE Eiffel 5 installer

ERROR_ENV=""
if [ ! "$ISE_EIFFEL" ]; then
	echo "The environment variable ISE_EIFFEL should be set to the directory where ISE Eiffel 5 is installed (typically the current directory: `pwd`)"
	ERROR_ENV=TRUE
fi
if [ ! "$ISE_PLATFORM" ]; then
	echo The environment variable ISE_PLATFORM should be set to one of these values, depending on your platform:
	echo linux-glibc2.1, linux-glibc, sgi, sgi-64, solaris, solaris-2.5+, alpha or unixware.
	ERROR_ENV=TRUE
fi
if [ "ERROR_ENV" = "TRUE" ]; then
	echo "When the needed environment variable(s) are set, launch $0 again."
	exit
fi

echo "Do you want to precompile EiffelBase (recommended) ? [y/n]"
read prec_base
echo "Do you want to precompile EiffelVision2 (recommended if you intend to develop Vision2-based applications) ? [y/n]"
read prec_vision2

INIT_DIR=`pwd`

echo Compile the C code of the libraries
source compile_libraries

echo Generate the proper Ace files for precompilation
mv $ISE_EIFFEL/precomp/spec/unix $ISE_EIFFEL/precomp/spec/$ISE_PLATFORM

if [ "$prec_base" != "n" ]; then
	echo Precompile EiffelBase
	cd $ISE_EIFFEL/precomp/spec/$ISE_PLATFORM/base
	ec -precompile -ace Ace.ace
fi
if [ "$prec_vision2" != "n" ]; then
	echo Precompile EiffelVision2
	cd $ISE_EIFFEL/precomp/spec/$ISE_PLATFORM/vision2
	ec -precompile -ace Ace.ace
fi

