note
	description: "[
			Summary description for {$TEST_CLASS_NAME}.
			This class is generated by {EW_EQA_TEST_EWEASEL_TCF_CONVERTER}
		]"

class
	$TEST_CLASS_NAME

inherit
	EQA_EW_SYSTEM_TEST_SET

feature -- Command$TCF_CONTENT

end
