note
	description: "[
					Generated by EiffelRibbon tool
																							]"
	date: "$Date$"
	revision: "$Revision$"

class
	GROUP_5

inherit
	GROUP_5_IMP

create
	{EV_RIBBON_TAB} make_with_command_list
	
end

