note
	description: "[
					Generated by EiffelRibbon tool
					Don't edit this file, since it will be replaced by EiffelRibbon tool
					generated files everytime
																							]"
	date: "$Date$"
	revision: "$Revision$"

deferred class
	GROUP_SPLIT_BUTTON_IMP

inherit
	EV_RIBBON_GROUP

feature {NONE} -- Initialization

	create_interface_objects
			-- Create objects
		do
			create split_button.make_with_command_list (<<{COMMAND_NAME_CONSTANTS}.split_button>>)

			create buttons.make (1)
			buttons.extend (split_button)

		end

feature -- Query

	split_button: SPLIT_BUTTON


end

