// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define tab_button 2 
#define tab_button_LabelTitle_RESID 60001
#define tab_button_Keytip_RESID 60002
#define group_button 3 
#define group_button_Keytip_RESID 60003
#define button_change_label_title 4 
#define button_change_label_title_LabelTitle_RESID 60004
#define button_change_label_title_Keytip_RESID 60005
#define button_change_small_image 5 
#define button_change_small_image_LabelTitle_RESID 60006
#define button_change_small_image_Keytip_RESID 60007
#define button_set_tooltip_title 6 
#define button_set_tooltip_title_LabelTitle_RESID 60008
#define button_set_tooltip_title_Keytip_RESID 60009
#define button_set_tooltip_description 7 
#define button_set_tooltip_description_LabelTitle_RESID 60010
#define button_set_tooltip_title_and_description 8 
#define button_set_tooltip_title_and_description_LabelTitle_RESID 60011
#define group_button_2 9 
#define group_button_2_Keytip_RESID 60012
#define button_change_large_image 10 
#define button_change_large_image_LabelTitle_RESID 60013
#define button_change_large_image_LargeImages_RESID 60014
#define tab_toggle_button 11 
#define tab_toggle_button_LabelTitle_RESID 60015
#define group_toggle_button 12 
#define toggle_button_check_state 13 
#define toggle_button_check_state_LabelTitle_RESID 60016
#define toggle_button_change_small_image 14 
#define toggle_button_change_small_image_LabelTitle_RESID 60017
#define group_toggle_button_2 15 
#define toggle_button_change_large_image 16 
#define toggle_button_change_large_image_LabelTitle_RESID 60018
#define tab_check_box 17 
#define tab_check_box_LabelTitle_RESID 60019
#define group_check_box 18 
#define checkbox_check_state 19 
#define checkbox_check_state_LabelTitle_RESID 60020
#define tab_spinner 20 
#define tab_spinner_LabelTitle_RESID 60021
#define group_spinner 21 
#define spinner 22 
#define spinner_LabelTitle_RESID 60022
#define spinner_query_value_button 23 
#define spinner_query_value_button_LabelTitle_RESID 60023
#define tab_combo_box 24 
#define tab_combo_box_LabelTitle_RESID 60024
#define group_combo_box 25 
#define combobox 26 
#define combobox_LabelTitle_RESID 60025
#define combo_box_query_selected_index_button 27 
#define combo_box_query_selected_index_button_LabelTitle_RESID 60026
#define tab_split_button 28 
#define tab_split_button_LabelTitle_RESID 60027
#define group_split_button 29 
#define split_button 30 
#define split_button_LabelTitle_RESID 60028
#define split_button_child_1 31 
#define split_button_child_1_LabelTitle_RESID 60029
#define split_button_child_2 32 
#define split_button_child_2_LabelTitle_RESID 60030
#define split_button_change_small_image 33 
#define split_button_change_small_image_child_1 34 
#define split_button_change_small_image_child_1_LabelTitle_RESID 60031
#define split_button_change_small_image_child_1_SmallImages_RESID 60032
#define split_button_change_small_image_child_2 35 
#define split_button_change_small_image_child_2_LabelTitle_RESID 60033
#define group_split_button_2 36 
#define split_button_change_large_image 37 
#define split_button_change_large_image_child_1 38 
#define split_button_change_large_image_child_1_LabelTitle_RESID 60034
#define split_button_change_large_image_child_2 39 
#define split_button_change_large_image_child_2_LabelTitle_RESID 60035
#define tab_dropdown_gallery 40 
#define tab_dropdown_gallery_LabelTitle_RESID 60036
#define group_dropdown_gallery 41 
#define drop_down_gallery 42 
#define drop_down_gallery_LabelTitle_RESID 60037
#define drop_down_gallery_LargeImages_RESID 60038
#define application_menu 43 
#define menu_group 44 
#define application_menu_button 45 
#define application_menu_button_LabelTitle_RESID 60039
#define InternalCmd2_LabelTitle_RESID 60040
