note
	description: "[
					Generated by EiffelRibbon tool
																							]"
	date: "$Date$"
	revision: "$Revision$"

class
	TAB_SPLIT_BUTTON

inherit
	TAB_SPLIT_BUTTON_IMP

create
	{EV_RIBBON} make_with_command_list
	
end

