.TH CECIL 1  "November 10, 1999" "ISE" "CECIL Programmer's Manual"
.SH NAME
attribute_exists	\- Does attribute exist or is visible? 
.SH SYNOPSYS
.nf
\fB#include "eif_cecil.h"\fB
.sp
.BI "EIF_BOOLEAN attribute_exists (EIF_REFERENCE " object ", char * " name "); "
.fi
.SH DESCRIPTION
The \fBattribute_exists()\fP macro returns \fBEIF_TRUE\fP or \fBEIF_FALSE\fP
when the attribute of name \fIname\fP exists in the Eiffel object (reference) \fIref\fB.
.SH RETURN VALUE
\fBEIF_TRUE\fP or \fBEIF_FALSE\fP.
.SH CONFORMANCE
ISE Eiffel 4.5 and later.
.SH SEE ALSO
.BR "eif_attribute "(1). " 


