indexing
	Generator: "Eiffel Emitter 2.7b2"
	external_name: "System.Runtime.Remoting.Channels.IClientFormatterSinkProvider"

deferred external class
	SYSTEM_RUNTIME_REMOTING_CHANNELS_ICLIENTFORMATTERSINKPROVIDER

inherit
	SYSTEM_RUNTIME_REMOTING_CHANNELS_ICLIENTCHANNELSINKPROVIDER

end -- class SYSTEM_RUNTIME_REMOTING_CHANNELS_ICLIENTFORMATTERSINKPROVIDER
