indexing
	Generator: "Eiffel Emitter 2.7b2"
	external_name: "System.Runtime.Remoting.Channels.IServerFormatterSinkProvider"

deferred external class
	SYSTEM_RUNTIME_REMOTING_CHANNELS_ISERVERFORMATTERSINKPROVIDER

inherit
	SYSTEM_RUNTIME_REMOTING_CHANNELS_ISERVERCHANNELSINKPROVIDER

end -- class SYSTEM_RUNTIME_REMOTING_CHANNELS_ISERVERFORMATTERSINKPROVIDER
